In [2]:
import torch
import numpy as np
import array


In [3]:
torch.__version__

'1.12.1+cu116'

In [4]:
t = torch.tensor(1)

In [5]:
t

tensor(1)

In [6]:
t.shape

torch.Size([])

In [7]:
x = t + torch.tensor([1, 2])

In [8]:
x

tensor([2, 3])

In [9]:
x.shape

torch.Size([2])

In [10]:
a = "12"

In [11]:
torch.is_tensor(a)

False

In [12]:
torch.is_tensor(x)

True

In [13]:
torch.is_floating_point(x)

False

In [14]:
torch.is_nonzero(x[0])

True

In [15]:
y = torch.tensor((1.3, 2.4))

In [16]:
y.dtype

torch.float32

In [17]:
torch.tensor(np.linspace(0, 30, 10).reshape(1, 5, 2)).shape

torch.Size([1, 5, 2])

In [18]:
torch.tensor(np.linspace(0, 30, 10).reshape(1, 5, 2)).dim()

3

In [19]:
torch.tensor(np.linspace(0, 30, 10).reshape(1, 5, 2)).size()

torch.Size([1, 5, 2])

In [20]:
x = torch.tensor(np.linspace(0, 30, 10).reshape(1, 5, 2))

In [21]:
y = [1, 2, 3]
x = torch.tensor(y)
y.append(4)
print(x, y)

tensor([1, 2, 3]) [1, 2, 3, 4]


In [22]:
y = [1, 2, 3]
x = torch.tensor(y)
y[0] = 20
print(x, y)

tensor([1, 2, 3]) [20, 2, 3]


In [23]:
y = np.array([1, 2, 3])
x = torch.as_tensor(y)
y[0] = 20
print(x, y)

tensor([20,  2,  3]) [20  2  3]


In [24]:
x = torch.from_numpy(y).cuda()
y[0] = -1
print(x, y)

tensor([20,  2,  3], device='cuda:0') [-1  2  3]


In [25]:
y = np.array([1, 2, 3])
x = torch.as_tensor(y).cuda()
y[0] = 20
print(x, y)

tensor([1, 2, 3], device='cuda:0') [20  2  3]


In [26]:
x.detach().cpu()[0] = 4

In [27]:
x = torch.tensor([[1]])

In [28]:
x.item()

1

In [29]:
x = torch.from_numpy(np.random.standard_normal((2, 3, 5)))

In [30]:
x, x.shape

(tensor([[[-1.0167, -0.5739,  0.3380, -0.2852,  0.1838],
          [ 0.0043,  0.0866,  0.1194,  0.3638,  1.6323],
          [ 1.2208,  0.4956, -0.4026, -1.2917,  0.6575]],
 
         [[ 1.6654, -1.2402, -1.3954,  0.2543,  0.5615],
          [ 1.2787,  1.0393, -0.0894,  1.2436, -1.1498],
          [ 0.7018, -0.5111, -0.2880, -0.2063,  0.8071]]], dtype=torch.float64),
 torch.Size([2, 3, 5]))

In [31]:
x.T, x.T.shape

/tmp/ipykernel_8635/3687214812.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matricesor `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2981.)
  x.T, x.T.shape


(tensor([[[-1.0167,  1.6654],
          [ 0.0043,  1.2787],
          [ 1.2208,  0.7018]],
 
         [[-0.5739, -1.2402],
          [ 0.0866,  1.0393],
          [ 0.4956, -0.5111]],
 
         [[ 0.3380, -1.3954],
          [ 0.1194, -0.0894],
          [-0.4026, -0.2880]],
 
         [[-0.2852,  0.2543],
          [ 0.3638,  1.2436],
          [-1.2917, -0.2063]],
 
         [[ 0.1838,  0.5615],
          [ 1.6323, -1.1498],
          [ 0.6575,  0.8071]]], dtype=torch.float64),
 torch.Size([5, 3, 2]))

In [32]:
# view of x
y = x.T

In [33]:
y[0][0][0] = -6

In [34]:
x

tensor([[[-6.0000e+00, -5.7389e-01,  3.3795e-01, -2.8518e-01,  1.8382e-01],
         [ 4.2907e-03,  8.6559e-02,  1.1941e-01,  3.6382e-01,  1.6323e+00],
         [ 1.2208e+00,  4.9561e-01, -4.0260e-01, -1.2917e+00,  6.5753e-01]],

        [[ 1.6654e+00, -1.2402e+00, -1.3954e+00,  2.5430e-01,  5.6154e-01],
         [ 1.2787e+00,  1.0393e+00, -8.9394e-02,  1.2436e+00, -1.1498e+00],
         [ 7.0182e-01, -5.1110e-01, -2.8802e-01, -2.0626e-01,  8.0711e-01]]],
       dtype=torch.float64)

In [35]:
z = x.permute((2, 1, 0))

In [36]:
z

tensor([[[-6.0000e+00,  1.6654e+00],
         [ 4.2907e-03,  1.2787e+00],
         [ 1.2208e+00,  7.0182e-01]],

        [[-5.7389e-01, -1.2402e+00],
         [ 8.6559e-02,  1.0393e+00],
         [ 4.9561e-01, -5.1110e-01]],

        [[ 3.3795e-01, -1.3954e+00],
         [ 1.1941e-01, -8.9394e-02],
         [-4.0260e-01, -2.8802e-01]],

        [[-2.8518e-01,  2.5430e-01],
         [ 3.6382e-01,  1.2436e+00],
         [-1.2917e+00, -2.0626e-01]],

        [[ 1.8382e-01,  5.6154e-01],
         [ 1.6323e+00, -1.1498e+00],
         [ 6.5753e-01,  8.0711e-01]]], dtype=torch.float64)

In [37]:
# View
z[0] *= 2

In [38]:
z

tensor([[[-1.2000e+01,  3.3308e+00],
         [ 8.5814e-03,  2.5573e+00],
         [ 2.4416e+00,  1.4036e+00]],

        [[-5.7389e-01, -1.2402e+00],
         [ 8.6559e-02,  1.0393e+00],
         [ 4.9561e-01, -5.1110e-01]],

        [[ 3.3795e-01, -1.3954e+00],
         [ 1.1941e-01, -8.9394e-02],
         [-4.0260e-01, -2.8802e-01]],

        [[-2.8518e-01,  2.5430e-01],
         [ 3.6382e-01,  1.2436e+00],
         [-1.2917e+00, -2.0626e-01]],

        [[ 1.8382e-01,  5.6154e-01],
         [ 1.6323e+00, -1.1498e+00],
         [ 6.5753e-01,  8.0711e-01]]], dtype=torch.float64)

In [39]:
x

tensor([[[-1.2000e+01, -5.7389e-01,  3.3795e-01, -2.8518e-01,  1.8382e-01],
         [ 8.5814e-03,  8.6559e-02,  1.1941e-01,  3.6382e-01,  1.6323e+00],
         [ 2.4416e+00,  4.9561e-01, -4.0260e-01, -1.2917e+00,  6.5753e-01]],

        [[ 3.3308e+00, -1.2402e+00, -1.3954e+00,  2.5430e-01,  5.6154e-01],
         [ 2.5573e+00,  1.0393e+00, -8.9394e-02,  1.2436e+00, -1.1498e+00],
         [ 1.4036e+00, -5.1110e-01, -2.8802e-01, -2.0626e-01,  8.0711e-01]]],
       dtype=torch.float64)

In [40]:
x.shape

torch.Size([2, 3, 5])

In [41]:
x.T

tensor([[[-1.2000e+01,  3.3308e+00],
         [ 8.5814e-03,  2.5573e+00],
         [ 2.4416e+00,  1.4036e+00]],

        [[-5.7389e-01, -1.2402e+00],
         [ 8.6559e-02,  1.0393e+00],
         [ 4.9561e-01, -5.1110e-01]],

        [[ 3.3795e-01, -1.3954e+00],
         [ 1.1941e-01, -8.9394e-02],
         [-4.0260e-01, -2.8802e-01]],

        [[-2.8518e-01,  2.5430e-01],
         [ 3.6382e-01,  1.2436e+00],
         [-1.2917e+00, -2.0626e-01]],

        [[ 1.8382e-01,  5.6154e-01],
         [ 1.6323e+00, -1.1498e+00],
         [ 6.5753e-01,  8.0711e-01]]], dtype=torch.float64)

In [42]:
x.mT

tensor([[[-1.2000e+01,  8.5814e-03,  2.4416e+00],
         [-5.7389e-01,  8.6559e-02,  4.9561e-01],
         [ 3.3795e-01,  1.1941e-01, -4.0260e-01],
         [-2.8518e-01,  3.6382e-01, -1.2917e+00],
         [ 1.8382e-01,  1.6323e+00,  6.5753e-01]],

        [[ 3.3308e+00,  2.5573e+00,  1.4036e+00],
         [-1.2402e+00,  1.0393e+00, -5.1110e-01],
         [-1.3954e+00, -8.9394e-02, -2.8802e-01],
         [ 2.5430e-01,  1.2436e+00, -2.0626e-01],
         [ 5.6154e-01, -1.1498e+00,  8.0711e-01]]], dtype=torch.float64)

In [43]:
x.mT.shape

torch.Size([2, 5, 3])

In [44]:
x = torch.from_numpy(np.random.standard_normal((2, 4, 3)))

In [45]:
x

tensor([[[-0.3826, -0.6037, -0.6748],
         [-1.8787, -0.2547, -0.0289],
         [-0.4818, -0.3606, -0.1400],
         [-0.1242, -0.7942, -0.9416]],

        [[-1.1494, -2.4842, -0.7269],
         [-0.1529, -0.1367,  0.6774],
         [-0.8078,  2.0476,  0.9494],
         [-0.3300,  0.1469, -0.5152]]], dtype=torch.float64)

In [46]:
x.permute((1, -1, 0))

tensor([[[-0.3826, -1.1494],
         [-0.6037, -2.4842],
         [-0.6748, -0.7269]],

        [[-1.8787, -0.1529],
         [-0.2547, -0.1367],
         [-0.0289,  0.6774]],

        [[-0.4818, -0.8078],
         [-0.3606,  2.0476],
         [-0.1400,  0.9494]],

        [[-0.1242, -0.3300],
         [-0.7942,  0.1469],
         [-0.9416, -0.5152]]], dtype=torch.float64)

In [47]:
x.permute((1, -1, 0)).shape

torch.Size([4, 3, 2])

In [48]:
torch.zeros((10, 5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [49]:
torch.ones((10, 5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [50]:
x.device

device(type='cpu')

In [51]:
torch.device("cpu")

device(type='cpu')

In [52]:
torch.device("cuda:0")

device(type='cuda', index=0)

In [53]:
# Product of x size shape
x.numel()

24

In [54]:
x.dtype

torch.float64

In [55]:
torch.get_default_dtype()

torch.float32

In [56]:
torch.set_default_dtype(torch.float64)
x = torch.tensor([2.0, 3.0])
x, x.dtype

(tensor([2., 3.]), torch.float64)

In [57]:
torch.get_default_dtype()

torch.float64

In [58]:
torch.set_default_dtype(torch.float32)

In [59]:
x = torch.tensor([2.0, 3.0])
x, x.dtype

(tensor([2., 3.]), torch.float32)

In [60]:
a = torch.tensor([1, 2, 3.], requires_grad=True).cuda()

In [61]:
b = torch.asarray(a)

In [62]:
b

tensor([1., 2., 3.], device='cuda:0')

In [63]:
b.requires_grad, b.device

(False, device(type='cuda', index=0))

In [64]:
a.requires_grad

True

In [65]:
b = torch.asarray(a, requires_grad=True)
b, b.device, b.requires_grad

(tensor([1., 2., 3.], device='cuda:0', grad_fn=<ToCopyBackward0>),
 device(type='cuda', index=0),
 True)

In [66]:
a *= 2
a, b

(tensor([2., 4., 6.], device='cuda:0', grad_fn=<MulBackward0>),
 tensor([2., 4., 6.], device='cuda:0', grad_fn=<MulBackward0>))

In [67]:
a.data_ptr() == b.data_ptr()

True

In [68]:
c = torch.asarray(a, copy=True)
c.data_ptr() == a.data_ptr()

False

In [69]:
a *= 2

In [70]:
a, b, c

(tensor([ 4.,  8., 12.], device='cuda:0', grad_fn=<MulBackward0>),
 tensor([ 4.,  8., 12.], device='cuda:0', grad_fn=<MulBackward0>),
 tensor([2., 4., 6.], device='cuda:0'))

In [71]:
c.data_ptr()

140351799034368

In [72]:
# Numpy data_ptr
np.array([1, 2, 3]).__array_interface__["data"][0]

94609805706240

In [73]:
a = array.array('i', [1, 2, 3])
b = torch.frombuffer(a, dtype=torch.int16)
b

tensor([1, 0, 2, 0, 3, 0], dtype=torch.int16)

In [74]:
c = array.array('u', ['A', 'B'])
b = torch.frombuffer(c, dtype=torch.int8)
b

tensor([65,  0,  0,  0, 66,  0,  0,  0], dtype=torch.int8)

In [75]:
x = torch.randn(5, 5)

In [76]:
x

tensor([[-0.3418,  0.2913,  0.4422, -0.9478, -2.1082],
        [-0.0315, -1.7208,  0.0347, -0.1945, -1.0246],
        [ 1.7817, -0.9046, -0.9375,  0.2244, -0.5881],
        [ 0.3344,  0.8130,  0.3590,  1.1079, -0.3558],
        [ 1.0216,  0.4711, -0.6301,  0.3078,  1.4080]])

In [77]:
t = torch.as_strided(x, (2, 2), (4, 6) )
t

tensor([[-0.3418, -1.7208],
        [-2.1082,  1.7817]])

In [78]:
t = torch.as_strided(x, (2, 2), (4, 6) , 1)
t


tensor([[ 0.2913,  0.0347],
        [-0.0315, -0.9046]])

In [79]:
t = torch.as_strided(x, (2, 2), (4, 6) , 2)
t



tensor([[ 0.4422, -0.1945],
        [-1.7208, -0.9375]])

In [80]:
t = torch.as_strided(x, (2, 2), (4, 6) , 14)
t

tensor([[-0.5881,  1.0216],
        [ 1.1079,  1.4080]])

In [81]:
t = torch.as_strided(x, (2, 2, 1), (4, 6, 1) , 14)
t



tensor([[[-0.5881],
         [ 1.0216]],

        [[ 1.1079],
         [ 1.4080]]])

In [82]:
x = torch.arange(1, 10, 0.5)
x

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000,
        5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000])

In [83]:
x = torch.linspace(1, 10, 5)
x

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [84]:
x = torch.range(1, 10, 2, dtype=torch.int32)
x

/tmp/ipykernel_8635/1458550859.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  x = torch.range(1, 10, 2, dtype=torch.int32)


tensor([1, 3, 5, 7, 9], dtype=torch.int32)

In [85]:
"""
(
base ** start,
base **(start+ steps−1 end−start),
base ** end
)
"""
torch.logspace(-3, 3, 5, base=2)

tensor([0.1250, 0.3536, 1.0000, 2.8284, 8.0000])

In [86]:
s = (10, 5)
y  = torch.zeros(s)
print(y)
x = torch.eye(3, 4, out=y)
x, y

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


(tensor([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]]),
 tensor([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]]))

In [87]:
x = torch.empty(size=s, dtype=torch.int32)
x

tensor([[1735617826,  577005919, 1663180858,  942684472,  761608249],
        [1650549042, 1714762797,  876096816, 1663908147,  845374004],
        [ 808661602,  576808038, 1830953004, 1952409459,  577073273],
        [1696735290, 1969448312, 1918854516, 1702195557,  740455539],
        [1702044192, 1869181811,  540680814,  929457442,  962935094],
        [1714498867,  875389751,  761410866,  878850914, 1681143341],
        [ 825516338, 1664103777,  539763253, 1702065442, 1835101810],
        [ 540680805,  909326114,  909390386, 1667312946,  875377713],
        [ 758330419, 1647862328,  895891501, 1681350960,  909259059],
        [ 539763251, 1919252002, 1852795251,  572537378,  573713973]],
       dtype=torch.int32)

In [88]:
z = torch.empty_like(x, device='cuda:0')
z

tensor([[1073741824, 1082130432, 1086324736,          0,          0],
        [         0,          0,          0,          0,          0],
        [         0,          0,          0,          0,          0],
        [         0,          0,          0,          0,          0],
        [         0,          0,          0,          0,          0],
        [         0,          0,          0,          0,          0],
        [         0,          0,          0,          0,          0],
        [         0,          0,          0,          0,          0],
        [         0,          0,          0,          0,          0],
        [         0,          0,          0,          0,          0]],
       device='cuda:0', dtype=torch.int32)

In [89]:
a = torch.empty_strided((3, 3), (1, 2))
a

tensor([[1.3058e+06, 2.7019e+00, 8.9683e-44],
        [3.0868e-41, 4.5793e-41, 0.0000e+00],
        [2.7019e+00, 8.9683e-44, 1.1210e-43]])

In [90]:
a.stride()

(1, 2)

In [91]:
a = torch.full((3, 4), 10, dtype=torch.int32)
a

tensor([[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]], dtype=torch.int32)

In [92]:
b = torch.full_like(a, 2)
b


tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]], dtype=torch.int32)

In [93]:
z = torch.tensor([-1.5, 0, 0.4, 2.])
torch.heaviside(z, torch.tensor(0.7))

tensor([0.0000, 0.7000, 1.0000, 1.0000])

In [94]:
x = np.random.uniform(-1, 1, (10, ))
y = torch.from_numpy(x)
y = torch.abs(y)
x, y

(array([ 0.16550526,  0.96500488, -0.14495367, -0.54093585,  0.83232426,
         0.07820075, -0.27294538,  0.9457885 ,  0.37416238,  0.58761035]),
 tensor([0.1655, 0.9650, 0.1450, 0.5409, 0.8323, 0.0782, 0.2729, 0.9458, 0.3742,
         0.5876], dtype=torch.float64))

In [95]:
deg = np.pi / 4

torch.cos(torch.tensor(deg)), torch.sin(torch.tensor(deg)), torch.tan(torch.tensor(deg))


(tensor(0.7071), tensor(0.7071), tensor(1.))

In [96]:
a = torch.randn(4).uniform_(1, 2)
a = a.tolist() + [1.57]
a = torch.tensor(a)
a

tensor([1.6576, 1.5305, 1.6655, 1.0529, 1.5700])

In [97]:
torch.acosh(a)

tensor([1.0918, 0.9892, 1.0977, 0.3238, 1.0226])

In [98]:
torch.atanh(a)



tensor([nan, nan, nan, nan, nan])

In [99]:
torch.asinh(a)

tensor([1.2791, 1.2116, 1.2832, 0.9183, 1.2330])

In [100]:
torch.acos(torch.tensor([0.7071])) * 180 / np.pi

tensor([45.0005])

In [101]:
torch.asin(torch.tensor([np.sqrt(3) / 2])) * 180 / np.pi


tensor([60.0000], dtype=torch.float64)

In [102]:
"""out
i
​
 =input
i
​
 +alpha×other
i
​

"""
a = torch.randn(10)
b = torch.randn_like(a)
c = torch.add(a, b, alpha=10)
d = a + b
c, d, c-d


(tensor([  7.3790,   7.1874, -21.1222,  14.5005, -10.3309,  -3.9729,  11.7958,
          13.8140,   4.8689,  -5.9807]),
 tensor([ 1.7384,  1.4906, -2.7460,  0.8728, -1.9983,  0.4970,  2.9859,  1.6976,
         -0.0544,  0.4979]),
 tensor([  5.6405,   5.6968, -18.3762,  13.6276,  -8.3326,  -4.4699,   8.8099,
          12.1164,   4.9233,  -6.4786]))

In [103]:
torch.angle(torch.tensor([-1+1j, -2+2j, 3-3j])) * 180 / 3.14159

tensor([135.0001, 135.0001, -45.0000])

In [104]:
torch.bitwise_not(torch.tensor([-2, 0, 2], dtype=torch.int8))

tensor([ 1, -1, -3], dtype=torch.int8)

In [105]:
~-2, ~0, ~2

(1, -1, -3)

In [106]:
a = torch.tensor([-1, -2, 3], dtype=torch.int8)
b = torch.tensor([1, 0, 13], dtype=torch.int8)

In [107]:
a | b, torch.bitwise_or(a, b)


(tensor([-1, -2, 15], dtype=torch.int8),
 tensor([-1, -2, 15], dtype=torch.int8))

In [108]:
a & b, torch.bitwise_and(a, b)

(tensor([1, 0, 1], dtype=torch.int8), tensor([1, 0, 1], dtype=torch.int8))

In [109]:
a ^ b, torch.bitwise_xor(a, b)



(tensor([-2, -2, 14], dtype=torch.int8),
 tensor([-2, -2, 14], dtype=torch.int8))

In [110]:
~a, torch.bitwise_not(a)

(tensor([ 0,  1, -4], dtype=torch.int8),
 tensor([ 0,  1, -4], dtype=torch.int8))

In [111]:
a >> 2, torch.bitwise_right_shift(a, 2)

(tensor([-1, -1,  0], dtype=torch.int8),
 tensor([-1, -1,  0], dtype=torch.int8))

In [112]:
a << 2, torch.bitwise_left_shift(a, 2)

(tensor([-4, -8, 12], dtype=torch.int8),
 tensor([-4, -8, 12], dtype=torch.int8))

In [113]:
x = torch.randn(10)
y = torch.ceil(x)
x, y

(tensor([-1.0068, -0.0583, -1.7446,  1.0425,  0.5845,  0.1460, -0.3792,  0.5689,
         -2.2889,  0.1642]),
 tensor([-1., -0., -1.,  2.,  1.,  1., -0.,  1., -2.,  1.]))

In [114]:
torch.floor(x)

tensor([-2., -1., -2.,  1.,  0.,  0., -1.,  0., -3.,  0.])

In [115]:
torch.clamp(x, -0.5, 0.5)

tensor([-0.5000, -0.0583, -0.5000,  0.5000,  0.5000,  0.1460, -0.3792,  0.5000,
        -0.5000,  0.1642])

In [116]:
torch.clip(x, -0.5, 0.5)


tensor([-0.5000, -0.0583, -0.5000,  0.5000,  0.5000,  0.1460, -0.3792,  0.5000,
        -0.5000,  0.1642])

In [117]:
z = torch.linspace(-1, 1, steps=x.shape[0])
z

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])

In [118]:
x, z, torch.clamp(x, min=z)

(tensor([-1.0068, -0.0583, -1.7446,  1.0425,  0.5845,  0.1460, -0.3792,  0.5689,
         -2.2889,  0.1642]),
 tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
          0.7778,  1.0000]),
 tensor([-1.0000, -0.0583, -0.5556,  1.0425,  0.5845,  0.1460,  0.3333,  0.5689,
          0.7778,  1.0000]))

In [119]:
torch.copysign(x, 1)

tensor([1.0068, 0.0583, 1.7446, 1.0425, 0.5845, 0.1460, 0.3792, 0.5689, 2.2889,
        0.1642])

In [120]:
torch.copysign(x, -1)

tensor([-1.0068, -0.0583, -1.7446, -1.0425, -0.5845, -0.1460, -0.3792, -0.5689,
        -2.2889, -0.1642])

In [121]:
torch.rad2deg(x)

tensor([ -57.6827,   -3.3392,  -99.9559,   59.7323,   33.4912,    8.3656,
         -21.7253,   32.5927, -131.1439,    9.4100])

In [122]:
torch.deg2rad(x)



tensor([-0.0176, -0.0010, -0.0304,  0.0182,  0.0102,  0.0025, -0.0066,  0.0099,
        -0.0399,  0.0029])

In [123]:
torch.mul(x, y)

tensor([1.0068, 0.0000, 1.7446, 2.0850, 0.5845, 0.1460, 0.0000, 0.5689, 4.5778,
        0.1642])

In [124]:
torch.div(x, 2*x)

tensor([0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
        0.5000])

In [125]:
y = torch.randn((x.numel(), 1))

In [126]:
y

tensor([[-1.3639],
        [-0.2790],
        [ 1.1846],
        [-0.5830],
        [ 2.7489],
        [ 0.1846],
        [-0.4409],
        [-0.9860],
        [ 1.3114],
        [-0.9555]])

In [127]:
x / y

tensor([[  0.7381,   0.0427,   1.2791,  -0.7644,  -0.4286,  -0.1071,   0.2780,
          -0.4171,   1.6782,  -0.1204],
        [  3.6080,   0.2089,   6.2521,  -3.7362,  -2.0948,  -0.5233,   1.3589,
          -2.0386,   8.2029,  -0.5886],
        [ -0.8499,  -0.0492,  -1.4727,   0.8801,   0.4934,   0.1233,  -0.3201,
           0.4802,  -1.9322,   0.1386],
        [  1.7267,   0.1000,   2.9922,  -1.7881,  -1.0026,  -0.2504,   0.6504,
          -0.9757,   3.9258,  -0.2817],
        [ -0.3662,  -0.0212,  -0.6346,   0.3793,   0.2126,   0.0531,  -0.1379,
           0.2069,  -0.8327,   0.0597],
        [ -5.4528,  -0.3157,  -9.4489,   5.6466,   3.1660,   0.7908,  -2.0537,
           3.0810, -12.3972,   0.8895],
        [  2.2834,   0.1322,   3.9567,  -2.3645,  -1.3257,  -0.3312,   0.8600,
          -1.2902,   5.1913,  -0.3725],
        [  1.0210,   0.0591,   1.7693,  -1.0573,  -0.5928,  -0.1481,   0.3846,
          -0.5769,   2.3214,  -0.1666],
        [ -0.7677,  -0.0444,  -1.3303,   0.7950,

In [128]:

torch.div(x, y)

tensor([[  0.7381,   0.0427,   1.2791,  -0.7644,  -0.4286,  -0.1071,   0.2780,
          -0.4171,   1.6782,  -0.1204],
        [  3.6080,   0.2089,   6.2521,  -3.7362,  -2.0948,  -0.5233,   1.3589,
          -2.0386,   8.2029,  -0.5886],
        [ -0.8499,  -0.0492,  -1.4727,   0.8801,   0.4934,   0.1233,  -0.3201,
           0.4802,  -1.9322,   0.1386],
        [  1.7267,   0.1000,   2.9922,  -1.7881,  -1.0026,  -0.2504,   0.6504,
          -0.9757,   3.9258,  -0.2817],
        [ -0.3662,  -0.0212,  -0.6346,   0.3793,   0.2126,   0.0531,  -0.1379,
           0.2069,  -0.8327,   0.0597],
        [ -5.4528,  -0.3157,  -9.4489,   5.6466,   3.1660,   0.7908,  -2.0537,
           3.0810, -12.3972,   0.8895],
        [  2.2834,   0.1322,   3.9567,  -2.3645,  -1.3257,  -0.3312,   0.8600,
          -1.2902,   5.1913,  -0.3725],
        [  1.0210,   0.0591,   1.7693,  -1.0573,  -0.5928,  -0.1481,   0.3846,
          -0.5769,   2.3214,  -0.1666],
        [ -0.7677,  -0.0444,  -1.3303,   0.7950,

In [129]:
torch.div(x, y, rounding_mode="trunc")

tensor([[  0.,   0.,   1.,  -0.,  -0.,  -0.,   0.,  -0.,   1.,  -0.],
        [  3.,   0.,   6.,  -3.,  -2.,  -0.,   1.,  -2.,   8.,  -0.],
        [ -0.,  -0.,  -1.,   0.,   0.,   0.,  -0.,   0.,  -1.,   0.],
        [  1.,   0.,   2.,  -1.,  -1.,  -0.,   0.,  -0.,   3.,  -0.],
        [ -0.,  -0.,  -0.,   0.,   0.,   0.,  -0.,   0.,  -0.,   0.],
        [ -5.,  -0.,  -9.,   5.,   3.,   0.,  -2.,   3., -12.,   0.],
        [  2.,   0.,   3.,  -2.,  -1.,  -0.,   0.,  -1.,   5.,  -0.],
        [  1.,   0.,   1.,  -1.,  -0.,  -0.,   0.,  -0.,   2.,  -0.],
        [ -0.,  -0.,  -1.,   0.,   0.,   0.,  -0.,   0.,  -1.,   0.],
        [  1.,   0.,   1.,  -1.,  -0.,  -0.,   0.,  -0.,   2.,  -0.]])

In [130]:
torch.div(x, y, rounding_mode="floor")


tensor([[  0.,   0.,   1.,  -1.,  -1.,  -1.,   0.,  -1.,   1.,  -1.],
        [  3.,   0.,   6.,  -4.,  -3.,  -1.,   1.,  -3.,   8.,  -1.],
        [ -1.,  -1.,  -2.,   0.,   0.,   0.,  -1.,   0.,  -2.,   0.],
        [  1.,   0.,   2.,  -2.,  -2.,  -1.,   0.,  -1.,   3.,  -1.],
        [ -1.,  -1.,  -1.,   0.,   0.,   0.,  -1.,   0.,  -1.,   0.],
        [ -6.,  -1., -10.,   5.,   3.,   0.,  -3.,   3., -13.,   0.],
        [  2.,   0.,   3.,  -3.,  -2.,  -1.,   0.,  -2.,   5.,  -1.],
        [  1.,   0.,   1.,  -2.,  -1.,  -1.,   0.,  -1.,   2.,  -1.],
        [ -1.,  -1.,  -2.,   0.,   0.,   0.,  -1.,   0.,  -2.,   0.],
        [  1.,   0.,   1.,  -2.,  -1.,  -1.,   0.,  -1.,   2.,  -1.]])

In [131]:
x.shape, y.shape, (x / y).shape, (x*y).shape

(torch.Size([10]),
 torch.Size([10, 1]),
 torch.Size([10, 10]),
 torch.Size([10, 10]))

In [132]:
c = torch.logspace(1, 2, 10,
                   base=torch.exp(torch.tensor(1.0)).item())
c

tensor([2.7183, 3.0377, 3.3947, 3.7937, 4.2395, 4.7377, 5.2945, 5.9167, 6.6120,
        7.3891])

In [133]:
c, torch.exp(c)

(tensor([2.7183, 3.0377, 3.3947, 3.7937, 4.2395, 4.7377, 5.2945, 5.9167, 6.6120,
         7.3891]),
 tensor([  15.1543,   20.8579,   29.8064,   44.4190,   69.3729,  114.1733,
          199.2360,  371.1823,  743.9826, 1618.1774]))

In [134]:
torch.special.exp2(c)

tensor([  6.5809,   8.2120,  10.5175,  13.8678,  18.8893,  26.6806,  39.2464,
         60.4091,  97.8173, 167.6206])

In [135]:
torch.special.expm1(c)

tensor([  14.1543,   19.8579,   28.8064,   43.4190,   68.3729,  113.1733,
         198.2360,  370.1823,  742.9826, 1617.1774])

In [136]:
# torch.special.logsumexp(c) # LSE

In [137]:
torch.log1p(c),  torch.log( 1 + c)


(tensor([1.3133, 1.3957, 1.4804, 1.5673, 1.6562, 1.7471, 1.8397, 1.9339, 2.0297,
         2.1269]),
 tensor([1.3133, 1.3957, 1.4804, 1.5673, 1.6562, 1.7471, 1.8397, 1.9339, 2.0297,
         2.1269]))

In [138]:
x, torch.trunc(x), torch.floor(x)


(tensor([-1.0068, -0.0583, -1.7446,  1.0425,  0.5845,  0.1460, -0.3792,  0.5689,
         -2.2889,  0.1642]),
 tensor([-1., -0., -1.,  1.,  0.,  0., -0.,  0., -2.,  0.]),
 tensor([-2., -1., -2.,  1.,  0.,  0., -1.,  0., -3.,  0.]))

In [139]:
a = torch.randint(10, (4, ))
a

tensor([5, 5, 8, 2])

In [140]:
torch.float_power(a, 2) , a**2, torch.pow(a, 2)

(tensor([25., 25., 64.,  4.], dtype=torch.float64),
 tensor([25, 25, 64,  4]),
 tensor([25, 25, 64,  4]))

In [141]:
z = torch.normal(mean=torch.ones((10, )) * -5.0,
                 std= torch.linspace(1, 10, 10))

z, torch.frac(z)

(tensor([ -7.2709,  -2.6744,  -4.5113,  -6.7455,  -7.9241,   4.2573,  -8.3328,
          -8.2041,   1.0384, -20.4137]),
 tensor([-0.2709, -0.6744, -0.5113, -0.7455, -0.9241,  0.2573, -0.3328, -0.2041,
          0.0384, -0.4137]))

In [142]:
x = torch.arange(1, 10, 2)
z = torch.arange(0, 10, 2)
x, z


(tensor([1, 3, 5, 7, 9]), tensor([0, 2, 4, 6, 8]))

In [143]:
y = 2 * z

In [144]:
torch.gradient(y, spacing=(z, ))

(tensor([2., 2., 2., 2., 2.]),)

In [145]:
mat = torch.randint(0, 10, size=(10, 5))


In [146]:
mat

tensor([[1, 3, 6, 1, 7],
        [0, 5, 3, 5, 3],
        [7, 5, 4, 2, 3],
        [7, 3, 9, 1, 3],
        [7, 0, 9, 9, 1],
        [8, 8, 1, 9, 1],
        [5, 5, 4, 5, 6],
        [8, 3, 7, 3, 6],
        [3, 8, 2, 7, 2],
        [1, 1, 0, 6, 8]])

In [147]:
w = torch.matmul(mat, z)
w

tensor([ 92,  76,  62,  72,  98,  82, 104, 100,  82, 102])

In [148]:
x=torch.randn(4, dtype=torch.cfloat)
x

tensor([ 0.6288+0.0533j, -0.4901+0.7358j, -1.0048+0.5569j,  0.7986+0.6270j])

In [149]:
x.imag


tensor([0.0533, 0.7358, 0.5569, 0.6270])

In [150]:
start = torch.arange(1, 5)
end = torch.empty(4).fill_(10)
start, end

(tensor([1, 2, 3, 4]), tensor([10., 10., 10., 10.]))

In [151]:
start = torch.arange(1, 5.)
end = torch.empty(4).fill_(10.)

x = torch.lerp(start, end, 0.5)
x

tensor([5.5000, 6.0000, 6.5000, 7.0000])

In [152]:
y = torch.lgamma(x)
x

tensor([5.5000, 6.0000, 6.5000, 7.0000])

In [153]:
z = torch.log(torch.tensor([1.0, 2, 3, 10]))

z

tensor([0.0000, 0.6931, 1.0986, 2.3026])

In [154]:
torch.log2(x), torch.log10(x)

(tensor([2.4594, 2.5850, 2.7004, 2.8074]),
 tensor([0.7404, 0.7782, 0.8129, 0.8451]))

In [155]:
"""log(e**x  +  e**y)"""
a = torch.tensor([np.log(1.0), np.log(2), np.log(3)])
x = torch.logaddexp(a, a)
x

tensor([0.6931, 1.3863, 1.7918], dtype=torch.float64)

In [156]:
torch.logical_and(a, a)

tensor([False,  True,  True])

In [157]:
torch.logical_or(a, a)


tensor([False,  True,  True])

In [158]:
torch.log2(torch.tensor(4))

tensor(2.)

In [159]:
torch.log10(torch.tensor(10))

tensor(1.)

In [160]:
a = torch.arange(1, 6.)
torch.log1p(a), torch.log(1 + a)

(tensor([0.6931, 1.0986, 1.3863, 1.6094, 1.7918]),
 tensor([0.6931, 1.0986, 1.3863, 1.6094, 1.7918]))

In [161]:
a = torch.rand((5, ))
"""Inverse of sigmoid = sigmoid^(-1)(x)"""
x = torch.logit(a, eps=1e-7)
a, x

(tensor([0.0290, 0.0257, 0.0531, 0.0987, 0.3532]),
 tensor([-3.5107, -3.6333, -2.8811, -2.2121, -0.6051]))

In [162]:
torch.special.logit(a)

tensor([-3.5107, -3.6333, -2.8811, -2.2121, -0.6051])

In [163]:
torch.special.logsumexp(a, 0, keepdim=True)

tensor([1.7294])

In [164]:
torch.special.log_softmax(a, 0)

tensor([-1.7004, -1.7037, -1.6763, -1.6307, -1.3762])

In [165]:
a = torch.hypot(torch.tensor([4.0]), torch.tensor([3.0, 4.0, 5.0]))
a

tensor([5.0000, 5.6569, 6.4031])

In [166]:
a = torch.randn((4, 3))
b = torch.randn((1, 3))
c = torch.mul(a, torch.div(b, b))
a, b, c

(tensor([[ 0.8733, -0.1694, -0.6686],
         [ 2.5879, -1.1164, -0.1450],
         [-0.0334,  0.8912,  0.3700],
         [-0.7426, -0.4579, -1.7458]]),
 tensor([[ 1.0611, -1.0127, -1.0582]]),
 tensor([[ 0.8733, -0.1694, -0.6686],
         [ 2.5879, -1.1164, -0.1450],
         [-0.0334,  0.8912,  0.3700],
         [-0.7426, -0.4579, -1.7458]]))

In [167]:
torch.multiply(torch.randn((4, 1)), torch.randn((1, 4)))

tensor([[-0.4693, -0.2679,  0.2850, -0.2720],
        [-0.8004, -0.4570,  0.4862, -0.4639],
        [-1.0237, -0.5844,  0.6218, -0.5933],
        [-0.2175, -0.1242,  0.1321, -0.1261]])

In [168]:
mat = torch.randn((100, 50))
weights = torch.randn((50, 10))

out = torch.einsum("ij, jk -> ik", mat, weights)
out2 = torch.matmul(mat, weights)
out3 = torch.matmul(mat, torch.reshape(weights, (1, weights.shape[0], weights.shape[-1])))
out.shape, out2.shape, out3.shape

(torch.Size([100, 10]), torch.Size([100, 10]), torch.Size([1, 100, 10]))

In [169]:
mat = torch.randn((100, 50))
weights = torch.randn((50,))

out = torch.multiply(mat, weights)
out.shape

torch.Size([100, 50])

In [170]:
out = torch.matmul(torch.randn(100), torch.randn((100, 5)))
out.size()

torch.Size([5])

In [171]:
x = torch.randn(10)
y = torch.randn(10)
print(x)
print(y)
print(x*y)
print(torch.matmul(x, y.T), y.T.shape)
print(torch.matmul(x, y))

tensor([-1.4982,  0.0207, -0.8316,  0.0661, -0.5382, -0.3427,  0.2333, -0.5733,
        -0.3469, -0.1285])
tensor([ 0.1167,  0.0220,  0.0563,  0.6478,  0.2594,  0.1649,  0.0123, -0.4254,
         0.9684, -0.4800])
tensor([-0.1748,  0.0005, -0.0469,  0.0428, -0.1396, -0.0565,  0.0029,  0.2439,
        -0.3359,  0.0617])
tensor(-0.4020) torch.Size([10])
tensor(-0.4020)


In [172]:
x = torch.randn((4, 3))
y = torch.randn((4, 3))
print(x)
print(y)
print(x*y)
print(torch.matmul(x, y.T))

tensor([[-0.3747, -1.5817, -1.3022],
        [-0.7510, -0.3534,  0.4367],
        [ 0.6360, -0.5406, -0.0478],
        [ 1.2996, -0.3324, -0.3114]])
tensor([[-0.1443,  0.2048,  1.3460],
        [ 0.3340, -1.2798,  1.8885],
        [-0.9498,  0.1028,  0.5047],
        [ 1.3814,  0.8677, -0.2459]])
tensor([[ 0.0541, -0.3239, -1.7528],
        [-0.2508,  0.4523,  0.8246],
        [-0.6040, -0.0556, -0.0241],
        [ 1.7952, -0.2884,  0.0766]])
tensor([[-2.0226, -0.5601, -0.4640, -1.5699],
        [ 0.6238,  1.0261,  0.8974, -1.4514],
        [-0.2668,  0.8140, -0.6837,  0.4212],
        [-0.6747,  0.2714, -1.4257,  1.5833]])


In [173]:
x = torch.randn(10)
y = torch.randn((10, 2))
z = torch.matmul(x, y)
print(z.shape)

torch.Size([2])


In [174]:
j, k, n = 3, 4, 2

x = torch.randn((j, 1, n, n))
y = torch.randn((k, n, n))
z = torch.matmul(x, y)
z.shape

torch.Size([3, 4, 2, 2])

In [175]:
x = torch.randn(10, 3, 4)
y = torch.randn(4, 5)

z = torch.matmul(x, y).size()
z

torch.Size([10, 3, 5])

In [176]:
torch.neg(torch.arange(1, 10.)), -torch.arange(1, 10.0)



(tensor([-1., -2., -3., -4., -5., -6., -7., -8., -9.]),
 tensor([-1., -2., -3., -4., -5., -6., -7., -8., -9.]))

In [177]:
x = torch.arange(1.0, 10.0)
y = torch.arange(1, 10)
torch.pow(x, 2), torch.pow(x, 1.4), x**1.4, torch.pow(x, y), x**y

(tensor([ 1.,  4.,  9., 16., 25., 36., 49., 64., 81.]),
 tensor([ 1.0000,  2.6390,  4.6555,  6.9644,  9.5183, 12.2860, 15.2453, 18.3792,
         21.6740]),
 tensor([ 1.0000,  2.6390,  4.6555,  6.9644,  9.5183, 12.2860, 15.2453, 18.3792,
         21.6740]),
 tensor([1.0000e+00, 4.0000e+00, 2.7000e+01, 2.5600e+02, 3.1250e+03, 4.6656e+04,
         8.2354e+05, 1.6777e+07, 3.8742e+08]),
 tensor([1.0000e+00, 4.0000e+00, 2.7000e+01, 2.5600e+02, 3.1250e+03, 4.6656e+04,
         8.2354e+05, 1.6777e+07, 3.8742e+08]))

In [178]:
qx = torch.quantize_per_tensor(torch.rand(2, 2, 2, 2), 1.5, 3, torch.quint8)
qx

tensor([[[[1.5000, 0.0000],
          [1.5000, 1.5000]],

         [[0.0000, 0.0000],
          [0.0000, 0.0000]]],


        [[[0.0000, 0.0000],
          [0.0000, 0.0000]],

         [[0.0000, 1.5000],
          [1.5000, 0.0000]]]], size=(2, 2, 2, 2), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=1.5, zero_point=3)

In [179]:
qx = torch.quantize_per_tensor(torch.rand(2, 2, 2, 2), 1.5, 3, torch.quint8)
qx

tensor([[[[0.0000, 0.0000],
          [1.5000, 1.5000]],

         [[1.5000, 0.0000],
          [0.0000, 0.0000]]],


        [[[0.0000, 0.0000],
          [0.0000, 0.0000]],

         [[0.0000, 0.0000],
          [0.0000, 0.0000]]]], size=(2, 2, 2, 2), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=1.5, zero_point=3)

In [180]:
a = torch.tensor([[3.142, -3.142], [6.283, -6.283], [1.570, -1.570]])
torch.rad2deg(a)

tensor([[ 180.0233, -180.0233],
        [ 359.9894, -359.9894],
        [  89.9544,  -89.9544]])

In [181]:
x = torch.randn(4, dtype=torch.cfloat)
x, x.real, x.imag

(tensor([-1.0311+0.2964j,  0.9546-0.8135j, -0.3357-0.1241j,  1.0272+1.3002j]),
 tensor([-1.0311,  0.9546, -0.3357,  1.0272]),
 tensor([ 0.2964, -0.8135, -0.1241,  1.3002]))

In [182]:
x = torch.randn(4)
torch.reciprocal(x), 1.0 / x

(tensor([-1.0994,  1.4736, -1.7582, -7.9448]),
 tensor([-1.0994,  1.4736, -1.7582, -7.9448]))

In [183]:
x = torch.tensor([-3, -2, -1, 1, 2, 3])
x

tensor([-3, -2, -1,  1,  2,  3])

In [184]:
x, x % 3, torch.remainder(x, 3), torch.div(x, 3)

(tensor([-3, -2, -1,  1,  2,  3]),
 tensor([0, 1, 2, 1, 2, 0]),
 tensor([0, 1, 2, 1, 2, 0]),
 tensor([-1.0000, -0.6667, -0.3333,  0.3333,  0.6667,  1.0000]))

In [185]:
div = -3
x, x % div, torch.remainder(x, div), torch.div(x, div)

(tensor([-3, -2, -1,  1,  2,  3]),
 tensor([ 0, -2, -1, -2, -1,  0]),
 tensor([ 0, -2, -1, -2, -1,  0]),
 tensor([ 1.0000,  0.6667,  0.3333, -0.3333, -0.6667, -1.0000]))

In [186]:
x = 1. + torch.randn(20) * 2
x, torch.trunc(x), torch.ceil(x), torch.round(x), torch.floor(x)

(tensor([ 2.0776,  0.7586,  2.6102, -1.0443,  0.3573, -2.7570,  1.3784,  5.2163,
          1.0419, -0.3403,  1.7830,  0.4019,  3.9618,  2.0822,  3.0938,  3.2167,
         -1.3552,  1.2674,  1.6332,  2.2491]),
 tensor([ 2.,  0.,  2., -1.,  0., -2.,  1.,  5.,  1., -0.,  1.,  0.,  3.,  2.,
          3.,  3., -1.,  1.,  1.,  2.]),
 tensor([ 3.,  1.,  3., -1.,  1., -2.,  2.,  6.,  2., -0.,  2.,  1.,  4.,  3.,
          4.,  4., -1.,  2.,  2.,  3.]),
 tensor([ 2.,  1.,  3., -1.,  0., -3.,  1.,  5.,  1., -0.,  2.,  0.,  4.,  2.,
          3.,  3., -1.,  1.,  2.,  2.]),
 tensor([ 2.,  0.,  2., -2.,  0., -3.,  1.,  5.,  1., -1.,  1.,  0.,  3.,  2.,
          3.,  3., -2.,  1.,  1.,  2.]))

In [187]:
torch.sqrt(x), x ** 0.5

(tensor([1.4414, 0.8710, 1.6156,    nan, 0.5978,    nan, 1.1740, 2.2839, 1.0207,
            nan, 1.3353, 0.6339, 1.9904, 1.4430, 1.7589, 1.7935,    nan, 1.1258,
         1.2780, 1.4997]),
 tensor([1.4414, 0.8710, 1.6156,    nan, 0.5978,    nan, 1.1740, 2.2839, 1.0207,
            nan, 1.3353, 0.6339, 1.9904, 1.4430, 1.7589, 1.7935,    nan, 1.1258,
         1.2780, 1.4997]))

In [188]:
torch.isnan(torch.sqrt(x))

tensor([False, False, False,  True, False,  True, False, False, False,  True,
        False, False, False, False, False, False,  True, False, False, False])

In [189]:
torch.rsqrt(x), x **-0.5

(tensor([0.6938, 1.1481, 0.6190,    nan, 1.6729,    nan, 0.8518, 0.4378, 0.9797,
            nan, 0.7489, 1.5774, 0.5024, 0.6930, 0.5685, 0.5576,    nan, 0.8883,
         0.7825, 0.6668]),
 tensor([0.6938, 1.1481, 0.6190,    nan, 1.6729,    nan, 0.8518, 0.4378, 0.9797,
            nan, 0.7489, 1.5774, 0.5024, 0.6930, 0.5685, 0.5576,    nan, 0.8883,
         0.7825, 0.6668]))

In [190]:
x, torch.sign(x)

(tensor([ 2.0776,  0.7586,  2.6102, -1.0443,  0.3573, -2.7570,  1.3784,  5.2163,
          1.0419, -0.3403,  1.7830,  0.4019,  3.9618,  2.0822,  3.0938,  3.2167,
         -1.3552,  1.2674,  1.6332,  2.2491]),
 tensor([ 1.,  1.,  1., -1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,
          1.,  1., -1.,  1.,  1.,  1.]))

In [191]:
t = torch.tensor([3+4j, 7-24j, 0, 1+2j])
torch.sgn(t)

tensor([0.6000+0.8000j, 0.2800-0.9600j, 0.0000+0.0000j, 0.4472+0.8944j])

In [192]:
torch.signbit(x)

tensor([False, False, False,  True, False,  True, False, False, False,  True,
        False, False, False, False, False, False,  True, False, False, False])

In [193]:
torch.square(x), x ** 2

(tensor([ 4.3166,  0.5755,  6.8133,  1.0905,  0.1277,  7.6009,  1.8999, 27.2102,
          1.0855,  0.1158,  3.1789,  0.1615, 15.6960,  4.3354,  9.5715, 10.3472,
          1.8365,  1.6063,  2.6673,  5.0584]),
 tensor([ 4.3166,  0.5755,  6.8133,  1.0905,  0.1277,  7.6009,  1.8999, 27.2102,
          1.0855,  0.1158,  3.1789,  0.1615, 15.6960,  4.3354,  9.5715, 10.3472,
          1.8365,  1.6063,  2.6673,  5.0584]))

In [194]:
torch.sub(x, x)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [195]:
z = torch.randn_like(x)
torch.divide(x, z * x), torch.div(x, z*x), torch.div(x, z*x), torch.true_divide(x, z*x)

(tensor([-2.1449, -1.5406,  0.9217, -1.8385, -1.0841, -1.0028,  1.8336,  1.0232,
         -2.0306,  2.8827, -1.4774,  0.6438, -2.1109, -2.8992, -1.8653, -2.0659,
         -8.8199, -0.6881,  3.0503,  2.4412]),
 tensor([-2.1449, -1.5406,  0.9217, -1.8385, -1.0841, -1.0028,  1.8336,  1.0232,
         -2.0306,  2.8827, -1.4774,  0.6438, -2.1109, -2.8992, -1.8653, -2.0659,
         -8.8199, -0.6881,  3.0503,  2.4412]),
 tensor([-2.1449, -1.5406,  0.9217, -1.8385, -1.0841, -1.0028,  1.8336,  1.0232,
         -2.0306,  2.8827, -1.4774,  0.6438, -2.1109, -2.8992, -1.8653, -2.0659,
         -8.8199, -0.6881,  3.0503,  2.4412]),
 tensor([-2.1449, -1.5406,  0.9217, -1.8385, -1.0841, -1.0028,  1.8336,  1.0232,
         -2.0306,  2.8827, -1.4774,  0.6438, -2.1109, -2.8992, -1.8653, -2.0659,
         -8.8199, -0.6881,  3.0503,  2.4412]))

In [196]:
y = torch.special.xlogy(x, torch.exp(z))
y, x*z, y - x*z

(tensor([-0.9686, -0.4924,  2.8320,  0.5680, -0.3296,  2.7493,  0.7517,  5.0983,
         -0.5131, -0.1181, -1.2068,  0.6242, -1.8768, -0.7182, -1.6586, -1.5570,
          0.1537, -1.8418,  0.5354,  0.9213]),
 tensor([-0.9686, -0.4924,  2.8320,  0.5680, -0.3296,  2.7493,  0.7517,  5.0983,
         -0.5131, -0.1181, -1.2068,  0.6242, -1.8768, -0.7182, -1.6586, -1.5570,
          0.1537, -1.8418,  0.5354,  0.9213]),
 tensor([ 5.9605e-08,  0.0000e+00,  0.0000e+00, -5.9605e-08, -2.9802e-08,
          0.0000e+00,  0.0000e+00,  0.0000e+00, -5.9605e-08, -1.4901e-08,
         -1.1921e-07,  0.0000e+00,  2.3842e-07,  0.0000e+00,  0.0000e+00,
          1.1921e-07,  1.4901e-08,  0.0000e+00,  5.9605e-08,  5.9605e-08]))

In [197]:
torch.isnan(x)

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False])

In [198]:
x

tensor([ 2.0776,  0.7586,  2.6102, -1.0443,  0.3573, -2.7570,  1.3784,  5.2163,
         1.0419, -0.3403,  1.7830,  0.4019,  3.9618,  2.0822,  3.0938,  3.2167,
        -1.3552,  1.2674,  1.6332,  2.2491])

In [212]:
torch.manual_seed(4)
x = torch.randint(0, 100, size=(4, 10))
x, torch.max(x), torch.max(x, dim=0), torch.max(x, dim=1)

(tensor([[30, 94, 31, 73, 89, 76, 19, 76, 82, 61],
         [38, 96, 55, 13, 50, 87, 67, 33,  0, 12],
         [78, 80, 18, 14, 22, 64, 31, 12, 79, 97],
         [49, 33, 82, 17, 14, 84, 86,  2,  5, 14]]),
 tensor(97),
 torch.return_types.max(
 values=tensor([78, 96, 82, 73, 89, 87, 86, 76, 82, 97]),
 indices=tensor([2, 1, 3, 0, 0, 1, 3, 0, 0, 2])),
 torch.return_types.max(
 values=tensor([94, 96, 97, 86]),
 indices=tensor([1, 1, 9, 6])))

In [214]:
torch.max(x, dim=1, keepdim=True)


torch.return_types.max(
values=tensor([[94],
        [96],
        [97],
        [86]]),
indices=tensor([[1],
        [1],
        [9],
        [6]]))

In [215]:
torch.max(x, dim=0, keepdim=True)

torch.return_types.max(
values=tensor([[78, 96, 82, 73, 89, 87, 86, 76, 82, 97]]),
indices=tensor([[2, 1, 3, 0, 0, 1, 3, 0, 0, 2]]))

In [222]:
y = torch.randint(0, 100, size=(4, 5))
z = torch.randint(0, 100, size=(4, 5))


y, z, torch.max(y, z)

(tensor([[46, 81, 29, 76,  1],
         [57, 57, 43, 53, 28],
         [ 2, 19, 49, 68, 73],
         [88, 89, 93, 38, 99]]),
 tensor([[74,  0, 72, 53, 11],
         [ 1, 13,  4, 87, 14],
         [55, 48,  4, 30, 28],
         [95, 52, 85, 48, 86]]),
 tensor([[74, 81, 72, 76, 11],
         [57, 57, 43, 87, 28],
         [55, 48, 49, 68, 73],
         [95, 89, 93, 48, 99]]))

In [224]:
torch.max(y, dim=0).values


tensor([88, 89, 93, 76, 99])

In [225]:
torch.max(y, dim=0).indices

tensor([3, 3, 3, 0, 3])

In [229]:
torch.argmax(y, dim=0)

tensor([3, 3, 3, 0, 3])

In [231]:
torch.maximum(y, z)

tensor([[74, 81, 72, 76, 11],
        [57, 57, 43, 87, 28],
        [55, 48, 49, 68, 73],
        [95, 89, 93, 48, 99]])

In [250]:
np.random.seed(0)
x = torch.from_numpy(np.random.uniform(-3, 3, size=(3, 4, 2)))
x

tensor([[[ 0.2929,  1.2911],
         [ 0.6166,  0.2693],
         [-0.4581,  0.8754],
         [-0.3745,  2.3506]],

        [[ 2.7820, -0.6994],
         [ 1.7504,  0.1734],
         [ 0.4083,  2.5536],
         [-2.5738, -2.4772]],

        [[-2.8787,  1.9957],
         [ 1.6689,  2.2201],
         [ 2.8717,  1.7950],
         [-0.2311,  1.6832]]], dtype=torch.float64)

In [251]:
torch.amax(x)

tensor(2.8717, dtype=torch.float64)

In [252]:
torch.amax(x, dim=1)

tensor([[0.6166, 2.3506],
        [2.7820, 2.5536],
        [2.8717, 2.2201]], dtype=torch.float64)

In [254]:
torch.amax(x, dim=0, keepdim=True)

tensor([[[ 2.7820,  1.9957],
         [ 1.7504,  2.2201],
         [ 2.8717,  2.5536],
         [-0.2311,  2.3506]]], dtype=torch.float64)

In [255]:
torch.argmax(x, dim=0, keepdim=True)

tensor([[[1, 2],
         [1, 2],
         [2, 1],
         [2, 0]]])

In [258]:
torch.amax(x, dim=(0, 1))

tensor([2.8717, 2.5536], dtype=torch.float64)

In [261]:
torch.amax(x, dim=(1, 0))


tensor([2.8717, 2.5536], dtype=torch.float64)

In [262]:
torch.amax(x, dim=(1, ))

tensor([[0.6166, 2.3506],
        [2.7820, 2.5536],
        [2.8717, 2.2201]], dtype=torch.float64)

In [263]:
torch.amax(x, dim=(1, 0), keepdim=True)

tensor([[[2.8717, 2.5536]]], dtype=torch.float64)

In [266]:
torch.argmin(x), torch.min(x)

(tensor(16), tensor(-2.8787, dtype=torch.float64))

In [267]:
torch.amin(x, dim=(0, 1))

tensor([-2.8787, -2.4772], dtype=torch.float64)

In [268]:
torch.min(x, dim=1)

torch.return_types.min(
values=tensor([[-0.4581,  0.2693],
        [-2.5738, -2.4772],
        [-2.8787,  1.6832]], dtype=torch.float64),
indices=tensor([[2, 1],
        [3, 3],
        [0, 3]]))

In [269]:
x

tensor([[[ 0.2929,  1.2911],
         [ 0.6166,  0.2693],
         [-0.4581,  0.8754],
         [-0.3745,  2.3506]],

        [[ 2.7820, -0.6994],
         [ 1.7504,  0.1734],
         [ 0.4083,  2.5536],
         [-2.5738, -2.4772]],

        [[-2.8787,  1.9957],
         [ 1.6689,  2.2201],
         [ 2.8717,  1.7950],
         [-0.2311,  1.6832]]], dtype=torch.float64)

In [270]:
torch.aminmax(x,)

torch.return_types.aminmax(
min=tensor(-2.8787, dtype=torch.float64),
max=tensor(2.8717, dtype=torch.float64))

In [272]:
torch.aminmax(x, dim=1)

torch.return_types.aminmax(
min=tensor([[-0.4581,  0.2693],
        [-2.5738, -2.4772],
        [-2.8787,  1.6832]], dtype=torch.float64),
max=tensor([[0.6166, 2.3506],
        [2.7820, 2.5536],
        [2.8717, 2.2201]], dtype=torch.float64))

In [291]:
p = torch.empty(3, 5).uniform_(0.7, 1)
x = torch.bernoulli(p).type(torch.bool)
x, torch.all(x, dim=1), torch.any(x, dim=1)

(tensor([[ True,  True,  True,  True,  True],
         [ True,  True,  True, False, False],
         [ True,  True,  True,  True, False]]),
 tensor([ True, False, False]),
 tensor([True, True, True]))

In [301]:
x = torch.tensor([1., 2.])
y = torch.tensor([3, 4.])
x, y, torch.dist(y, x, 2), torch.sum(torch.sqrt(y-x))

(tensor([1., 2.]), tensor([3., 4.]), tensor(2.8284), tensor(2.8284))

In [305]:
y = torch.randn(3, 3)
torch.logsumexp(y, 1)

tensor([0.6128, 1.3178, 1.0855])

In [311]:
x = torch.arange(0, 10).to(dtype=torch.float32).reshape((2, 5))
x, torch.mean(x), torch.median(x), torch.mean(x, dim=1), torch.median(x, dim=1)

(tensor([[0., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]),
 tensor(4.5000),
 tensor(4.),
 tensor([2., 7.]),
 torch.return_types.median(
 values=tensor([2., 7.]),
 indices=tensor([2, 2])))

In [328]:
a = torch.randint(10, (5,))
b = a + (torch.randn(4, 1) * 5).long()
a, b, torch.mode(b, dim=0),torch.mode(b, dim=1)

(tensor([4, 4, 2, 5, 7]),
 tensor([[ 8,  8,  6,  9, 11],
         [-1, -1, -3,  0,  2],
         [ 4,  4,  2,  5,  7],
         [11, 11,  9, 12, 14]]),
 torch.return_types.mode(
 values=tensor([-1, -1, -3,  0,  2]),
 indices=tensor([1, 1, 1, 1, 1])),
 torch.return_types.mode(
 values=tensor([ 8, -1,  4, 11]),
 indices=tensor([1, 1, 1, 1])))

In [331]:
torch.norm(b.to(dtype=torch.float32))

tensor(33.9706)

In [333]:
torch.nansum(torch.tensor([1., float("nan")])), torch.sum(torch.tensor([1., float("nan")]))

(tensor(1.), tensor(nan))

In [338]:
a = torch.tensor([[1, 2], [3, 4]])
a, torch.prod(a), torch.prod(a, dim=1)

(tensor([[1, 2],
         [3, 4]]),
 tensor(24),
 tensor([ 2, 12]))

In [345]:
torch.manual_seed(0)
x = torch.randn((4, 5))
x, 

(tensor([[-1.1258, -1.1524, -0.2506, -0.4339,  0.5988],
         [-1.5551, -0.3414,  1.8530,  0.4681, -0.1577],
         [ 1.4437,  0.2660,  1.3894,  1.5863,  0.9463],
         [-0.8437,  0.9318,  1.2590,  2.0050,  0.0537]]),)

In [346]:
torch.quantile(x, torch.tensor([0.5]))

tensor([0.3671])

In [347]:
torch.quantile(x, torch.tensor([0.5, 0.25]))

tensor([ 0.3671, -0.3645])

In [353]:
torch.quantile(x, torch.tensor([0.5]), dim=1)

tensor([[-0.4339, -0.1577,  1.3894,  0.9318]])

In [354]:
torch.quantile(x, torch.tensor([0.5]), interpolation="linear", dim=1)


tensor([[-0.4339, -0.1577,  1.3894,  0.9318]])

In [355]:
torch.quantile(x, torch.tensor([0.5]), interpolation="lower", dim=1)


tensor([[-0.4339, -0.1577,  1.3894,  0.9318]])

In [356]:
torch.quantile(x, torch.tensor([0.5]), interpolation="higher", dim=1)


tensor([[-0.4339, -0.1577,  1.3894,  0.9318]])

In [358]:
torch.quantile(x, torch.tensor([0.5]), interpolation="nearest", dim=1)


tensor([[-0.4339, -0.1577,  1.3894,  0.9318]])

In [359]:
torch.quantile(x, torch.tensor([0.5]), interpolation="midpoint", dim=1)


tensor([[-0.4339, -0.1577,  1.3894,  0.9318]])

In [361]:
x = torch.randn((2, 5))
x, torch.sum(x, dim=1)


(tensor([[-0.0209, -0.7185,  0.5186, -1.3125,  0.1920],
         [ 0.5428, -2.2188,  0.2590, -1.0297, -0.5008]]),
 tensor([-1.3412, -2.9475]))

In [368]:
x = torch.randint(0, 10, (4, 10))
x, torch.unique(x, dim=0), torch.unique(x, dim=1, sorted=False)

(tensor([[7, 4, 7, 6, 9, 3, 8, 4, 4, 9],
         [4, 4, 9, 9, 5, 7, 0, 3, 2, 0],
         [8, 6, 1, 9, 1, 6, 9, 8, 6, 5],
         [1, 3, 5, 5, 3, 6, 2, 7, 5, 7]]),
 tensor([[1, 3, 5, 5, 3, 6, 2, 7, 5, 7],
         [4, 4, 9, 9, 5, 7, 0, 3, 2, 0],
         [7, 4, 7, 6, 9, 3, 8, 4, 4, 9],
         [8, 6, 1, 9, 1, 6, 9, 8, 6, 5]]),
 tensor([[3, 4, 4, 4, 6, 7, 7, 8, 9, 9],
         [7, 2, 3, 4, 9, 4, 9, 0, 0, 5],
         [6, 6, 8, 6, 9, 8, 1, 9, 5, 1],
         [6, 5, 7, 3, 5, 1, 5, 2, 7, 3]]))

In [371]:
torch.var_mean(x.to(torch.float32), dim=1)

(tensor([ 4.9889, 10.6778,  8.5444,  4.2667]),
 tensor([6.1000, 4.3000, 5.9000, 4.4000]))