In [1]:
%load_ext autoreload
%autoreload 2
import random
import tensorflow as tf
import tensorflow.experimental.numpy as tnp
import numpy as np


2024-01-03 10:50:15.766174: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
gpus = tf.config.list_physical_devices("GPU")

2024-01-03 10:50:18.007556: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-03 10:50:18.029049: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-03 10:50:18.029261: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [3]:
len(gpus)

1

In [4]:
gpus

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

In [6]:
np.random.seed(0)
tf.random.set_seed(0)
x = np.random.randn(5, 10).astype("float")
x

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
        -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
         0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  2.26975462,
        -1.45436567,  0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647, -0.34791215,
         0.15634897,  1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218,
        -0.4380743 , -1.25279536,  0.77749036, -1.61389785, -0.21274028]])

In [7]:
y = tf.convert_to_tensor(x, dtype=tf.float32)
y

2024-01-03 10:50:18.236078: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-03 10:50:18.236299: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-03 10:50:18.236435: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[ 1.7640524 ,  0.4001572 ,  0.978738  ,  2.2408931 ,  1.867558  ,
        -0.9772779 ,  0.95008844, -0.1513572 , -0.10321885,  0.41059852],
       [ 0.14404356,  1.4542735 ,  0.7610377 ,  0.12167501,  0.44386324,
         0.33367434,  1.4940791 , -0.20515826,  0.3130677 , -0.85409576],
       [-2.5529897 ,  0.6536186 ,  0.8644362 , -0.742165  ,  2.2697546 ,
        -1.4543657 ,  0.04575852, -0.18718386,  1.5327792 ,  1.4693588 ],
       [ 0.15494743,  0.37816253, -0.88778573, -1.9807965 , -0.34791216,
         0.15634897,  1.2302907 ,  1.2023798 , -0.3873268 , -0.30230275],
       [-1.048553  , -1.420018  , -1.7062702 ,  1.9507754 , -0.5096522 ,
        -0.4380743 , -1.2527953 ,  0.7774904 , -1.6138978 , -0.21274029]],
      dtype=float32)>

In [8]:
y.numpy()

array([[ 1.7640524 ,  0.4001572 ,  0.978738  ,  2.2408931 ,  1.867558  ,
        -0.9772779 ,  0.95008844, -0.1513572 , -0.10321885,  0.41059852],
       [ 0.14404356,  1.4542735 ,  0.7610377 ,  0.12167501,  0.44386324,
         0.33367434,  1.4940791 , -0.20515826,  0.3130677 , -0.85409576],
       [-2.5529897 ,  0.6536186 ,  0.8644362 , -0.742165  ,  2.2697546 ,
        -1.4543657 ,  0.04575852, -0.18718386,  1.5327792 ,  1.4693588 ],
       [ 0.15494743,  0.37816253, -0.88778573, -1.9807965 , -0.34791216,
         0.15634897,  1.2302907 ,  1.2023798 , -0.3873268 , -0.30230275],
       [-1.048553  , -1.420018  , -1.7062702 ,  1.9507754 , -0.5096522 ,
        -0.4380743 , -1.2527953 ,  0.7774904 , -1.6138978 , -0.21274029]],
      dtype=float32)

In [9]:
x = tf.range(4*3)
x = tf.reshape(x, (4, 3))
x

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int32)>

In [10]:
np.random.seed(0)
x = tf.constant(np.random.randint(0, 10, (4, 3)).reshape((4, 3)), dtype=tf.int32)
x

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]], dtype=int32)>

In [11]:
x, tf.reshape(x, (2, 2, 3))

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[5, 0, 3],
         [3, 7, 9]],
 
        [[3, 5, 2],
         [4, 7, 6]]], dtype=int32)>)

In [12]:
x, tf.reshape(x, (2, -1, 3))

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[5, 0, 3],
         [3, 7, 9]],
 
        [[3, 5, 2],
         [4, 7, 6]]], dtype=int32)>)

In [13]:
2*x, tf.add(x, x)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[10,  0,  6],
        [ 6, 14, 18],
        [ 6, 10,  4],
        [ 8, 14, 12]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[10,  0,  6],
        [ 6, 14, 18],
        [ 6, 10,  4],
        [ 8, 14, 12]], dtype=int32)>)

In [14]:
x-x, tf.subtract(x, x)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=int32)>)

In [15]:
x, tf.transpose(x, (1, 0))

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[5, 3, 3, 4],
        [0, 7, 5, 7],
        [3, 9, 2, 6]], dtype=int32)>)

In [16]:
x * x, tf.multiply(x, x)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[25,  0,  9],
        [ 9, 49, 81],
        [ 9, 25,  4],
        [16, 49, 36]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[25,  0,  9],
        [ 9, 49, 81],
        [ 9, 25,  4],
        [16, 49, 36]], dtype=int32)>)

In [17]:
x, tf.argmax(x) # default axis=0

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 1, 1])>)

In [18]:
x, tf.argmax(x, 0)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 1, 1])>)

In [19]:
x, tf.argmax(x, 1)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 2, 1, 1])>)

In [20]:
x, tf.argmin(x)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 0, 2])>)

In [21]:
x, tf.argmin(x, 0)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 0, 2])>)

In [22]:
x, tf.argmin(x, 1, output_type=x.dtype)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 0, 2, 0], dtype=int32)>)

In [23]:
x.get_shape()

TensorShape([4, 3])

In [24]:
x

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]], dtype=int32)>

In [25]:
x.dtype

tf.int32

In [26]:
x.ref()

<Reference wrapping <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]], dtype=int32)>>

In [27]:
angle = tf.range(0, 2*np.pi+np.pi/4, np.pi/4)
angle, tf.cos(angle), tf.sin(angle), tf.square(tf.cos(angle)) +  tf.pow(tf.sin(angle), 2), tf.tan(angle)

(<tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([0.       , 0.7853982, 1.5707964, 2.3561945, 3.1415927, 3.926991 ,
        4.712389 , 5.4977875, 6.2831855], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([ 1.0000000e+00,  7.0710677e-01, -4.3711388e-08, -7.0710677e-01,
        -1.0000000e+00, -7.0710671e-01,  1.1924881e-08,  7.0710701e-01,
         1.0000000e+00], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([ 0.0000000e+00,  7.0710683e-01,  1.0000000e+00,  7.0710683e-01,
        -8.7422777e-08, -7.0710689e-01, -1.0000000e+00, -7.0710653e-01,
         1.7484555e-07], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.0000001 , 1.        , 0.99999994, 1.        ], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([ 0.0000000e+00,  1.0000000e+00, -2.2877334e+07, -1.0000000e+00,
         8.7422777e-08,  1.0000004e+00, -8.385

In [28]:
tf.cos(angle), tf.abs(tf.cos(angle))

(<tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([ 1.0000000e+00,  7.0710677e-01, -4.3711388e-08, -7.0710677e-01,
        -1.0000000e+00, -7.0710671e-01,  1.1924881e-08,  7.0710701e-01,
         1.0000000e+00], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([1.0000000e+00, 7.0710677e-01, 4.3711388e-08, 7.0710677e-01,
        1.0000000e+00, 7.0710671e-01, 1.1924881e-08, 7.0710701e-01,
        1.0000000e+00], dtype=float32)>)

In [29]:
tf.cos(angle), tf.sign(tf.cos(angle))

(<tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([ 1.0000000e+00,  7.0710677e-01, -4.3711388e-08, -7.0710677e-01,
        -1.0000000e+00, -7.0710671e-01,  1.1924881e-08,  7.0710701e-01,
         1.0000000e+00], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=array([ 1.,  1., -1., -1., -1., -1.,  1.,  1.,  1.], dtype=float32)>)

In [30]:
x, tf.argsort(x) # default - 1

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[1, 2, 0],
        [0, 1, 2],
        [2, 0, 1],
        [0, 2, 1]], dtype=int32)>)

In [31]:
x, tf.argsort(x, 0)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[1, 0, 2],
        [2, 2, 0],
        [3, 1, 3],
        [0, 3, 1]], dtype=int32)>)

In [32]:
x, tf.argsort(x, 0)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[1, 0, 2],
        [2, 2, 0],
        [3, 1, 3],
        [0, 3, 1]], dtype=int32)>)

In [33]:
x, x >0, tf.greater(x, 0)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=bool, numpy=
 array([[ True, False,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>,
 <tf.Tensor: shape=(4, 3), dtype=bool, numpy=
 array([[ True, False,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [34]:
x, x >= 0, tf.greater_equal(x, 0)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>,
 <tf.Tensor: shape=(4, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [35]:
x, x <= 0, tf.less_equal(x, 0)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=bool, numpy=
 array([[False,  True, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]])>,
 <tf.Tensor: shape=(4, 3), dtype=bool, numpy=
 array([[False,  True, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]])>)

In [36]:
x, x < 0, tf.less(x, 0)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]])>,
 <tf.Tensor: shape=(4, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]])>)

In [37]:
x, tf.sort(x), tf.sort(x, 1)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[0, 3, 5],
        [3, 7, 9],
        [2, 3, 5],
        [4, 6, 7]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[0, 3, 5],
        [3, 7, 9],
        [2, 3, 5],
        [4, 6, 7]], dtype=int32)>)

In [38]:
x, tf.sort(x, 0)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[3, 0, 2],
        [3, 5, 3],
        [4, 7, 6],
        [5, 7, 9]], dtype=int32)>)

In [39]:
a = x >= 2
b = x[-1] > 6
a, b, tf.logical_and(a, b), tf.logical_or(a, b), tf.logical_not(b)

(<tf.Tensor: shape=(4, 3), dtype=bool, numpy=
 array([[ True, False,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>,
 <tf.Tensor: shape=(3,), dtype=bool, numpy=array([False,  True, False])>,
 <tf.Tensor: shape=(4, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False,  True, False],
        [False,  True, False],
        [False,  True, False]])>,
 <tf.Tensor: shape=(4, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>,
 <tf.Tensor: shape=(3,), dtype=bool, numpy=array([ True, False,  True])>)

In [40]:
tf.bitwise.bitwise_and(x, 2*x), tf.bitwise.bitwise_or(x, 2*x)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[0, 0, 2],
        [2, 6, 0],
        [2, 0, 0],
        [0, 6, 4]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[15,  0,  7],
        [ 7, 15, 27],
        [ 7, 15,  6],
        [12, 15, 14]], dtype=int32)>)

In [41]:
tf.bitwise.right_shift(x, 2), tf.bitwise.invert(x), tf.bitwise.left_shift(x, 4)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[1, 0, 0],
        [0, 1, 2],
        [0, 1, 0],
        [1, 1, 1]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[ -6,  -1,  -4],
        [ -4,  -8, -10],
        [ -4,  -6,  -3],
        [ -5,  -8,  -7]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[ 80,   0,  48],
        [ 48, 112, 144],
        [ 48,  80,  32],
        [ 64, 112,  96]], dtype=int32)>)

In [42]:
tf.cast(x, "float")

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[5., 0., 3.],
       [3., 7., 9.],
       [3., 5., 2.],
       [4., 7., 6.]], dtype=float32)>

In [43]:
tf.cast(x, tf.float32)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[5., 0., 3.],
       [3., 7., 9.],
       [3., 5., 2.],
       [4., 7., 6.]], dtype=float32)>

In [44]:
tf.cast(x, tf.as_dtype(2))

<tf.Tensor: shape=(4, 3), dtype=float64, numpy=
array([[5., 0., 3.],
       [3., 7., 9.],
       [3., 5., 2.],
       [4., 7., 6.]])>

In [45]:
tf.as_dtype(1)

tf.float32

In [46]:
x > 0, tf.math.reduce_all(x > 0)

(<tf.Tensor: shape=(4, 3), dtype=bool, numpy=
 array([[ True, False,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>,
 <tf.Tensor: shape=(), dtype=bool, numpy=False>)

In [47]:
x, tf.case([(tf.math.reduce_all(tf.less(x, 5)), lambda: tf.constant(0))], default=lambda: tf.constant(-1))

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-1>)

In [48]:
x, tf.case([(tf.math.reduce_any(tf.less(x, 5)), lambda: x * -1)], default=lambda: tf.constant(-1))

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[-5,  0, -3],
        [-3, -7, -9],
        [-3, -5, -2],
        [-4, -7, -6]], dtype=int32)>)

In [49]:
x, 0.5 * tf.cast(x[1], tf.float32), tf.maximum(tf.cast(x, tf.float32), 0.5 * tf.cast(x[1], tf.float32))

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.5, 3.5, 4.5], dtype=float32)>,
 <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[5. , 3.5, 4.5],
        [3. , 7. , 9. ],
        [3. , 5. , 4.5],
        [4. , 7. , 6. ]], dtype=float32)>)

In [50]:
x, 0.5 * tf.cast(x[1], tf.float32), tf.minimum(tf.cast(x, tf.float32), 0.5 * tf.cast(x[1], tf.float32))

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.5, 3.5, 4.5], dtype=float32)>,
 <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[1.5, 0. , 3. ],
        [1.5, 3.5, 4.5],
        [1.5, 3.5, 2. ],
        [1.5, 3.5, 4.5]], dtype=float32)>)

In [51]:
x, tnp.amax(x)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>)

In [52]:
tnp.abs(x)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]], dtype=int32)>

In [53]:
# Select index in mask
mask = x > 5
x, mask, tf.boolean_mask(x, mask)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False,  True,  True],
        [False, False, False],
        [False,  True,  True]])>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([7, 9, 7, 6], dtype=int32)>)

In [54]:
mask = x > 5
mask = mask[1]
x, mask, tf.boolean_mask(x, mask, 1)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=bool, numpy=array([False,  True,  True])>,
 <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[0, 3],
        [7, 9],
        [5, 2],
        [7, 6]], dtype=int32)>)

In [55]:
mask = x > 5
mask = mask[:, 1]
x, mask, tf.boolean_mask(x, mask, 0)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=bool, numpy=array([False,  True, False,  True])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 7, 9],
        [4, 7, 6]], dtype=int32)>)

In [56]:
tf.broadcast_dynamic_shape((1, 2, 3), (2, 3))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [57]:
tf.broadcast_dynamic_shape((1, 5, 3), (2, 1, 3))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 5, 3], dtype=int32)>

In [58]:
tf.broadcast_dynamic_shape((10, 5, 3), (1, 3))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  5,  3], dtype=int32)>

In [59]:
tf.broadcast_static_shape(tf.TensorShape((10, 5, 3)), 
                          tf.TensorShape((1, 3)))

TensorShape([10, 5, 3])

In [60]:
x, tf.concat([x, x], axis=0)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(8, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>)

In [61]:
x, tf.concat([x, x], axis=1)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4, 6), dtype=int32, numpy=
 array([[5, 0, 3, 5, 0, 3],
        [3, 7, 9, 3, 7, 9],
        [3, 5, 2, 3, 5, 2],
        [4, 7, 6, 4, 7, 6]], dtype=int32)>)

In [62]:
def get_random_tensor(size, dtype="float", seed=-1):
    if seed == -1:
        seed = random.randint(0, 2**32 - 1)
    np.random.seed(seed)
    if isinstance(type(size), int):
        size = (size, )
    t = tf.convert_to_tensor(np.random.normal(0, 1., size))
    t = tf.cast(t, dtype)
    return t

In [63]:
a = get_random_tensor((2, 5, 3), seed=2)
b = get_random_tensor((2, 4, 3), seed=3)
a.shape, b.shape, tf.concat([a, b], 1).shape

(TensorShape([2, 5, 3]), TensorShape([2, 4, 3]), TensorShape([2, 9, 3]))

In [64]:
a = get_random_tensor((2, 5, 3), seed=2)
b = get_random_tensor((2, 5, 3), seed=3)
a.shape, b.shape, tf.stack([a, b], 0).shape

(TensorShape([2, 5, 3]), TensorShape([2, 5, 3]), TensorShape([2, 2, 5, 3]))

In [65]:
tf.rank(a), tf.rank(x).numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=3>, 2)

In [66]:
a = tf.range(3*5*2)
a = tf.reshape(a, (3, 5, 2))
s, r, t = tf.unstack(a, 3)
a, s, r, t

(<tf.Tensor: shape=(3, 5, 2), dtype=int32, numpy=
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],
 
        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]],
 
        [[20, 21],
         [22, 23],
         [24, 25],
         [26, 27],
         [28, 29]]], dtype=int32)>,
 <tf.Tensor: shape=(5, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(5, 2), dtype=int32, numpy=
 array([[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]], dtype=int32)>,
 <tf.Tensor: shape=(5, 2), dtype=int32, numpy=
 array([[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]], dtype=int32)>)

In [67]:
a = tf.range(3*5*2)
a = tf.reshape(a, (3, 5, 2))
s, r = tf.unstack(a, axis=2)
a, s, r

(<tf.Tensor: shape=(3, 5, 2), dtype=int32, numpy=
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],
 
        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]],
 
        [[20, 21],
         [22, 23],
         [24, 25],
         [26, 27],
         [28, 29]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 5), dtype=int32, numpy=
 array([[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28]], dtype=int32)>,
 <tf.Tensor: shape=(3, 5), dtype=int32, numpy=
 array([[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19],
        [21, 23, 25, 27, 29]], dtype=int32)>)

In [68]:
a = tf.range(3*5*2)
a = tf.reshape(a, (3, 5, 2))
a, tf.tile(a, (1, 1, 1))

(<tf.Tensor: shape=(3, 5, 2), dtype=int32, numpy=
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],
 
        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]],
 
        [[20, 21],
         [22, 23],
         [24, 25],
         [26, 27],
         [28, 29]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 5, 2), dtype=int32, numpy=
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],
 
        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]],
 
        [[20, 21],
         [22, 23],
         [24, 25],
         [26, 27],
         [28, 29]]], dtype=int32)>)

In [69]:
a = tf.range(3*5*2)
a = tf.reshape(a, (3, 5, 2))
a, tf.tile(a, (1, 1, 2))

(<tf.Tensor: shape=(3, 5, 2), dtype=int32, numpy=
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],
 
        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]],
 
        [[20, 21],
         [22, 23],
         [24, 25],
         [26, 27],
         [28, 29]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 5, 4), dtype=int32, numpy=
 array([[[ 0,  1,  0,  1],
         [ 2,  3,  2,  3],
         [ 4,  5,  4,  5],
         [ 6,  7,  6,  7],
         [ 8,  9,  8,  9]],
 
        [[10, 11, 10, 11],
         [12, 13, 12, 13],
         [14, 15, 14, 15],
         [16, 17, 16, 17],
         [18, 19, 18, 19]],
 
        [[20, 21, 20, 21],
         [22, 23, 22, 23],
         [24, 25, 24, 25],
         [26, 27, 26, 27],
         [28, 29, 28, 29]]], dtype=int32)>)

In [70]:
a = tf.range(3*5*2)
a = tf.reshape(a, (3, 5, 2))
a, tf.tile(a, (1, 2, 2))

(<tf.Tensor: shape=(3, 5, 2), dtype=int32, numpy=
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],
 
        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]],
 
        [[20, 21],
         [22, 23],
         [24, 25],
         [26, 27],
         [28, 29]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 10, 4), dtype=int32, numpy=
 array([[[ 0,  1,  0,  1],
         [ 2,  3,  2,  3],
         [ 4,  5,  4,  5],
         [ 6,  7,  6,  7],
         [ 8,  9,  8,  9],
         [ 0,  1,  0,  1],
         [ 2,  3,  2,  3],
         [ 4,  5,  4,  5],
         [ 6,  7,  6,  7],
         [ 8,  9,  8,  9]],
 
        [[10, 11, 10, 11],
         [12, 13, 12, 13],
         [14, 15, 14, 15],
         [16, 17, 16, 17],
         [18, 19, 18, 19],
         [10, 11, 10, 11],
         [12, 13, 12, 13],
         [14, 15, 14, 15],
         [16, 17, 16, 17],
         [18, 19, 18, 19]],
 
        [[20, 21, 20, 21],
         [22, 23, 

In [71]:
a = tf.range(3*5*2)
a = tf.reshape(a, (3, 5, 2))
a, tf.expand_dims(a, axis=0)

(<tf.Tensor: shape=(3, 5, 2), dtype=int32, numpy=
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],
 
        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]],
 
        [[20, 21],
         [22, 23],
         [24, 25],
         [26, 27],
         [28, 29]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 3, 5, 2), dtype=int32, numpy=
 array([[[[ 0,  1],
          [ 2,  3],
          [ 4,  5],
          [ 6,  7],
          [ 8,  9]],
 
         [[10, 11],
          [12, 13],
          [14, 15],
          [16, 17],
          [18, 19]],
 
         [[20, 21],
          [22, 23],
          [24, 25],
          [26, 27],
          [28, 29]]]], dtype=int32)>)

In [72]:
a = tf.range(3*5*2)
a = tf.reshape(a, (3, 5, 2))
a, tf.expand_dims(a, axis=1)

(<tf.Tensor: shape=(3, 5, 2), dtype=int32, numpy=
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],
 
        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]],
 
        [[20, 21],
         [22, 23],
         [24, 25],
         [26, 27],
         [28, 29]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 1, 5, 2), dtype=int32, numpy=
 array([[[[ 0,  1],
          [ 2,  3],
          [ 4,  5],
          [ 6,  7],
          [ 8,  9]]],
 
 
        [[[10, 11],
          [12, 13],
          [14, 15],
          [16, 17],
          [18, 19]]],
 
 
        [[[20, 21],
          [22, 23],
          [24, 25],
          [26, 27],
          [28, 29]]]], dtype=int32)>)

In [73]:
a = tf.range(3*5*2)
a = tf.reshape(a, (3, 5, 2))
a, tf.expand_dims(a, axis=3)

(<tf.Tensor: shape=(3, 5, 2), dtype=int32, numpy=
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],
 
        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]],
 
        [[20, 21],
         [22, 23],
         [24, 25],
         [26, 27],
         [28, 29]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 5, 2, 1), dtype=int32, numpy=
 array([[[[ 0],
          [ 1]],
 
         [[ 2],
          [ 3]],
 
         [[ 4],
          [ 5]],
 
         [[ 6],
          [ 7]],
 
         [[ 8],
          [ 9]]],
 
 
        [[[10],
          [11]],
 
         [[12],
          [13]],
 
         [[14],
          [15]],
 
         [[16],
          [17]],
 
         [[18],
          [19]]],
 
 
        [[[20],
          [21]],
 
         [[22],
          [23]],
 
         [[24],
          [25]],
 
         [[26],
          [27]],
 
         [[28],
          [29]]]], dtype=int32)>)

In [74]:
a = tf.range(5*2)
a = tf.reshape(a, (5, 2))
b = tf.expand_dims(tf.expand_dims(a, axis=2), axis=0)
a,  b, tf.squeeze(b)

(<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(1, 5, 2, 1), dtype=int32, numpy=
 array([[[[0],
          [1]],
 
         [[2],
          [3]],
 
         [[4],
          [5]],
 
         [[6],
          [7]],
 
         [[8],
          [9]]]], dtype=int32)>,
 <tf.Tensor: shape=(5, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]], dtype=int32)>)

In [75]:
a = tf.range(5*2)
a = tf.reshape(a, (5, 2))
b = tf.expand_dims(tf.expand_dims(a, axis=2), axis=0)
a,  b, tf.squeeze(b, axis=0)

(<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(1, 5, 2, 1), dtype=int32, numpy=
 array([[[[0],
          [1]],
 
         [[2],
          [3]],
 
         [[4],
          [5]],
 
         [[6],
          [7]],
 
         [[8],
          [9]]]], dtype=int32)>,
 <tf.Tensor: shape=(5, 2, 1), dtype=int32, numpy=
 array([[[0],
         [1]],
 
        [[2],
         [3]],
 
        [[4],
         [5]],
 
        [[6],
         [7]],
 
        [[8],
         [9]]], dtype=int32)>)

In [76]:
a = tf.range(5*2)
a = tf.reshape(a, (5, 2))
b = tf.expand_dims(tf.expand_dims(a, axis=2), axis=0)
a,  b, tf.squeeze(b, axis=(0, -1))

(<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(1, 5, 2, 1), dtype=int32, numpy=
 array([[[[0],
          [1]],
 
         [[2],
          [3]],
 
         [[4],
          [5]],
 
         [[6],
          [7]],
 
         [[8],
          [9]]]], dtype=int32)>,
 <tf.Tensor: shape=(5, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]], dtype=int32)>)

In [77]:
a = tf.range(5*2)
a = tf.reshape(a, (5, 2))
b = tf.expand_dims(tf.expand_dims(a, axis=2), axis=0)
a,  b, tf.squeeze(b, axis=(0, -1))

(<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(1, 5, 2, 1), dtype=int32, numpy=
 array([[[[0],
          [1]],
 
         [[2],
          [3]],
 
         [[4],
          [5]],
 
         [[6],
          [7]],
 
         [[8],
          [9]]]], dtype=int32)>,
 <tf.Tensor: shape=(5, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]], dtype=int32)>)

In [78]:
size = tf.constant([3, 5, 2])
a = tf.range(tf.math.reduce_prod(size))
a = tf.reshape(a, size)
a, tf.transpose(a, )

(<tf.Tensor: shape=(3, 5, 2), dtype=int32, numpy=
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],
 
        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]],
 
        [[20, 21],
         [22, 23],
         [24, 25],
         [26, 27],
         [28, 29]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 5, 3), dtype=int32, numpy=
 array([[[ 0, 10, 20],
         [ 2, 12, 22],
         [ 4, 14, 24],
         [ 6, 16, 26],
         [ 8, 18, 28]],
 
        [[ 1, 11, 21],
         [ 3, 13, 23],
         [ 5, 15, 25],
         [ 7, 17, 27],
         [ 9, 19, 29]]], dtype=int32)>)

In [79]:
size = tf.constant([3, 5, 2])
a = tf.range(tf.math.reduce_prod(size))
a = tf.reshape(a, size)
a, tf.transpose(a, (1, 0, 2))

(<tf.Tensor: shape=(3, 5, 2), dtype=int32, numpy=
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],
 
        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]],
 
        [[20, 21],
         [22, 23],
         [24, 25],
         [26, 27],
         [28, 29]]], dtype=int32)>,
 <tf.Tensor: shape=(5, 3, 2), dtype=int32, numpy=
 array([[[ 0,  1],
         [10, 11],
         [20, 21]],
 
        [[ 2,  3],
         [12, 13],
         [22, 23]],
 
        [[ 4,  5],
         [14, 15],
         [24, 25]],
 
        [[ 6,  7],
         [16, 17],
         [26, 27]],
 
        [[ 8,  9],
         [18, 19],
         [28, 29]]], dtype=int32)>)

In [80]:
size = tf.constant([3, 5, 2])
a = tf.range(tf.math.reduce_prod(size))
a = tf.reshape(a, size)
a, tf.split(a, axis=0, num_or_size_splits=3), tf.unstack(a, axis=0)

(<tf.Tensor: shape=(3, 5, 2), dtype=int32, numpy=
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],
 
        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]],
 
        [[20, 21],
         [22, 23],
         [24, 25],
         [26, 27],
         [28, 29]]], dtype=int32)>,
 [<tf.Tensor: shape=(1, 5, 2), dtype=int32, numpy=
  array([[[0, 1],
          [2, 3],
          [4, 5],
          [6, 7],
          [8, 9]]], dtype=int32)>,
  <tf.Tensor: shape=(1, 5, 2), dtype=int32, numpy=
  array([[[10, 11],
          [12, 13],
          [14, 15],
          [16, 17],
          [18, 19]]], dtype=int32)>,
  <tf.Tensor: shape=(1, 5, 2), dtype=int32, numpy=
  array([[[20, 21],
          [22, 23],
          [24, 25],
          [26, 27],
          [28, 29]]], dtype=int32)>],
 [<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
  array([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]], dtype=int32)>

In [81]:
size = tf.constant([6, 5, 2])
a = tf.range(tf.math.reduce_prod(size))
a = tf.reshape(a, size)
a, tf.split(a, axis=0, num_or_size_splits=3), tf.unstack(a, axis=0)

(<tf.Tensor: shape=(6, 5, 2), dtype=int32, numpy=
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],
 
        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]],
 
        [[20, 21],
         [22, 23],
         [24, 25],
         [26, 27],
         [28, 29]],
 
        [[30, 31],
         [32, 33],
         [34, 35],
         [36, 37],
         [38, 39]],
 
        [[40, 41],
         [42, 43],
         [44, 45],
         [46, 47],
         [48, 49]],
 
        [[50, 51],
         [52, 53],
         [54, 55],
         [56, 57],
         [58, 59]]], dtype=int32)>,
 [<tf.Tensor: shape=(2, 5, 2), dtype=int32, numpy=
  array([[[ 0,  1],
          [ 2,  3],
          [ 4,  5],
          [ 6,  7],
          [ 8,  9]],
  
         [[10, 11],
          [12, 13],
          [14, 15],
          [16, 17],
          [18, 19]]], dtype=int32)>,
  <tf.Tensor: shape=(2, 5, 2), dtype=int32, numpy=
  array([[[20, 21],
     

In [82]:
size = tf.constant([2, 5, 2])
a = tf.range(tf.math.reduce_prod(size))
a = tf.reshape(a, size)
a, tf.reduce_sum(a), tf.reduce_min(a), tf.reduce_max(a),  tf.reduce_all(a < 0), tf.reduce_any(a > 0), tf.reduce_prod(tf.cast(a + 1, tf.float64)[0]), tf.reduce_mean(a)

(<tf.Tensor: shape=(2, 5, 2), dtype=int32, numpy=
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],
 
        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=190>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=19>,
 <tf.Tensor: shape=(), dtype=bool, numpy=False>,
 <tf.Tensor: shape=(), dtype=bool, numpy=True>,
 <tf.Tensor: shape=(), dtype=float64, numpy=3628800.0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>)

In [83]:
tf.divide(a, 2*a)

<tf.Tensor: shape=(2, 5, 2), dtype=float64, numpy=
array([[[nan, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]],

       [[0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]]])>

In [84]:
tf.zeros_like(a)

<tf.Tensor: shape=(2, 5, 2), dtype=int32, numpy=
array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]], dtype=int32)>

In [85]:
tf.ones((2, 5))

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [86]:
tf.ones_like(a)

<tf.Tensor: shape=(2, 5, 2), dtype=int32, numpy=
array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)>

In [87]:
tf.eye(5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [88]:
tf.eye(num_rows=2, num_columns=5)

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]], dtype=float32)>

In [89]:
a = get_random_tensor((3, 2), seed=5)
b = get_random_tensor((3, 2), seed=15)
a, b, tf.maximum(a, b)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.4412275 , -0.33087015],
        [ 2.430771  , -0.25209212],
        [ 0.10960984,  1.5824811 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.3123285 ,  0.33928472],
        [-0.15590854, -0.5017897 ],
        [ 0.2355689 , -1.7636052 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.4412275 ,  0.33928472],
        [ 2.430771  , -0.25209212],
        [ 0.2355689 ,  1.5824811 ]], dtype=float32)>)

In [90]:
a = get_random_tensor((3, 2), seed=5)
b = get_random_tensor(2, seed=15)
a, b, tf.maximum(a, b), tf.minimum(a, b)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.4412275 , -0.33087015],
        [ 2.430771  , -0.25209212],
        [ 0.10960984,  1.5824811 ]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.3123285 ,  0.33928472], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.4412275 , 0.33928472],
        [2.430771  , 0.33928472],
        [0.10960984, 1.5824811 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.3123285 , -0.33087015],
        [-0.3123285 , -0.25209212],
        [-0.3123285 ,  0.33928472]], dtype=float32)>)

In [91]:
a = get_random_tensor((3, 2), seed=5)
a, tf.reduce_min(a), tf.reduce_min(a, 0), tf.reduce_max(a, 0), tf.reduce_sum(a, 1)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.4412275 , -0.33087015],
        [ 2.430771  , -0.25209212],
        [ 0.10960984,  1.5824811 ]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-0.33087015>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.10960984, -0.33087015], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.430771 , 1.5824811], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.11035734, 2.178679  , 1.692091  ], dtype=float32)>)

In [92]:
tf.linspace(0, 1, 11)

<tf.Tensor: shape=(11,), dtype=float64, numpy=array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])>

In [93]:
tf.range(0, 10, 1)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [94]:
tf.range(0, 10, 2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

In [95]:
a, tf.linalg.norm(a, ord=2), tf.sqrt(tf.reduce_sum(tf.square(a))), tf.norm(a, "euclidean")

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.4412275 , -0.33087015],
        [ 2.430771  , -0.25209212],
        [ 0.10960984,  1.5824811 ]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.9652345>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.9652345>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.9652345>)

In [96]:
a, tf.norm(a, axis=1), tf.sqrt(tf.reduce_sum(tf.square(a), 1))

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.4412275 , -0.33087015],
        [ 2.430771  , -0.25209212],
        [ 0.10960984,  1.5824811 ]], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.5515041, 2.443808 , 1.5862726], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.5515041, 2.443808 , 1.5862726], dtype=float32)>)

In [97]:
a, tf.clip_by_value(a, 0., 0.2)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.4412275 , -0.33087015],
        [ 2.430771  , -0.25209212],
        [ 0.10960984,  1.5824811 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.2       , 0.        ],
        [0.2       , 0.        ],
        [0.10960984, 0.2       ]], dtype=float32)>)

In [98]:
# t * clip_norm / l2norm(t)
a, tf.norm(a, axis=1), tf.clip_by_norm(a, 0.5, 1), tf.divide(a, tf.expand_dims(tf.norm(a, axis=1), 1)) * 0.5

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.4412275 , -0.33087015],
        [ 2.430771  , -0.25209212],
        [ 0.10960984,  1.5824811 ]], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.5515041, 2.443808 , 1.5862726], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.40002197, -0.29997072],
        [ 0.49733266, -0.05157772],
        [ 0.0345495 ,  0.49880493]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.40002197, -0.29997072],
        [ 0.49733266, -0.05157772],
        [ 0.0345495 ,  0.49880493]], dtype=float32)>)

In [99]:
tf.size(a), tf.rank(a), tf.shape(a)

(<tf.Tensor: shape=(), dtype=int32, numpy=6>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>)

In [100]:
tf.assert_equal(tf.size(a), 6)

In [101]:
try:
    tf.assert_equal(tf.size(a), 3)
except:
    print("Assertion error")
    

Assertion error


In [102]:
tf.assert_greater(tf.size(a), 3)

In [103]:
tf.constant(2,)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [104]:
tf.constant(2, dtype="float")

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [105]:
tf.constant(2, dtype="float", shape=(2, 4))

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[2., 2., 2., 2.],
       [2., 2., 2., 2.]], dtype=float32)>

In [106]:
tf.fill(4, 2.0)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2., 2., 2., 2.], dtype=float32)>

In [107]:
tf.fill((4, 5), 2.0), tf.constant(2., shape=(4, 5))

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]], dtype=float32)>)

In [108]:
tf.constant(tf.range(1, 11), shape=(2, 5))

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int32)>

In [109]:
tf.constant_initializer(2.)

In [110]:
tf.constant_initializer()((3, 4))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [111]:
tf.random_normal_initializer(0, 1.)((3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.5110626 ,  0.42292207, -0.41969493, -1.0360373 ],
       [-1.2368279 ,  0.47027302, -0.01397488,  1.1888583 ],
       [ 0.60253334,  0.5997111 , -0.70571196, -0.43297547]],
      dtype=float32)>

In [112]:
tf.random_normal_initializer(0, 1.)((3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.0668802 ,  0.19454929, -0.53082895,  0.09190083],
       [-0.17753708, -0.91930884, -2.0777557 ,  2.0391905 ],
       [ 0.8028997 , -0.9309037 , -0.37243125, -0.32097384]],
      dtype=float32)>

In [113]:
a = tf.range(3*2, dtype="float")
a = tf.reshape(a, (3, 2))
b = tf.range(2, dtype="float")
b = tf.reshape(b, (2, ) )
a, b, tf.einsum("ij, j -> i", a, b)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0., 1.],
        [2., 3.],
        [4., 5.]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 1.], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 3., 5.], dtype=float32)>)

In [114]:
a = tf.range(3*2, dtype="float")
a = tf.reshape(a, (3, 2))
b = tf.range(2*4, dtype="float")
b = tf.reshape(b, (2, 4) )
a, b, tf.einsum("ij, jk -> ik", a, b), tf.matmul(a, b)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0., 1.],
        [2., 3.],
        [4., 5.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 4.,  5.,  6.,  7.],
        [12., 17., 22., 27.],
        [20., 29., 38., 47.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 4.,  5.,  6.,  7.],
        [12., 17., 22., 27.],
        [20., 29., 38., 47.]], dtype=float32)>)

In [115]:
a = tf.range(3*2*5*6, dtype="float")
a = tf.reshape(a, (3, 2, 5, 6))
b = tf.range(6*3, dtype="float")
b = tf.reshape(b, (6, 3) )
a.shape, b.shape, tf.einsum("...ij, jk -> ...ik", a, b).shape

(TensorShape([3, 2, 5, 6]), TensorShape([6, 3]), TensorShape([3, 2, 5, 3]))

In [116]:
a = tf.range(4, dtype="float")
a, tf.einsum("i, i -> ", a, a)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=14.0>)

In [117]:
a = tf.range(4, dtype="float")
a, 2*a, tf.einsum("i, j -> ij", a, 2*a)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 2., 4., 6.], dtype=float32)>,
 <tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[ 0.,  0.,  0.,  0.],
        [ 0.,  2.,  4.,  6.],
        [ 0.,  4.,  8., 12.],
        [ 0.,  6., 12., 18.]], dtype=float32)>)

In [118]:
a = tf.range(3*2*5*6, dtype="float")
a = tf.reshape(a, (3, 2, 5, 6))
a.shape, tf.einsum("ijkl -> lkji", a).shape

(TensorShape([3, 2, 5, 6]), TensorShape([6, 5, 2, 3]))

In [119]:
a = tf.range(3*3, dtype="float")
a = tf.reshape(a, ( 3, 3))
a, tf.einsum("ii -> i", a)

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 4., 8.], dtype=float32)>)

In [120]:
a = tf.range(3*3, dtype="float")
a = tf.reshape(a, ( 3, 3))
a, tf.einsum("ii -> ", a)

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=12.0>)

In [121]:
a = tf.range(2*4*3, dtype="float")
a = tf.reshape(a, (2, 4, 3))
tf.ensure_shape(a, (2, 4, 3))

<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]]], dtype=float32)>

In [122]:
a = tf.range(2*4*3, dtype="float")
a = tf.reshape(a, (2, 4, 3))
tf.ensure_shape(a, (None, 4, 3))

<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]]], dtype=float32)>

In [123]:
a = tf.range(2*4*3, dtype="float")
a = tf.reshape(a, (2, 4, 3))
tf.ensure_shape(a, (None, None, None))

<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]]], dtype=float32)>

In [124]:
a = tf.range(2*4*3, dtype="float")
a = tf.reshape(a, (2, 4, 3))
tf.ensure_shape(a, (None, 4, None))

<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]]], dtype=float32)>

In [125]:
a = tf.range(2*4*3, dtype="float")
a = tf.reshape(a, (2, 4, 3))
try:
    tf.ensure_shape(a, (None, 5, None))
except:
    print("Error shape")

Error shape


In [126]:
np.random.seed(51)
partitions = np.random.binomial(1, 0.55, (7,))
t = tf.convert_to_tensor(np.random.randint(0, 100, (7,)))
partitions, t, tf.dynamic_partition(t, partitions, 1)

(array([0, 1, 1, 0, 1, 0, 1]),
 <tf.Tensor: shape=(7,), dtype=int64, numpy=array([37, 60, 94, 28, 84, 36, 35])>,
 [<tf.Tensor: shape=(3,), dtype=int64, numpy=array([37, 28, 36])>])

In [127]:
np.random.seed(51)
partitions = np.random.binomial(1, 0.55, (7,))
t = tf.convert_to_tensor(np.random.randint(0, 100, (7,)))
partitions, t, tf.dynamic_partition(t, partitions, 3)

(array([0, 1, 1, 0, 1, 0, 1]),
 <tf.Tensor: shape=(7,), dtype=int64, numpy=array([37, 60, 94, 28, 84, 36, 35])>,
 [<tf.Tensor: shape=(3,), dtype=int64, numpy=array([37, 28, 36])>,
  <tf.Tensor: shape=(4,), dtype=int64, numpy=array([60, 94, 84, 35])>,
  <tf.Tensor: shape=(0,), dtype=int64, numpy=array([], dtype=int64)>])

In [128]:
np.random.seed(51)
partitions = np.random.binomial(2, 0.55, (7,))
t = tf.convert_to_tensor(np.random.randint(0, 100, (7,)))
partitions, t, tf.dynamic_partition(t, partitions, 3)

(array([1, 2, 1, 1, 2, 0, 2]),
 <tf.Tensor: shape=(7,), dtype=int64, numpy=array([37, 60, 94, 28, 84, 36, 35])>,
 [<tf.Tensor: shape=(1,), dtype=int64, numpy=array([36])>,
  <tf.Tensor: shape=(3,), dtype=int64, numpy=array([37, 94, 28])>,
  <tf.Tensor: shape=(3,), dtype=int64, numpy=array([60, 84, 35])>])

In [129]:
np.random.seed(51)
partitions = np.random.binomial(2, 0.55, (4,))
t = tf.convert_to_tensor(np.random.randint(0, 100, (4, 5)))
partitions, t, tf.dynamic_partition(t, partitions, 3)

(array([1, 2, 1, 1]),
 <tf.Tensor: shape=(4, 5), dtype=int64, numpy=
 array([[94, 52, 37, 37, 60],
        [94, 28, 84, 36, 35],
        [27, 28, 42, 10,  6],
        [25, 33, 77, 39, 48]])>,
 [<tf.Tensor: shape=(0, 5), dtype=int64, numpy=array([], shape=(0, 5), dtype=int64)>,
  <tf.Tensor: shape=(3, 5), dtype=int64, numpy=
  array([[94, 52, 37, 37, 60],
         [27, 28, 42, 10,  6],
         [25, 33, 77, 39, 48]])>,
  <tf.Tensor: shape=(1, 5), dtype=int64, numpy=array([[94, 28, 84, 36, 35]])>])

In [130]:
np.random.seed(51)
partitions = np.random.binomial(2, 0.55, (4,))
t = tf.convert_to_tensor(np.random.randint(0, 100, (4, 5)))
partitions, t, tf.dynamic_partition(t, partitions, 2)

(array([1, 2, 1, 1]),
 <tf.Tensor: shape=(4, 5), dtype=int64, numpy=
 array([[94, 52, 37, 37, 60],
        [94, 28, 84, 36, 35],
        [27, 28, 42, 10,  6],
        [25, 33, 77, 39, 48]])>,
 [<tf.Tensor: shape=(0, 5), dtype=int64, numpy=array([], shape=(0, 5), dtype=int64)>,
  <tf.Tensor: shape=(3, 5), dtype=int64, numpy=
  array([[94, 52, 37, 37, 60],
         [27, 28, 42, 10,  6],
         [25, 33, 77, 39, 48]])>])

In [131]:
np.random.seed(541)
partitions = np.random.binomial(4, 0.5, (20,))
t = tf.convert_to_tensor(np.random.randint(0, 100, (20,)))
partitions, t, tf.dynamic_partition(t, partitions, 5)

(array([2, 3, 4, 2, 2, 2, 2, 2, 3, 0, 2, 3, 0, 3, 1, 2, 2, 2, 2, 3]),
 <tf.Tensor: shape=(20,), dtype=int64, numpy=
 array([32, 70, 83, 51, 25, 74, 28, 11, 90, 71, 69, 96, 84, 66, 61, 16, 66,
        69, 36, 29])>,
 [<tf.Tensor: shape=(2,), dtype=int64, numpy=array([71, 84])>,
  <tf.Tensor: shape=(1,), dtype=int64, numpy=array([61])>,
  <tf.Tensor: shape=(11,), dtype=int64, numpy=array([32, 51, 25, 74, 28, 11, 69, 16, 66, 69, 36])>,
  <tf.Tensor: shape=(5,), dtype=int64, numpy=array([70, 90, 96, 66, 29])>,
  <tf.Tensor: shape=(1,), dtype=int64, numpy=array([83])>])

In [132]:
indices = [[] for i in range(5)]
for j, i in enumerate(partitions):
    indices[i].append(j)
    
indices 

[[9, 12],
 [14],
 [0, 3, 4, 5, 6, 7, 10, 15, 16, 17, 18],
 [1, 8, 11, 13, 19],
 [2]]

In [133]:
t, tf.dynamic_stitch(indices=indices, data=tf.dynamic_partition(t, partitions, 5))

(<tf.Tensor: shape=(20,), dtype=int64, numpy=
 array([32, 70, 83, 51, 25, 74, 28, 11, 90, 71, 69, 96, 84, 66, 61, 16, 66,
        69, 36, 29])>,
 <tf.Tensor: shape=(20,), dtype=int64, numpy=
 array([32, 70, 83, 51, 25, 74, 28, 11, 90, 71, 69, 96, 84, 66, 61, 16, 66,
        69, 36, 29])>)

In [134]:
a = tf.range(4, dtype="float")
a, tf.foldl(lambda u, v: u + v, a)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [135]:
np.random.seed(100)
a = tf.constant(np.random.randint(0, 100, (5)))
a, tf.foldl(lambda u, v: tf.maximum(u, v), a)

(<tf.Tensor: shape=(5,), dtype=int64, numpy=array([ 8, 24, 67, 87, 79])>,
 <tf.Tensor: shape=(), dtype=int64, numpy=87>)

In [136]:
np.random.seed(100)
a = tf.constant(np.random.randint(0, 100, (5, 10)))
a, tf.foldl(lambda u, v: tf.maximum(u, v), a)

(<tf.Tensor: shape=(5, 10), dtype=int64, numpy=
 array([[ 8, 24, 67, 87, 79, 48, 10, 94, 52, 98],
        [53, 66, 98, 14, 34, 24, 15, 60, 58, 16],
        [ 9, 93, 86,  2, 27,  4, 31,  1, 13, 83],
        [ 4, 91, 59, 67,  7, 49, 47, 65, 61, 14],
        [55, 71, 80,  2, 94, 19, 98, 63, 53, 27]])>,
 <tf.Tensor: shape=(10,), dtype=int64, numpy=array([55, 93, 98, 87, 94, 49, 98, 94, 61, 98])>)

In [137]:
np.random.seed(100)
a = tf.constant(np.random.randint(0, 100, (5, 10)))
a, tf.foldr(lambda u, v: tf.maximum(u, v), a)

(<tf.Tensor: shape=(5, 10), dtype=int64, numpy=
 array([[ 8, 24, 67, 87, 79, 48, 10, 94, 52, 98],
        [53, 66, 98, 14, 34, 24, 15, 60, 58, 16],
        [ 9, 93, 86,  2, 27,  4, 31,  1, 13, 83],
        [ 4, 91, 59, 67,  7, 49, 47, 65, 61, 14],
        [55, 71, 80,  2, 94, 19, 98, 63, 53, 27]])>,
 <tf.Tensor: shape=(10,), dtype=int64, numpy=array([55, 93, 98, 87, 94, 49, 98, 94, 61, 98])>)

In [138]:
x = get_random_tensor((5, 4), seed=10)
indices =[0, 1, 2]
x, indices, tf.gather(x, indices=indices, axis=0)

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 1.3315865 ,  0.715279  , -1.5454003 , -0.00838385],
        [ 0.621336  , -0.72008556,  0.26551157,  0.10854852],
        [ 0.00429143, -0.17460021,  0.4330262 ,  1.2030374 ],
        [-0.96506566,  1.028274  ,  0.22863013,  0.44513762],
        [-1.1366022 ,  0.13513687,  1.484537  , -1.0798049 ]],
       dtype=float32)>,
 [0, 1, 2],
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 1.3315865 ,  0.715279  , -1.5454003 , -0.00838385],
        [ 0.621336  , -0.72008556,  0.26551157,  0.10854852],
        [ 0.00429143, -0.17460021,  0.4330262 ,  1.2030374 ]],
       dtype=float32)>)

In [139]:
x = get_random_tensor((5, 4), seed=10)
indices = tf.constant( [0, 1, 3, 4, 5])
x, indices, tf.gather(x, indices=indices, axis=1)

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 1.3315865 ,  0.715279  , -1.5454003 , -0.00838385],
        [ 0.621336  , -0.72008556,  0.26551157,  0.10854852],
        [ 0.00429143, -0.17460021,  0.4330262 ,  1.2030374 ],
        [-0.96506566,  1.028274  ,  0.22863013,  0.44513762],
        [-1.1366022 ,  0.13513687,  1.484537  , -1.0798049 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 3, 4, 5], dtype=int32)>,
 <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[ 1.3315865 ,  0.715279  , -0.00838385,  0.        ,  0.        ],
        [ 0.621336  , -0.72008556,  0.10854852,  0.        ,  0.        ],
        [ 0.00429143, -0.17460021,  1.2030374 ,  0.        ,  0.        ],
        [-0.96506566,  1.028274  ,  0.44513762,  0.        ,  0.        ],
        [-1.1366022 ,  0.13513687, -1.0798049 ,  0.        ,  0.        ]],
       dtype=float32)>)

In [140]:
x = get_random_tensor((5, 4), seed=10)
indices = tf.constant([[0, 1]])
x, indices, tf.gather(x, indices=indices, axis=0)

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 1.3315865 ,  0.715279  , -1.5454003 , -0.00838385],
        [ 0.621336  , -0.72008556,  0.26551157,  0.10854852],
        [ 0.00429143, -0.17460021,  0.4330262 ,  1.2030374 ],
        [-0.96506566,  1.028274  ,  0.22863013,  0.44513762],
        [-1.1366022 ,  0.13513687,  1.484537  , -1.0798049 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2, 4), dtype=float32, numpy=
 array([[[ 1.3315865 ,  0.715279  , -1.5454003 , -0.00838385],
         [ 0.621336  , -0.72008556,  0.26551157,  0.10854852]]],
       dtype=float32)>)

In [141]:
x = get_random_tensor((5, 4), seed=10)
indices = tf.constant([[0, 1]])
x, indices, tf.gather(x, indices=indices, axis=1)

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 1.3315865 ,  0.715279  , -1.5454003 , -0.00838385],
        [ 0.621336  , -0.72008556,  0.26551157,  0.10854852],
        [ 0.00429143, -0.17460021,  0.4330262 ,  1.2030374 ],
        [-0.96506566,  1.028274  ,  0.22863013,  0.44513762],
        [-1.1366022 ,  0.13513687,  1.484537  , -1.0798049 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>,
 <tf.Tensor: shape=(5, 1, 2), dtype=float32, numpy=
 array([[[ 1.3315865 ,  0.715279  ]],
 
        [[ 0.621336  , -0.72008556]],
 
        [[ 0.00429143, -0.17460021]],
 
        [[-0.96506566,  1.028274  ]],
 
        [[-1.1366022 ,  0.13513687]]], dtype=float32)>)

In [142]:
x = tf.range(4*3)
x = tf.reshape(x, (4, 3))
indices = tf.constant([[2, 1],
                       [0, 4]
                       ])
x, indices, tf.gather(x, indices=indices, axis=1)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 1],
        [0, 4]], dtype=int32)>,
 <tf.Tensor: shape=(4, 2, 2), dtype=int32, numpy=
 array([[[ 2,  1],
         [ 0,  0]],
 
        [[ 5,  4],
         [ 3,  0]],
 
        [[ 8,  7],
         [ 6,  0]],
 
        [[11, 10],
         [ 9,  0]]], dtype=int32)>)

In [143]:
x = tf.range(4*3)
x = tf.reshape(x, (4, 3))
indices = tf.constant([[2, 1],
                       [0, 4]
                       ])
x, indices, tf.gather(x, indices=indices, axis=0)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 1],
        [0, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[6, 7, 8],
         [3, 4, 5]],
 
        [[0, 1, 2],
         [0, 0, 0]]], dtype=int32)>)

In [144]:
x = tf.range(4*3)
x = tf.reshape(x, (4, 3))
indices = tf.constant([[2, 1],
                       [0, 2],
                       [2, 1], 
                       [0, 2]
                       ])
x, indices, tf.gather(x, indices=indices, axis=1, batch_dims=0)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]], dtype=int32)>,
 <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[2, 1],
        [0, 2],
        [2, 1],
        [0, 2]], dtype=int32)>,
 <tf.Tensor: shape=(4, 4, 2), dtype=int32, numpy=
 array([[[ 2,  1],
         [ 0,  2],
         [ 2,  1],
         [ 0,  2]],
 
        [[ 5,  4],
         [ 3,  5],
         [ 5,  4],
         [ 3,  5]],
 
        [[ 8,  7],
         [ 6,  8],
         [ 8,  7],
         [ 6,  8]],
 
        [[11, 10],
         [ 9, 11],
         [11, 10],
         [ 9, 11]]], dtype=int32)>)

In [145]:
x = tf.range(4*3)
x = tf.reshape(x, (4, 3))
indices = tf.constant([[2, 1],
                       [0, 2],
                       [2, 1], 
                       [0, 2]
                       ])
x, indices, tf.gather(x, indices=indices, axis=1, batch_dims=1)

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]], dtype=int32)>,
 <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[2, 1],
        [0, 2],
        [2, 1],
        [0, 2]], dtype=int32)>,
 <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[ 2,  1],
        [ 3,  5],
        [ 8,  7],
        [ 9, 11]], dtype=int32)>)

In [146]:
x = tf.range(4*2*3)
x = tf.reshape(x, (4, 2, 3))
indices = tf.constant([1, 2])
x, indices, tf.gather(x, indices=indices, axis=-1)

(<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
 array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11]],
 
        [[12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23]]], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(4, 2, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 4,  5]],
 
        [[ 7,  8],
         [10, 11]],
 
        [[13, 14],
         [16, 17]],
 
        [[19, 20],
         [22, 23]]], dtype=int32)>)

In [147]:
x = tf.range(4*2*3)
x = tf.reshape(x, (4, 2, 3))
indices = tf.constant([1, 0,  2, 3])
x, indices, tf.gather(x, indices=indices, axis=2, batch_dims=1)

(<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
 array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11]],
 
        [[12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23]]], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 0, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[ 1,  4],
        [ 6,  9],
        [14, 17],
        [ 0,  0]], dtype=int32)>)

In [148]:
x = tf.range(4*2*3)
x = tf.reshape(x, (4, 2, 3))
indices = tf.constant([1, 0,  2, 3])
x, indices, tf.gather(x, indices=indices, axis=1, batch_dims=1)

(<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
 array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11]],
 
        [[12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23]]], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 0, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[3, 4, 5],
        [6, 7, 8],
        [0, 0, 0],
        [0, 0, 0]], dtype=int32)>)

In [149]:
x = tf.range(4*2*3)
x = tf.reshape(x, (4, 2, 3))
x, x[-2:]

(<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
 array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11]],
 
        [[12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23]]], dtype=int32)>)

In [150]:
x = tf.range(4*2*3)
x = tf.reshape(x, (4, 2, 3))
x, x[0:1, 1:, 1:], tf.slice(x, [0, 1, 1], [1, 1, 2])

(<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
 array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11]],
 
        [[12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 1, 2), dtype=int32, numpy=array([[[4, 5]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 1, 2), dtype=int32, numpy=array([[[4, 5]]], dtype=int32)>)

In [151]:
x = tf.range(2*3)
x = tf.reshape(x, (2, 3))
indices = tf.constant([1, 0, ])
x, indices, tf.gather(x, indices=indices, axis=1, batch_dims=1)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[0, 1, 2],
        [3, 4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 0], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>)

In [152]:
x = tf.range(2*3)
x = tf.reshape(x, (2, 3))
indices = tf.constant([1, 0, ])
x, indices, tf.gather(x, indices=indices, axis=1)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[0, 1, 2],
        [3, 4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 0], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [4, 3]], dtype=int32)>)

In [153]:
x = tf.range(2*3)
x = tf.reshape(x, (2, 3))
indices = tf.constant([[1, 0,], [0, 1] ])
x, indices, tf.gather_nd(x, indices=indices, )

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[0, 1, 2],
        [3, 4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 1]], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 1], dtype=int32)>)

In [154]:
x = tf.range(2*3)
x = tf.reshape(x, (2, 3))
indices = tf.constant([[1, 0,], [0, 1], [2, 0] ])
x, indices, tf.gather_nd(x, indices=indices, )

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[0, 1, 2],
        [3, 4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 1],
        [2, 0]], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 1, 0], dtype=int32)>)

In [155]:
x = tf.range(2*3)
x = tf.reshape(x, (2, 3))
indices = tf.constant([[1], [0] ])
x, indices, tf.gather_nd(x, indices=indices, )

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[0, 1, 2],
        [3, 4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[1],
        [0]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 4, 5],
        [0, 1, 2]], dtype=int32)>)

In [156]:
x = tf.range(2*3)
x = tf.reshape(x, (2, 3))
indices = tf.constant([[1], [0] ])
x, indices, tf.gather_nd(x, indices=indices, batch_dims=1 )

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[0, 1, 2],
        [3, 4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[1],
        [0]], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>)

In [157]:
np.random.seed(0)
mask = tf.constant(np.random.randint(0, 2, (5,)).astype(bool))
x = tf.range(3* 4 * 5, dtype=float)
x = tf.reshape(x, (3, 4, 5))
x, mask, tf.boolean_mask(x, mask, axis=2)

(<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
 array([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]],
 
        [[20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.],
         [30., 31., 32., 33., 34.],
         [35., 36., 37., 38., 39.]],
 
        [[40., 41., 42., 43., 44.],
         [45., 46., 47., 48., 49.],
         [50., 51., 52., 53., 54.],
         [55., 56., 57., 58., 59.]]], dtype=float32)>,
 <tf.Tensor: shape=(5,), dtype=bool, numpy=array([False,  True,  True, False,  True])>,
 <tf.Tensor: shape=(3, 4, 3), dtype=float32, numpy=
 array([[[ 1.,  2.,  4.],
         [ 6.,  7.,  9.],
         [11., 12., 14.],
         [16., 17., 19.]],
 
        [[21., 22., 24.],
         [26., 27., 29.],
         [31., 32., 34.],
         [36., 37., 39.]],
 
        [[41., 42., 44.],
         [46., 47., 49.],
         [51., 52., 54.],
         [56., 57., 59.]]], dtype=float32)>)

In [158]:
np.random.seed(0)
mask = tf.constant(np.random.randint(0, 2, (5,)).astype(bool))
x = tf.constant(np.random.normal(0, 1., (4, 5)), dtype=float)
y = tf.constant(np.random.normal(0, 1., (4, 5)), dtype=float)
x, mask, tf.where(mask, x, y)

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[ 0.07085926,  0.07304142, -1.4223258 ,  1.5200695 , -0.29139397],
        [-0.13309029, -0.1730696 , -1.7616516 , -0.08767307,  1.3668793 ],
        [ 1.1253141 , -0.35899556,  1.2206081 , -1.3394955 ,  0.42837337],
        [-0.12346315,  1.4143772 , -0.12405066,  2.008157  ,  0.22988653]],
       dtype=float32)>,
 <tf.Tensor: shape=(5,), dtype=bool, numpy=array([False,  True,  True, False,  True])>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[ 0.60489374,  0.07304142, -1.4223258 ,  0.23043416, -0.29139397],
        [-0.96898025, -0.1730696 , -1.7616516 , -0.44423282,  1.3668793 ],
        [-0.88180053, -0.35899556,  1.2206081 , -1.3232274 ,  0.42837337],
        [ 0.90734595,  1.4143772 , -0.12405066, -1.0261788 ,  0.22988653]],
       dtype=float32)>)

In [159]:
np.random.seed(0)
mask = tf.constant(np.random.randint(0, 2, (5,)).astype(bool))
x = tf.constant(np.random.normal(0, 1., (4, 5)), dtype=float)
y = tf.constant(np.random.normal(0, 1., (1, 5)), dtype=float)
x, mask, tf.where(mask, x, y)

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[ 0.07085926,  0.07304142, -1.4223258 ,  1.5200695 , -0.29139397],
        [-0.13309029, -0.1730696 , -1.7616516 , -0.08767307,  1.3668793 ],
        [ 1.1253141 , -0.35899556,  1.2206081 , -1.3394955 ,  0.42837337],
        [-0.12346315,  1.4143772 , -0.12405066,  2.008157  ,  0.22988653]],
       dtype=float32)>,
 <tf.Tensor: shape=(5,), dtype=bool, numpy=array([False,  True,  True, False,  True])>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[ 0.60489374,  0.07304142, -1.4223258 ,  0.23043416, -0.29139397],
        [ 0.60489374, -0.1730696 , -1.7616516 ,  0.23043416,  1.3668793 ],
        [ 0.60489374, -0.35899556,  1.2206081 ,  0.23043416,  0.42837337],
        [ 0.60489374,  1.4143772 , -0.12405066,  0.23043416,  0.22988653]],
       dtype=float32)>)

In [160]:
x

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 0.07085926,  0.07304142, -1.4223258 ,  1.5200695 , -0.29139397],
       [-0.13309029, -0.1730696 , -1.7616516 , -0.08767307,  1.3668793 ],
       [ 1.1253141 , -0.35899556,  1.2206081 , -1.3394955 ,  0.42837337],
       [-0.12346315,  1.4143772 , -0.12405066,  2.008157  ,  0.22988653]],
      dtype=float32)>

In [161]:
y = tf.identity(x)
x += 5
y, x

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[ 0.07085926,  0.07304142, -1.4223258 ,  1.5200695 , -0.29139397],
        [-0.13309029, -0.1730696 , -1.7616516 , -0.08767307,  1.3668793 ],
        [ 1.1253141 , -0.35899556,  1.2206081 , -1.3394955 ,  0.42837337],
        [-0.12346315,  1.4143772 , -0.12405066,  2.008157  ,  0.22988653]],
       dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[5.0708594, 5.0730414, 3.5776742, 6.5200696, 4.7086062],
        [4.8669095, 4.8269305, 3.2383485, 4.912327 , 6.3668795],
        [6.125314 , 4.6410046, 6.220608 , 3.6605043, 5.4283733],
        [4.876537 , 6.414377 , 4.8759494, 7.008157 , 5.2298865]],
       dtype=float32)>)

In [162]:
tf.is_tensor(x)

True

In [163]:
tf.is_tensor(5.0)

False

In [164]:
tf.map_fn(lambda u: tf.range(u, u+4) , tf.constant([1, 2, 3]))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]], dtype=int32)>

In [165]:
x = tf.range(5)
y = tf.range(10, 13)
x, y, tf.meshgrid(x, y, )

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 11, 12], dtype=int32)>,
 [<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
  array([[0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4]], dtype=int32)>,
  <tf.Tensor: shape=(3, 5), dtype=int32, numpy=
  array([[10, 10, 10, 10, 10],
         [11, 11, 11, 11, 11],
         [12, 12, 12, 12, 12]], dtype=int32)>])

In [166]:
x = tf.range(5)
y = tf.range(10, 13)
x, y, tf.meshgrid(x, y, indexing="xy")

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 11, 12], dtype=int32)>,
 [<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
  array([[0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4]], dtype=int32)>,
  <tf.Tensor: shape=(3, 5), dtype=int32, numpy=
  array([[10, 10, 10, 10, 10],
         [11, 11, 11, 11, 11],
         [12, 12, 12, 12, 12]], dtype=int32)>])

In [167]:
x = tf.range(5)
y = tf.range(10, 13)
x, y, tf.meshgrid(x, y, indexing="ij")

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 11, 12], dtype=int32)>,
 [<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
  array([[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4]], dtype=int32)>,
  <tf.Tensor: shape=(5, 3), dtype=int32, numpy=
  array([[10, 11, 12],
         [10, 11, 12],
         [10, 11, 12],
         [10, 11, 12],
         [10, 11, 12]], dtype=int32)>])

In [168]:
x = tf.range(5)
y = tf.range(10, 13)
z = tf.range(20, 24)
tf.meshgrid(x, y, z)

[<tf.Tensor: shape=(3, 5, 4), dtype=int32, numpy=
 array([[[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4]],
 
        [[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4]],
 
        [[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 5, 4), dtype=int32, numpy=
 array([[[10, 10, 10, 10],
         [10, 10, 10, 10],
         [10, 10, 10, 10],
         [10, 10, 10, 10],
         [10, 10, 10, 10]],
 
        [[11, 11, 11, 11],
         [11, 11, 11, 11],
         [11, 11, 11, 11],
         [11, 11, 11, 11],
         [11, 11, 11, 11]],
 
        [[12, 12, 12, 12],
         [12, 12, 12, 12],
         [12, 12, 12, 12],
         [12, 12, 12, 12],
         [12, 12, 12, 12]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 5, 4), dtype=int32, numpy=
 array([[[20, 21, 22, 23],
         [20, 21, 22, 23],


In [169]:
tf.one_hot([2, 4, 5], depth=10)

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)>

In [170]:
tf.one_hot([[2], [4], [5]], depth=10)

<tf.Tensor: shape=(3, 1, 10), dtype=float32, numpy=
array([[[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]]], dtype=float32)>

In [171]:
tf.one_hot([2, 4, 5], depth=10, on_value=0, off_value=1)

<tf.Tensor: shape=(3, 10), dtype=int32, numpy=
array([[1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 1]], dtype=int32)>

In [172]:
x = tf.range(1, 7)
x = tf.reshape(x, ( 2, 3))
x, tf.pad(x, tf.constant([[0, 1], [2, 3]]), constant_values=-1)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[-1, -1,  1,  2,  3, -1, -1, -1],
        [-1, -1,  4,  5,  6, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1]], dtype=int32)>)

In [173]:
x = tf.range(1, 7)
x = tf.reshape(x, ( 2, 3))
x, tf.pad(x, tf.constant([[0, 1], [2, 2]]), mode="REFLECT")

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 7), dtype=int32, numpy=
 array([[3, 2, 1, 2, 3, 2, 1],
        [6, 5, 4, 5, 6, 5, 4],
        [3, 2, 1, 2, 3, 2, 1]], dtype=int32)>)

In [174]:
x = tf.range(1, 7)
x = tf.reshape(x, ( 2, 3))
x, tf.pad(x, tf.constant([[0, 1], [2, 2]]), mode="SYMMETRIC")

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 7), dtype=int32, numpy=
 array([[2, 1, 1, 2, 3, 3, 2],
        [5, 4, 4, 5, 6, 6, 5],
        [5, 4, 4, 5, 6, 6, 5]], dtype=int32)>)

In [175]:
x = tf.range(1, 7)
x, tf.repeat(x, tf.constant(2))

(<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>,
 <tf.Tensor: shape=(12,), dtype=int32, numpy=array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6], dtype=int32)>)

In [176]:
x = tf.range(1, 7)
x = tf.reshape(x, ( 2, 3))
x, tf.repeat(x, tf.constant([1, 1, 2, 2, 3, 3]))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(12,), dtype=int32, numpy=array([1, 2, 3, 3, 4, 4, 5, 5, 5, 6, 6, 6], dtype=int32)>)

In [177]:
x = tf.range(1, 7)
x = tf.reshape(x, ( 2, 3))
x, tf.repeat(x, tf.constant([2]))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(12,), dtype=int32, numpy=array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6], dtype=int32)>)

In [178]:
x = tf.range(1, 7)
x = tf.reshape(x, ( 2, 3))
x, tf.repeat(x, tf.constant([2]), axis=0)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [1, 2, 3],
        [4, 5, 6],
        [4, 5, 6]], dtype=int32)>)

In [179]:
x = tf.range(1, 7)
x = tf.reshape(x, ( 2, 3))
x, tf.repeat(x, tf.constant([2]), axis=1)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[1, 1, 2, 2, 3, 3],
        [4, 4, 5, 5, 6, 6]], dtype=int32)>)

In [180]:
x = tf.range(24)
x = tf.reshape(x, (1, 2, 3, 4))
x, tf.reverse(x, [-1])

(<tf.Tensor: shape=(1, 2, 3, 4), dtype=int32, numpy=
 array([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2, 3, 4), dtype=int32, numpy=
 array([[[[ 3,  2,  1,  0],
          [ 7,  6,  5,  4],
          [11, 10,  9,  8]],
 
         [[15, 14, 13, 12],
          [19, 18, 17, 16],
          [23, 22, 21, 20]]]], dtype=int32)>)

In [181]:
x = tf.range(24)
x = tf.reshape(x, (1, 2, 3, 4))
x, tf.reverse(x, [-1, -2])

(<tf.Tensor: shape=(1, 2, 3, 4), dtype=int32, numpy=
 array([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2, 3, 4), dtype=int32, numpy=
 array([[[[11, 10,  9,  8],
          [ 7,  6,  5,  4],
          [ 3,  2,  1,  0]],
 
         [[23, 22, 21, 20],
          [19, 18, 17, 16],
          [15, 14, 13, 12]]]], dtype=int32)>)

In [182]:
x = tf.range(4*8)
x = tf.reshape(x, (4, 8))
x, tf.reverse_sequence(x, [7, 2, 3, 1], batch_axis=0, seq_axis=1)

(<tf.Tensor: shape=(4, 8), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]], dtype=int32)>,
 <tf.Tensor: shape=(4, 8), dtype=int32, numpy=
 array([[ 6,  5,  4,  3,  2,  1,  0,  7],
        [ 9,  8, 10, 11, 12, 13, 14, 15],
        [18, 17, 16, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]], dtype=int32)>)

In [183]:
x = tf.range(24)
x = tf.reshape(x, (2, 3, 4))
x, tf.roll(x, shift=0, axis=0)

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]], dtype=int32)>)

In [184]:
x = tf.range(24)
x = tf.reshape(x, (2, 3, 4))
x, tf.roll(x, shift=1, axis=0)

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],
 
        [[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]], dtype=int32)>)

In [185]:
x = tf.range(24)
x = tf.reshape(x, (2, 3, 4))
x, tf.roll(x, shift=2, axis=0)

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]], dtype=int32)>)

In [186]:
x = tf.range(24)
x = tf.reshape(x, (2, 3, 4))
x, tf.roll(x, shift=1, axis=-1)

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 3,  0,  1,  2],
         [ 7,  4,  5,  6],
         [11,  8,  9, 10]],
 
        [[15, 12, 13, 14],
         [19, 16, 17, 18],
         [23, 20, 21, 22]]], dtype=int32)>)

In [187]:
x = tf.range(24)
x = tf.reshape(x, (2, 3, 4))
x, tf.roll(x, shift=-1, axis=-1)

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  0],
         [ 5,  6,  7,  4],
         [ 9, 10, 11,  8]],
 
        [[13, 14, 15, 12],
         [17, 18, 19, 16],
         [21, 22, 23, 20]]], dtype=int32)>)

In [188]:
x = tf.range(24)
x = tf.reshape(x, (2, 3, 4))
x, tf.roll(x, shift=(-1, -1), axis=(-1, -2))

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 5,  6,  7,  4],
         [ 9, 10, 11,  8],
         [ 1,  2,  3,  0]],
 
        [[17, 18, 19, 16],
         [21, 22, 23, 20],
         [13, 14, 15, 12]]], dtype=int32)>)

In [189]:
x = np.arange(1, 7)
s = tf.scan(lambda i, el:  el, x)
x, s

(array([1, 2, 3, 4, 5, 6]),
 <tf.Tensor: shape=(6,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6])>)

In [190]:
x = np.arange(1, 7)
s = tf.scan(lambda i, el:  i, x, initializer=np.array(0))
x, s

(array([1, 2, 3, 4, 5, 6]),
 <tf.Tensor: shape=(6,), dtype=int64, numpy=array([0, 0, 0, 0, 0, 0])>)

In [191]:
x = np.arange(1, 7)
x = np.expand_dims(x, 0)
x = np.tile(x, (2, 1))
x[1] *= 2
s = tf.scan(lambda i, el:  np.sum(el) , x, initializer=np.array(0))
x, s

(array([[ 1,  2,  3,  4,  5,  6],
        [ 2,  4,  6,  8, 10, 12]]),
 <tf.Tensor: shape=(2,), dtype=int64, numpy=array([21, 42])>)

In [192]:
x = np.arange(1, 7)
x = np.expand_dims(x, 0)
x = np.tile(x, (2, 1))
x[1] *= 10 
s = tf.scan(lambda i, el: el[0]  , x, initializer=np.array(0))
x, s

(array([[ 1,  2,  3,  4,  5,  6],
        [10, 20, 30, 40, 50, 60]]),
 <tf.Tensor: shape=(2,), dtype=int64, numpy=array([ 1, 10])>)

In [193]:
x = tf.constant([4, 4])
ind = tf.constant([[0, 1], [1, 2]])
updates = tf.constant([-1, -2])
x, tf.scatter_nd(indices=ind, updates=updates, shape=x)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 4], dtype=int32)>,
 <tf.Tensor: shape=(4, 4), dtype=int32, numpy=
 array([[ 0, -1,  0,  0],
        [ 0,  0, -2,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]], dtype=int32)>)

In [194]:
x = tf.constant([3, 4, 4])
ind = tf.constant([[0, 1, 1]])
updates = tf.constant([-1])
x, tf.scatter_nd(indices=ind, updates=updates, shape=x)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 4], dtype=int32)>,
 <tf.Tensor: shape=(3, 4, 4), dtype=int32, numpy=
 array([[[ 0,  0,  0,  0],
         [ 0, -1,  0,  0],
         [ 0,  0,  0,  0],
         [ 0,  0,  0,  0]],
 
        [[ 0,  0,  0,  0],
         [ 0,  0,  0,  0],
         [ 0,  0,  0,  0],
         [ 0,  0,  0,  0]],
 
        [[ 0,  0,  0,  0],
         [ 0,  0,  0,  0],
         [ 0,  0,  0,  0],
         [ 0,  0,  0,  0]]], dtype=int32)>)

In [195]:
x = tf.constant([3, 4, 4])
ind = tf.constant([[1]])
updates = tf.constant(tf.fill((1, 4, 4), 1))
x, updates, tf.scatter_nd(indices=ind, updates=updates, shape=x)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 4], dtype=int32)>,
 <tf.Tensor: shape=(1, 4, 4), dtype=int32, numpy=
 array([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 4, 4), dtype=int32, numpy=
 array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]], dtype=int32)>)

In [196]:
x = tf.constant([3, 4, 4])
ind = tf.constant([[2]])
updates = tf.constant(tf.fill((1, 4, 4), 1))
x, updates, tf.scatter_nd(indices=ind, updates=updates, shape=x)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 4], dtype=int32)>,
 <tf.Tensor: shape=(1, 4, 4), dtype=int32, numpy=
 array([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 4, 4), dtype=int32, numpy=
 array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=int32)>)

In [197]:
x = tf.constant([3, 4, 4])
ind = tf.constant([[2], [0]])
updates = tf.Variable(tf.fill((2, 4, 4), 1))
updates[-1].assign(-1)
x, updates, tf.scatter_nd(indices=ind, updates=updates, shape=x)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 4], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2, 4, 4) dtype=int32, numpy=
 array([[[ 1,  1,  1,  1],
         [ 1,  1,  1,  1],
         [ 1,  1,  1,  1],
         [ 1,  1,  1,  1]],
 
        [[-1, -1, -1, -1],
         [-1, -1, -1, -1],
         [-1, -1, -1, -1],
         [-1, -1, -1, -1]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 4, 4), dtype=int32, numpy=
 array([[[-1, -1, -1, -1],
         [-1, -1, -1, -1],
         [-1, -1, -1, -1],
         [-1, -1, -1, -1]],
 
        [[ 0,  0,  0,  0],
         [ 0,  0,  0,  0],
         [ 0,  0,  0,  0],
         [ 0,  0,  0,  0]],
 
        [[ 1,  1,  1,  1],
         [ 1,  1,  1,  1],
         [ 1,  1,  1,  1],
         [ 1,  1,  1,  1]]], dtype=int32)>)

In [198]:
seq = [0, 3, 6, 9, 12]
values = [2, 3, 11]
tf.searchsorted(sorted_sequence=seq, values=values)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 1, 4], dtype=int32)>

In [199]:
seq = [0, 3, 6, 9, 12]
values = [2, 3, 11]
tf.searchsorted(sorted_sequence=seq, values=values, side="right")

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 4], dtype=int32)>

In [200]:
tf.sequence_mask([2, 4], 10)

<tf.Tensor: shape=(2, 10), dtype=bool, numpy=
array([[ True,  True, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True, False, False, False, False, False,
        False]])>

In [201]:
x, y, z = [get_random_tensor(size) for i, size in enumerate([(2, 4), (3, 5, 6), 4])]
tf.shape(x), tf.shape_n([x, y, z])

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>,
 [<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>,
  <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 6], dtype=int32)>,
  <tf.Tensor: shape=(1,), dtype=int32, numpy=array([4], dtype=int32)>])

In [202]:
x = tf.constant(tf.range(4*6), shape=(2, 2, 6))
x, tf.slice(x, [0, 0, 2], [1, 2, 1])

(<tf.Tensor: shape=(2, 2, 6), dtype=int32, numpy=
 array([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]],
 
        [[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2, 1), dtype=int32, numpy=
 array([[[2],
         [8]]], dtype=int32)>)

In [203]:
x = tf.constant(tf.range(8*8), shape=(8, 8))
x, tf.strided_slice(x, [0, 0,], [8, 8], strides=[2, 2])

(<tf.Tensor: shape=(8, 8), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]], dtype=int32)>,
 <tf.Tensor: shape=(4, 4), dtype=int32, numpy=
 array([[ 0,  2,  4,  6],
        [16, 18, 20, 22],
        [32, 34, 36, 38],
        [48, 50, 52, 54]], dtype=int32)>)

In [204]:
t = tf.ones((4, 5))
ind = tf.constant([[0, 1], [1, 1]])
updates = tf.constant([1, 2] , dtype=t.dtype)
t, tf.tensor_scatter_nd_add(tensor=t, indices=ind, updates=updates)

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[1., 2., 1., 1., 1.],
        [1., 3., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32)>)

In [205]:
t = tf.ones((4, 5))
ind = tf.constant([[0, 1], [1, 1], [0, 1]])
updates = tf.constant([1, 2, 1] , dtype=t.dtype)
t, tf.tensor_scatter_nd_add(tensor=t, indices=ind, updates=updates)

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[1., 3., 1., 1., 1.],
        [1., 3., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32)>)

In [206]:
t = tf.zeros((4, 5))
ind = tf.constant([[0], [0]])
updates = tf.constant([[1]*5, [1]*5] , dtype=t.dtype)
t, updates, tf.tensor_scatter_nd_add(tensor=t, indices=ind, updates=updates)

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[2., 2., 2., 2., 2.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32)>)

In [207]:
t = tf.ones((4, 5))
ind = tf.constant([[0], [0]])
updates = tf.constant([[1, 3, 5, 2, 0], [3, 10, 5, 17, -1]] , dtype=t.dtype)
t, updates, tf.tensor_scatter_nd_max(tensor=t, indices=ind, updates=updates)

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[ 1.,  3.,  5.,  2.,  0.],
        [ 3., 10.,  5., 17., -1.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[ 3., 10.,  5., 17.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]], dtype=float32)>)

In [208]:
t = tf.ones((4, 5))
ind = tf.constant([[0], [0]])
updates = tf.constant([[1, 3, 5, 2, 0], [3, 10, 5, 17, -1]] , dtype=t.dtype)
t, updates, tf.tensor_scatter_nd_min(tensor=t, indices=ind, updates=updates)

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[ 1.,  3.,  5.,  2.,  0.],
        [ 3., 10.,  5., 17., -1.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[ 1.,  1.,  1.,  1., -1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]], dtype=float32)>)

In [209]:
t = tf.ones((4, 5))
ind = tf.constant([[0], [0]])
updates = tf.constant([[1, 3, 5, 2, 0], [3, 10, 5, 17, -1]] , dtype=t.dtype)
t, updates, tf.tensor_scatter_nd_update(tensor=t, indices=ind, updates=updates)

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[ 1.,  3.,  5.,  2.,  0.],
        [ 3., 10.,  5., 17., -1.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[1., 3., 5., 2., 0.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32)>)

In [210]:
t = tf.ones((4, 5))
ind = tf.constant([[0], [1]])
updates = tf.constant([[1, 3, 5, 2, 0], [3, 10, 5, 17, -1]] , dtype=t.dtype)
t, updates, tf.tensor_scatter_nd_update(tensor=t, indices=ind, updates=updates)

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[ 1.,  3.,  5.,  2.,  0.],
        [ 3., 10.,  5., 17., -1.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[ 1.,  3.,  5.,  2.,  0.],
        [ 3., 10.,  5., 17., -1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]], dtype=float32)>)

In [211]:
x = tf.constant(tf.range(2*4*5), shape=(2, 4, 5))
y = tf.constant(tf.range(2*4*5), shape=(4, 2, 5))
x, y, tf.tensordot(x, y, axes=([1, 0], [0, 1]))

(<tf.Tensor: shape=(2, 4, 5), dtype=int32, numpy=
 array([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],
 
        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]], dtype=int32)>,
 <tf.Tensor: shape=(4, 2, 5), dtype=int32, numpy=
 array([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],
 
        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],
 
        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],
 
        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]], dtype=int32)>,
 <tf.Tensor: shape=(5, 5), dtype=int32, numpy=
 array([[3150, 3290, 3430, 3570, 3710],
        [3290, 3438, 3586, 3734, 3882],
        [3430, 3586, 3742, 3898, 4054],
        [3570, 3734, 3898, 4062, 4226],
        [3710, 3882, 4054, 4226, 4398]], dtype=int32)>)

In [212]:
np.random.seed(0)
x = tf.constant(np.random.randint(0, 10, (10,)))
x, tf.unique(x)

(<tf.Tensor: shape=(10,), dtype=int64, numpy=array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])>,
 Unique(y=<tf.Tensor: shape=(7,), dtype=int64, numpy=array([5, 0, 3, 7, 9, 2, 4])>, idx=<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 2, 3, 4, 2, 0, 5, 6], dtype=int32)>))

In [213]:
np.random.seed(0)
x = tf.constant(np.random.randint(0, 10, (10,)))
x, tf.unique_with_counts(x)

(<tf.Tensor: shape=(10,), dtype=int64, numpy=array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])>,
 UniqueWithCounts(y=<tf.Tensor: shape=(7,), dtype=int64, numpy=array([5, 0, 3, 7, 9, 2, 4])>, idx=<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 2, 3, 4, 2, 0, 5, 6], dtype=int32)>, count=<tf.Tensor: shape=(7,), dtype=int32, numpy=array([2, 1, 3, 1, 1, 1, 1], dtype=int32)>))

In [214]:
np.random.seed(0)
x = tf.constant(np.random.randint(0, 10, (10,5)))
try:
    x, tf.unique_with_counts(x)
except Exception as e:
    print(e)

{{function_node __wrapped__UniqueWithCounts_device_/job:localhost/replica:0/task:0/device:GPU:0}} unique expects a 1D vector. [Op:UniqueWithCounts]


In [215]:
tf.unravel_index([5,], dims=[3, 4])

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [1]], dtype=int32)>

In [216]:
x = tf.constant(tf.range(4*5), shape=(4, 5))
x, tf.unravel_index([3, 0, 2, 5], dims=[3, 4])

(<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]], dtype=int32)>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[0, 0, 0, 1],
        [3, 0, 2, 1]], dtype=int32)>)

In [217]:
y = tf.ones(5, dtype=tf.int32)
def matmul(x):
    return tf.tensordot(x, y, axes=(0, 0))

x = tf.constant(tf.range(4*5), shape=(4, 5))
tf.vectorized_map(matmul, x), tf.matmul(x, tf.expand_dims(y, 1))

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 35, 60, 85], dtype=int32)>,
 <tf.Tensor: shape=(4, 1), dtype=int32, numpy=
 array([[10],
        [35],
        [60],
        [85]], dtype=int32)>)