In [1]:
%load_ext autoreload
%autoreload 2
import tensorflow as tf
import numpy as np
gpus = tf.config.experimental.list_physical_devices(device_type="GPU")
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

2024-01-04 08:49:28.245411: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-04 08:49:30.450949: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-04 08:49:30.471064: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-

In [2]:
ds = tf.data.Dataset.from_tensor_slices(tf.range(11))
ds

2024-01-04 08:58:09.334994: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-04 08:58:09.335330: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-04 08:58:09.335506: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [3]:
ds.as_numpy_iterator()

2024-01-04 08:58:26.705106: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [11]
	 [[{{node Placeholder/_0}}]]


In [4]:
list(ds.as_numpy_iterator())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
for i in ds:
    print(i)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)


In [6]:
for i in ds.batch(2):
    print(i)

tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([4 5], shape=(2,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)
tf.Tensor([10], shape=(1,), dtype=int32)


2024-01-04 08:59:14.422117: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [11]
	 [[{{node Placeholder/_0}}]]


In [10]:
for j, i in enumerate(ds.repeat().batch(2).take(20)):
    print(j, i)

0 tf.Tensor([0 1], shape=(2,), dtype=int32)
1 tf.Tensor([2 3], shape=(2,), dtype=int32)
2 tf.Tensor([4 5], shape=(2,), dtype=int32)
3 tf.Tensor([6 7], shape=(2,), dtype=int32)
4 tf.Tensor([8 9], shape=(2,), dtype=int32)
5 tf.Tensor([10  0], shape=(2,), dtype=int32)
6 tf.Tensor([1 2], shape=(2,), dtype=int32)
7 tf.Tensor([3 4], shape=(2,), dtype=int32)
8 tf.Tensor([5 6], shape=(2,), dtype=int32)
9 tf.Tensor([7 8], shape=(2,), dtype=int32)
10 tf.Tensor([ 9 10], shape=(2,), dtype=int32)
11 tf.Tensor([0 1], shape=(2,), dtype=int32)
12 tf.Tensor([2 3], shape=(2,), dtype=int32)
13 tf.Tensor([4 5], shape=(2,), dtype=int32)
14 tf.Tensor([6 7], shape=(2,), dtype=int32)
15 tf.Tensor([8 9], shape=(2,), dtype=int32)
16 tf.Tensor([10  0], shape=(2,), dtype=int32)
17 tf.Tensor([1 2], shape=(2,), dtype=int32)
18 tf.Tensor([3 4], shape=(2,), dtype=int32)
19 tf.Tensor([5 6], shape=(2,), dtype=int32)


2024-01-04 09:00:47.058054: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [11]
	 [[{{node Placeholder/_0}}]]


In [11]:
for j, i in enumerate(ds.batch(2).repeat().take(20)):
    print(j, i)

0 tf.Tensor([0 1], shape=(2,), dtype=int32)
1 tf.Tensor([2 3], shape=(2,), dtype=int32)
2 tf.Tensor([4 5], shape=(2,), dtype=int32)
3 tf.Tensor([6 7], shape=(2,), dtype=int32)
4 tf.Tensor([8 9], shape=(2,), dtype=int32)
5 tf.Tensor([10], shape=(1,), dtype=int32)
6 tf.Tensor([0 1], shape=(2,), dtype=int32)
7 tf.Tensor([2 3], shape=(2,), dtype=int32)
8 tf.Tensor([4 5], shape=(2,), dtype=int32)
9 tf.Tensor([6 7], shape=(2,), dtype=int32)
10 tf.Tensor([8 9], shape=(2,), dtype=int32)
11 tf.Tensor([10], shape=(1,), dtype=int32)
12 tf.Tensor([0 1], shape=(2,), dtype=int32)
13 tf.Tensor([2 3], shape=(2,), dtype=int32)
14 tf.Tensor([4 5], shape=(2,), dtype=int32)
15 tf.Tensor([6 7], shape=(2,), dtype=int32)
16 tf.Tensor([8 9], shape=(2,), dtype=int32)
17 tf.Tensor([10], shape=(1,), dtype=int32)
18 tf.Tensor([0 1], shape=(2,), dtype=int32)
19 tf.Tensor([2 3], shape=(2,), dtype=int32)


2024-01-04 09:01:23.905799: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [11]
	 [[{{node Placeholder/_0}}]]


In [29]:
ds = tf.data.Dataset.from_tensor_slices(tf.constant(tf.range(50*2*6), shape=(50, 2, 6)))

In [30]:
next(iter(ds))

2024-01-04 09:09:08.232752: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [50,2,6]
	 [[{{node Placeholder/_0}}]]


<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]], dtype=int32)>

In [31]:
for k, el in ds.enumerate(start=1).take(3):
    print(k, el)

tf.Tensor(1, shape=(), dtype=int64) tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]], shape=(2, 6), dtype=int32)
tf.Tensor(2, shape=(), dtype=int64) tf.Tensor(
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]], shape=(2, 6), dtype=int32)
tf.Tensor(3, shape=(), dtype=int64) tf.Tensor(
[[24 25 26 27 28 29]
 [30 31 32 33 34 35]], shape=(2, 6), dtype=int32)


2024-01-04 09:09:08.467596: I tensorflow/core/grappler/optimizers/data/replicate_on_split.cc:32] Running replicate on split optimization
2024-01-04 09:09:08.469332: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_4' with dtype int32 and shape [50,2,6]
	 [[{{node Placeholder/_4}}]]
2024-01-04 09:09:08.469490: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_4' with dtype int32 and shape [50,2,6]
	 [[{{node Placeholder/_4}}]]


In [38]:
for el in ds.batch(3).take(3):
    print(el)
    print("-" * 50)

tf.Tensor(
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]], shape=(3, 2, 6), dtype=int32)
--------------------------------------------------
tf.Tensor(
[[[36 37 38 39 40 41]
  [42 43 44 45 46 47]]

 [[48 49 50 51 52 53]
  [54 55 56 57 58 59]]

 [[60 61 62 63 64 65]
  [66 67 68 69 70 71]]], shape=(3, 2, 6), dtype=int32)
--------------------------------------------------
tf.Tensor(
[[[ 72  73  74  75  76  77]
  [ 78  79  80  81  82  83]]

 [[ 84  85  86  87  88  89]
  [ 90  91  92  93  94  95]]

 [[ 96  97  98  99 100 101]
  [102 103 104 105 106 107]]], shape=(3, 2, 6), dtype=int32)
--------------------------------------------------


2024-01-04 09:10:56.785372: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [50,2,6]
	 [[{{node Placeholder/_0}}]]
2024-01-04 09:10:56.785549: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [50,2,6]
	 [[{{node Placeholder/_0}}]]


In [37]:
for el in ds.batch(3).map(lambda x: x[0]).take(3):
    print(el)
    print("-" * 50)

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]], shape=(2, 6), dtype=int32)
--------------------------------------------------
tf.Tensor(
[[36 37 38 39 40 41]
 [42 43 44 45 46 47]], shape=(2, 6), dtype=int32)
--------------------------------------------------
tf.Tensor(
[[72 73 74 75 76 77]
 [78 79 80 81 82 83]], shape=(2, 6), dtype=int32)
--------------------------------------------------


2024-01-04 09:10:30.818509: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [50,2,6]
	 [[{{node Placeholder/_0}}]]
2024-01-04 09:10:30.818689: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [50,2,6]
	 [[{{node Placeholder/_0}}]]


In [42]:
for el in ds.batch(3).flat_map( lambda x: tf.data.Dataset.from_tensor_slices(x)).take(3):
    print(el)
    print("-" * 50)

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]], shape=(2, 6), dtype=int32)
--------------------------------------------------
tf.Tensor(
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]], shape=(2, 6), dtype=int32)
--------------------------------------------------
tf.Tensor(
[[24 25 26 27 28 29]
 [30 31 32 33 34 35]], shape=(2, 6), dtype=int32)
--------------------------------------------------


2024-01-04 09:14:13.251407: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [50,2,6]
	 [[{{node Placeholder/_0}}]]
2024-01-04 09:14:13.251557: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [50,2,6]
	 [[{{node Placeholder/_0}}]]


In [43]:
list(tf.data.Dataset.range(0, 10).as_numpy_iterator())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
list(tf.data.Dataset.range(0, 10).shuffle(5, seed=5).as_numpy_iterator())

[0, 2, 1, 7, 8, 6, 3, 5, 9, 4]

In [58]:
ds1 = tf.data.Dataset.range(10, 20)
ds2 = tf.data.Dataset.range(20, 30)
ds3 = tf.data.Dataset.range(30, 40)
ds4 = tf.data.Dataset.range(40, 50)
ds5 = tf.data.Dataset.range(50, 60)

In [59]:
ds1.cardinality()

<tf.Tensor: shape=(), dtype=int64, numpy=10>

In [66]:
ds = tf.data.Dataset.from_tensor_slices([ds1, ds2, ds3, ds4, ds5])

In [67]:
ds = ds.interleave(lambda x: x, 2, block_length=4).batch(6, drop_remainder=True)

In [68]:
for el in ds.as_numpy_iterator():
    print(el)
    print("------")

[10 11 12 13 20 21]
------
[22 23 14 15 16 17]
------
[24 25 26 27 18 19]
------
[28 29 30 31 32 33]
------
[40 41 42 43 34 35]
------
[36 37 44 45 46 47]
------
[38 39 48 49 50 51]
------
[52 53 54 55 56 57]
------


2024-01-04 10:24:20.047607: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype variant and shape [5]
	 [[{{node Placeholder/_0}}]]


In [69]:
ds.element_spec

TensorSpec(shape=(6,), dtype=tf.int64, name=None)

In [73]:
ds = ds1.concatenate(ds2)

In [74]:
for k in ds.batch(4):
    print(k)

tf.Tensor([10 11 12 13], shape=(4,), dtype=int64)
tf.Tensor([14 15 16 17], shape=(4,), dtype=int64)
tf.Tensor([18 19 20 21], shape=(4,), dtype=int64)
tf.Tensor([22 23 24 25], shape=(4,), dtype=int64)
tf.Tensor([26 27 28 29], shape=(4,), dtype=int64)


In [83]:
ds = tf.data.Dataset.range(1, 5)
ds = ds.map(lambda x: tf.fill([x], x))
for el in ds:
    print(el)

tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2 2], shape=(2,), dtype=int64)
tf.Tensor([3 3 3], shape=(3,), dtype=int64)
tf.Tensor([4 4 4 4], shape=(4,), dtype=int64)


2024-01-04 10:29:54.584625: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'args_0' with dtype int64
	 [[{{node args_0}}]]


In [84]:
ds = ds.padded_batch(1, (4, ), padding_values=tf.constant(-1, dtype=ds.element_spec.dtype))

In [85]:
for el in ds:
    print(el)

tf.Tensor([[ 1 -1 -1 -1]], shape=(1, 4), dtype=int64)
tf.Tensor([[ 2  2 -1 -1]], shape=(1, 4), dtype=int64)
tf.Tensor([[ 3  3  3 -1]], shape=(1, 4), dtype=int64)
tf.Tensor([[4 4 4 4]], shape=(1, 4), dtype=int64)


In [88]:
for el in ds.skip(2):
    print(el)

tf.Tensor([[ 3  3  3 -1]], shape=(1, 4), dtype=int64)
tf.Tensor([[4 4 4 4]], shape=(1, 4), dtype=int64)


In [98]:
ds = tf.data.Dataset.range(4 * 10).window(3)
for el in ds:
    print([k.numpy() for k in el])

[0, 1, 2]
[3, 4, 5]
[6, 7, 8]
[9, 10, 11]
[12, 13, 14]
[15, 16, 17]
[18, 19, 20]
[21, 22, 23]
[24, 25, 26]
[27, 28, 29]
[30, 31, 32]
[33, 34, 35]
[36, 37, 38]
[39]


2024-01-04 10:38:29.038759: W tensorflow/core/framework/dataset.cc:807] Input of Window will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.
2024-01-04 10:38:29.038919: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype variant
	 [[{{node Placeholder/_0}}]]
2024-01-04 10:38:29.042020: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype variant
	 [[{{node Placeholder/_0}}]]
2024-01-04 10:38:29.045164: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting 

In [99]:
ds = tf.data.Dataset.range(4 * 10).window(3, shift=1)
for el in ds:
    print([k.numpy() for k in el])

[0, 1, 2]
[1, 2, 3]
[2, 3, 4]
[3, 4, 5]
[4, 5, 6]
[5, 6, 7]
[6, 7, 8]
[7, 8, 9]
[8, 9, 10]
[9, 10, 11]
[10, 11, 12]
[11, 12, 13]
[12, 13, 14]
[13, 14, 15]
[14, 15, 16]
[15, 16, 17]
[16, 17, 18]
[17, 18, 19]
[18, 19, 20]
[19, 20, 21]
[20, 21, 22]
[21, 22, 23]
[22, 23, 24]
[23, 24, 25]
[24, 25, 26]
[25, 26, 27]
[26, 27, 28]
[27, 28, 29]
[28, 29, 30]
[29, 30, 31]
[30, 31, 32]
[31, 32, 33]
[32, 33, 34]
[33, 34, 35]
[34, 35, 36]
[35, 36, 37]
[36, 37, 38]
[37, 38, 39]
[38, 39]
[39]


2024-01-04 10:39:07.265760: W tensorflow/core/framework/dataset.cc:807] Input of Window will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.
2024-01-04 10:39:07.265952: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype variant
	 [[{{node Placeholder/_0}}]]
2024-01-04 10:39:07.268947: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype variant
	 [[{{node Placeholder/_0}}]]
2024-01-04 10:39:07.271736: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting 

In [102]:
ds = tf.data.Dataset.range(4 * 10).window(3, shift=1, stride=2)
for el in ds:
    print([k.numpy() for k in el])

[0, 2, 4]
[1, 3, 5]
[2, 4, 6]
[3, 5, 7]
[4, 6, 8]
[5, 7, 9]
[6, 8, 10]
[7, 9, 11]
[8, 10, 12]
[9, 11, 13]
[10, 12, 14]
[11, 13, 15]
[12, 14, 16]
[13, 15, 17]
[14, 16, 18]
[15, 17, 19]
[16, 18, 20]
[17, 19, 21]
[18, 20, 22]
[19, 21, 23]
[20, 22, 24]
[21, 23, 25]
[22, 24, 26]
[23, 25, 27]
[24, 26, 28]
[25, 27, 29]
[26, 28, 30]
[27, 29, 31]
[28, 30, 32]
[29, 31, 33]
[30, 32, 34]
[31, 33, 35]
[32, 34, 36]
[33, 35, 37]
[34, 36, 38]
[35, 37, 39]
[36, 38]
[37, 39]
[38]
[39]


2024-01-04 10:39:43.656054: W tensorflow/core/framework/dataset.cc:807] Input of Window will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.
2024-01-04 10:39:43.656254: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype variant
	 [[{{node Placeholder/_0}}]]
2024-01-04 10:39:43.660019: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype variant
	 [[{{node Placeholder/_0}}]]
2024-01-04 10:39:43.666108: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting 