In [1]:
import torch
import numpy as np
import array
import math
from torch import nn


In [2]:
math.ceil(-2.2)

-2

In [3]:
torch.arange(10)[None, None, :]

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [4]:
net = nn.LazyLinear(256)

/home/mtb/env/lib/python3.9/site-packages/torch/nn/modules/lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [5]:
net.weight.size()

torch.Size([0])

In [6]:
x = torch.randn((10, 30))

In [7]:
y = net(x)

In [8]:
y.shape

torch.Size([10, 256])

In [9]:
net.weight.shape

torch.Size([256, 30])

In [10]:
x.to(device='cuda:0') 

tensor([[ 3.0911e-01, -1.0789e+00,  1.0737e-01, -1.3498e+00,  1.5476e-01,
         -1.1084e+00, -3.4560e-01,  4.6330e-01, -9.8335e-01,  6.4840e-01,
         -6.5192e-02, -1.3707e-01, -7.1245e-01, -7.7227e-01,  1.9990e+00,
          5.1117e-01, -2.1491e-01,  9.6488e-01, -1.5871e+00, -3.1419e-01,
          1.8360e+00,  1.0339e+00,  3.7070e-01,  7.2553e-01,  6.3298e-01,
          5.4931e-01, -8.1978e-01, -7.5271e-01, -1.0334e+00,  1.0417e+00],
        [ 1.1480e+00,  1.2092e-01, -6.4100e-01, -1.7866e+00,  2.3195e-02,
         -3.3704e-01, -2.0448e+00, -8.8505e-01,  1.8044e+00,  1.1934e+00,
         -1.5795e-01, -8.5402e-01, -8.6426e-01,  1.8778e+00,  7.1888e-01,
         -2.8875e-01, -6.6242e-01,  3.3368e-01,  1.3396e-01, -9.5222e-01,
          1.0995e+00, -1.4410e+00, -1.0610e+00, -6.4639e-01, -4.2257e-01,
          6.8144e-01,  1.4082e+00, -1.0659e+00,  2.5271e-01,  1.2011e+00],
        [ 4.6962e-01,  5.8273e-01,  1.4306e-01,  1.6111e+00, -1.9799e-01,
          3.1544e-01,  2.9356e-01,  

In [11]:
x.device

device(type='cpu')

In [12]:
torch.manual_seed(10)
x = torch.empty((10, 5000)).uniform_(-4, 4)

In [13]:
y = x.clone()

In [14]:
torch.normal(0., 1., size=(10, 5000))

tensor([[-0.3695,  0.2178, -0.8544,  ..., -0.5767,  0.0687,  0.9357],
        [ 0.7685, -1.7597, -0.5440,  ...,  0.0067, -0.1785, -0.2007],
        [-1.3787,  1.0032,  1.5139,  ..., -0.0311, -0.7310, -0.7357],
        ...,
        [-0.6211,  1.6740,  1.3860,  ..., -0.3418, -0.1636, -0.1092],
        [ 1.5157, -0.0277,  0.8166,  ...,  1.1793,  0.7833, -0.5789],
        [-0.3016,  1.0526,  0.3381,  ..., -0.3096,  0.3056, -1.4316]])

In [15]:
x.normal_(0, 1)

tensor([[ 0.3510,  1.1682,  1.3972,  ..., -0.5403, -1.8046,  1.1958],
        [ 1.4531, -0.5814, -0.5592,  ..., -2.4647,  0.2427, -0.5404],
        [ 0.0337,  0.9904, -0.9932,  ..., -2.0111, -0.2497,  1.1261],
        ...,
        [-0.3714,  1.3240, -0.1600,  ..., -1.9292,  1.6265,  0.3676],
        [ 0.6357,  0.2587,  0.5304,  ..., -1.2510,  0.8620,  1.0873],
        [ 0.4514, -0.1732,  0.4199,  ...,  0.6106,  1.2206, -1.0866]])

In [16]:
x.normal_(0, 1)

tensor([[ 0.3887, -0.0518, -0.6590,  ..., -0.3228,  0.7122, -1.4934],
        [ 1.3387,  2.3876,  0.5639,  ...,  0.8801, -0.1235, -0.5796],
        [ 1.4232, -0.8363,  0.4545,  ...,  0.4513, -0.0427, -0.6412],
        ...,
        [ 0.0268,  0.0838, -0.0644,  ...,  0.5830, -0.5323, -0.2533],
        [ 0.1744,  0.6938, -0.6699,  ..., -0.5077, -0.0810,  0.5587],
        [ 0.1309,  0.6458,  1.9199,  ...,  0.8345, -1.2508,  0.6531]])

In [17]:
x

tensor([[ 0.3887, -0.0518, -0.6590,  ..., -0.3228,  0.7122, -1.4934],
        [ 1.3387,  2.3876,  0.5639,  ...,  0.8801, -0.1235, -0.5796],
        [ 1.4232, -0.8363,  0.4545,  ...,  0.4513, -0.0427, -0.6412],
        ...,
        [ 0.0268,  0.0838, -0.0644,  ...,  0.5830, -0.5323, -0.2533],
        [ 0.1744,  0.6938, -0.6699,  ..., -0.5077, -0.0810,  0.5587],
        [ 0.1309,  0.6458,  1.9199,  ...,  0.8345, -1.2508,  0.6531]])

In [18]:
x.sum((-1)) / 5000

tensor([ 0.0124, -0.0021,  0.0146, -0.0086,  0.0119, -0.0051,  0.0012,  0.0191,
         0.0050,  0.0265])

In [19]:
y - y.mean(axis=(1, ), keepdim=True), y -  y.sum() / 50000

(tensor([[-0.3817, -0.1835, -1.5463,  ..., -2.1051, -1.2046,  3.5418],
         [ 3.8134,  2.7599, -3.0942,  ..., -3.6861,  3.3261, -3.9601],
         [-2.9215, -3.5598, -2.8361,  ..., -3.5278,  0.1972, -0.7693],
         ...,
         [-0.8184, -3.0790,  2.2531,  ..., -3.7783, -3.3329,  1.3009],
         [ 3.3563,  1.7762,  0.0914,  ...,  0.9927,  1.0587, -1.5650],
         [ 3.8360,  0.8514, -2.5571,  ...,  3.6733,  0.1638,  2.8013]]),
 tensor([[-0.3500, -0.1518, -1.5146,  ..., -2.0734, -1.1729,  3.5735],
         [ 3.7703,  2.7168, -3.1373,  ..., -3.7292,  3.2830, -4.0032],
         [-2.9363, -3.5746, -2.8509,  ..., -3.5426,  0.1824, -0.7841],
         ...,
         [-0.7874, -3.0481,  2.2840,  ..., -3.7473, -3.3019,  1.3318],
         [ 3.3932,  1.8130,  0.1283,  ...,  1.0296,  1.0956, -1.5282],
         [ 3.8346,  0.8500, -2.5585,  ...,  3.6719,  0.1623,  2.7999]]))

In [20]:
z = y.sum(axis=-1, keepdim=True) / 5000

In [21]:
w = y - z

In [22]:
w.mean(axis=(-1))

tensor([ 5.7602e-08, -7.6294e-08,  1.2207e-08,  2.1362e-08, -3.3569e-08,
        -3.0518e-08, -5.2643e-08,  4.5776e-08,  4.5776e-08,  2.5177e-08])

In [23]:
w + 2

tensor([[ 1.6183,  1.8165,  0.4537,  ..., -0.1051,  0.7954,  5.5418],
        [ 5.8134,  4.7599, -1.0942,  ..., -1.6861,  5.3261, -1.9601],
        [-0.9215, -1.5598, -0.8361,  ..., -1.5278,  2.1972,  1.2307],
        ...,
        [ 1.1816, -1.0790,  4.2531,  ..., -1.7783, -1.3329,  3.3009],
        [ 5.3563,  3.7762,  2.0914,  ...,  2.9927,  3.0587,  0.4350],
        [ 5.8360,  2.8514, -0.5571,  ...,  5.6733,  2.1638,  4.8013]])

In [24]:
torch.manual_seed(10)
x = torch.empty((10, 5, 10, 5000)).uniform_(-4, 4)

In [25]:
x.mean(axis=(-1, -2))

tensor([[ 0.0146,  0.0002, -0.0002, -0.0103,  0.0040],
        [ 0.0043, -0.0058,  0.0041,  0.0007,  0.0131],
        [-0.0122,  0.0037, -0.0264, -0.0108, -0.0075],
        [ 0.0198, -0.0003, -0.0140,  0.0062, -0.0056],
        [-0.0018,  0.0028,  0.0114, -0.0059, -0.0080],
        [ 0.0002, -0.0061, -0.0109, -0.0079, -0.0001],
        [ 0.0123, -0.0162,  0.0010,  0.0027, -0.0017],
        [-0.0154, -0.0113, -0.0122,  0.0016, -0.0126],
        [ 0.0298,  0.0111, -0.0063,  0.0095, -0.0102],
        [-0.0012,  0.0038, -0.0087,  0.0119, -0.0023]])

MLP

In [26]:
net = nn.Linear(4, 10)

In [27]:
x = torch.randn(2, 4)

In [28]:
y = net(x)
y.shape

torch.Size([2, 10])

In [29]:
y

tensor([[-0.5986,  0.2001,  1.2537,  0.5834, -0.5716,  0.2312,  0.0540,  0.0463,
         -0.3411,  0.3042],
        [-0.4324,  0.1083, -0.6668, -0.4291, -0.7299, -0.0870, -1.0466,  0.3723,
         -0.6390, -0.0645]], grad_fn=<AddmmBackward0>)

In [30]:
net.weight

Parameter containing:
tensor([[ 0.0322, -0.0182, -0.4234, -0.4418],
        [ 0.4645, -0.0485,  0.1915,  0.4401],
        [-0.2199,  0.2342, -0.1968,  0.4420],
        [-0.3294, -0.1101, -0.0606,  0.2784],
        [-0.4155,  0.4957, -0.1378, -0.4509],
        [-0.2811,  0.3955, -0.3359, -0.4654],
        [ 0.0860,  0.1035, -0.4661,  0.0312],
        [ 0.4474,  0.0618,  0.0999,  0.1228],
        [ 0.0265,  0.4594,  0.2514,  0.1779],
        [ 0.1866,  0.4216,  0.1418,  0.1924]], requires_grad=True)

In [31]:
net.weight.shape

torch.Size([10, 4])

In [32]:
torch.matmul(x, net.weight.T) + net.bias

tensor([[-0.5986,  0.2001,  1.2537,  0.5834, -0.5716,  0.2312,  0.0540,  0.0463,
         -0.3411,  0.3042],
        [-0.4324,  0.1083, -0.6668, -0.4291, -0.7299, -0.0870, -1.0466,  0.3723,
         -0.6390, -0.0645]], grad_fn=<AddBackward0>)

In [33]:
torch.einsum('bj, ij -> bi', x, net.weight) + net.bias

tensor([[-0.5986,  0.2001,  1.2537,  0.5834, -0.5716,  0.2312,  0.0540,  0.0463,
         -0.3411,  0.3042],
        [-0.4324,  0.1083, -0.6668, -0.4291, -0.7299, -0.0870, -1.0466,  0.3723,
         -0.6390, -0.0645]], grad_fn=<AddBackward0>)

In [34]:
import torch.nn.functional as F

In [35]:
F.linear(x, net.weight, net.bias)

tensor([[-0.5986,  0.2001,  1.2537,  0.5834, -0.5716,  0.2312,  0.0540,  0.0463,
         -0.3411,  0.3042],
        [-0.4324,  0.1083, -0.6668, -0.4291, -0.7299, -0.0870, -1.0466,  0.3723,
         -0.6390, -0.0645]], grad_fn=<AddmmBackward0>)

In [36]:
torch.manual_seed(42)
net = nn.Sequential()
net.add_module('lin1', nn.Linear(32, 64))
net.add_module('lin2', nn.Linear(64, 10))

In [37]:
x = torch.randn((4, 32))

In [38]:
y = net(x)
y[0], y.shape


(tensor([-0.0630, -0.0022, -0.0127, -0.3661,  0.0866,  0.0741,  0.0963,  0.1773,
         -0.0797,  0.3435], grad_fn=<SelectBackward0>),
 torch.Size([4, 10]))

In [39]:
z = net.lin2(net.lin1(x))
z[0]

tensor([-0.0630, -0.0022, -0.0127, -0.3661,  0.0866,  0.0741,  0.0963,  0.1773,
        -0.0797,  0.3435], grad_fn=<SelectBackward0>)

In [40]:
net.state_dict().keys()

odict_keys(['lin1.weight', 'lin1.bias', 'lin2.weight', 'lin2.bias'])

In [41]:
x = torch.randn(20, 10, 4, 32)
y = net(x)
y.shape

torch.Size([20, 10, 4, 10])

In [42]:
x = torch.empty((4, 5)).uniform_(-10, 10)

In [43]:
x

tensor([[ 9.6053,  6.1465, -3.9468, -6.8474,  6.5705],
        [ 7.9896,  7.8190, -2.3512,  7.2122,  8.1273],
        [ 7.9416,  9.6219, -9.1863,  9.3812,  7.5133],
        [ 2.9351,  5.0090,  1.0653, -6.3083,  4.4218]])

In [44]:
bn = nn.BatchNorm1d(x.shape[1])
y = bn(x)

In [45]:
bn.weight, bn.bias, bn.weight.shape, bn.bias.size()

(Parameter containing:
 tensor([1., 1., 1., 1., 1.], requires_grad=True),
 Parameter containing:
 tensor([0., 0., 0., 0., 0.], requires_grad=True),
 torch.Size([5]),
 torch.Size([5]))

In [46]:
y, y.mean(dim=0), y.std(0)

(tensor([[ 0.9926, -0.5753, -0.0925, -1.0304, -0.0625],
         [ 0.3478,  0.3844,  0.3391,  0.8494,  1.0455],
         [ 0.3287,  1.4189, -1.5100,  1.1394,  0.6085],
         [-1.6691, -1.2280,  1.2634, -0.9584, -1.5915]],
        grad_fn=<NativeBatchNormBackward0>),
 tensor([ 5.9605e-08,  5.9605e-08,  5.9605e-08, -1.4901e-08, -1.4901e-07],
        grad_fn=<MeanBackward1>),
 tensor([1.1547, 1.1547, 1.1547, 1.1547, 1.1547], grad_fn=<StdBackward0>))

In [47]:
x.mean(dim=0)

tensor([ 7.1179,  7.1491, -3.6047,  0.8594,  6.6582])

In [48]:
(x - x.mean(dim=0)) / (x.std(dim=0) + 1e-9)

tensor([[ 0.8596, -0.4982, -0.0801, -0.8924, -0.0541],
        [ 0.3012,  0.3329,  0.2937,  0.7356,  0.9054],
        [ 0.2846,  1.2288, -1.3077,  0.9868,  0.5270],
        [-1.4455, -1.0635,  1.0942, -0.8300, -1.3783]])

In [49]:
x = torch.randint(0, 4, (3, 2, 4))
x

tensor([[[3, 3, 3, 1],
         [3, 1, 1, 3]],

        [[0, 0, 2, 3],
         [2, 3, 2, 1]],

        [[3, 0, 3, 2],
         [2, 2, 2, 2]]])

In [51]:
x.shape, F.one_hot(x, 6).shape, F.one_hot(x, 6)

(torch.Size([3, 2, 4]),
 torch.Size([3, 2, 4, 6]),
 tensor([[[[0, 0, 0, 1, 0, 0],
           [0, 0, 0, 1, 0, 0],
           [0, 0, 0, 1, 0, 0],
           [0, 1, 0, 0, 0, 0]],
 
          [[0, 0, 0, 1, 0, 0],
           [0, 1, 0, 0, 0, 0],
           [0, 1, 0, 0, 0, 0],
           [0, 0, 0, 1, 0, 0]]],
 
 
         [[[1, 0, 0, 0, 0, 0],
           [1, 0, 0, 0, 0, 0],
           [0, 0, 1, 0, 0, 0],
           [0, 0, 0, 1, 0, 0]],
 
          [[0, 0, 1, 0, 0, 0],
           [0, 0, 0, 1, 0, 0],
           [0, 0, 1, 0, 0, 0],
           [0, 1, 0, 0, 0, 0]]],
 
 
         [[[0, 0, 0, 1, 0, 0],
           [1, 0, 0, 0, 0, 0],
           [0, 0, 0, 1, 0, 0],
           [0, 0, 1, 0, 0, 0]],
 
          [[0, 0, 1, 0, 0, 0],
           [0, 0, 1, 0, 0, 0],
           [0, 0, 1, 0, 0, 0],
           [0, 0, 1, 0, 0, 0]]]]))

In [56]:
input = torch.normal(4, 10, size=(10, )).requires_grad_()

In [57]:
input

tensor([12.7321,  5.6809,  9.2964, 14.9853, -3.7835,  3.7777,  5.0353, -3.6466,
        -2.5364, 12.3880], requires_grad=True)

In [89]:
target = torch.randint(0, 2, size=input.size(), dtype=torch.float).requires_grad_()
target

tensor([0., 1., 1., 0., 1., 0., 1., 0., 0., 1.], requires_grad=True)

In [90]:
target

tensor([0., 1., 1., 0., 1., 0., 1., 0., 0., 1.], requires_grad=True)

In [94]:
F.binary_cross_entropy(F.sigmoid(input), target, reduce=None)

/home/mtb/env/lib/python3.9/site-packages/torch/nn/functional.py:1960: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


tensor(3.5285, grad_fn=<BinaryCrossEntropyBackward0>)

In [92]:
def binary_cross_entropy(input, target):
    mu = nn.Sigmoid()(input)
    
    loss = target * torch.log(mu) + (1 - target) * torch.log( 1 - mu)
    
    return -loss.mean()
    
binary_cross_entropy(input, target)
    

tensor(3.5285, grad_fn=<NegBackward0>)

In [95]:
target = torch.empty_like(target).uniform_(0, 1).requires_grad_()

In [96]:
target

tensor([0.6049, 0.8155, 0.2100, 0.4384, 0.0345, 0.9598, 0.2903, 0.3734, 0.9725,
        0.0572], requires_grad=True)

In [97]:
F.binary_cross_entropy(F.sigmoid(input), target, reduce=None)

/home/mtb/env/lib/python3.9/site-packages/torch/nn/functional.py:1960: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


tensor(4.1276, grad_fn=<BinaryCrossEntropyBackward0>)

In [99]:
binary_cross_entropy(input, target)

tensor(4.1276, grad_fn=<NegBackward0>)