In [2]:
import torch
import numpy as np
import array
import math
from torch import nn
import torch.nn.functional as F


In [3]:
from torch.optim import Adam

In [4]:
Adam

torch.optim.adam.Adam

In [5]:
math.ceil(-2.2)

-2

In [6]:
torch.arange(10)[None, None, :]

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [7]:
net = nn.LazyLinear(256)

/home/mtb/env/lib/python3.9/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [8]:
net.weight.size()

torch.Size([0])

In [9]:
x = torch.randn((10, 30))

In [10]:
y = net(x)

In [11]:
y.shape

torch.Size([10, 256])

In [12]:
net.weight.shape

torch.Size([256, 30])

In [13]:
x.to(device='cuda:0') 

tensor([[ 7.6156e-01,  2.2416e-01, -6.2062e-01,  4.0938e-01, -2.2079e-01,
         -9.5154e-01, -9.3815e-01,  8.2117e-01, -1.8201e+00, -1.4522e+00,
         -1.2727e-01, -1.1335e+00, -1.4772e+00, -1.2622e+00,  8.8334e-01,
         -4.3175e-01, -4.0975e-01,  4.5277e-01, -2.7047e-01,  2.0095e+00,
         -1.5936e+00,  1.4700e+00,  1.6986e+00, -1.2798e+00, -3.0017e+00,
         -5.9000e-01, -1.1693e-01,  4.5831e-01,  1.5630e+00, -1.5814e-01],
        [-1.1859e+00, -1.0206e-01, -1.0175e+00,  1.1703e+00,  3.5414e-01,
          1.6072e+00, -9.0198e-01, -6.3206e-01,  1.3173e+00,  7.3807e-01,
         -1.6103e-01,  2.1051e-01,  9.5457e-01, -5.1960e-01,  3.2614e-01,
         -1.0304e+00, -2.9474e-01,  1.0184e+00, -1.0407e+00, -2.1810e-01,
          1.2669e+00, -6.9635e-01,  1.0776e-01,  6.4657e-01, -2.9427e-01,
         -1.4450e+00,  4.0426e-01,  1.3840e+00, -8.1841e-01,  1.0840e+00],
        [ 2.8282e-01,  1.7083e-01,  1.9828e-02, -7.3426e-01,  2.1143e-01,
         -1.2155e+00,  5.0430e-01,  

In [14]:
x.device

device(type='cpu')

In [15]:
torch.manual_seed(10)
x = torch.empty((10, 5000)).uniform_(-4, 4)

In [16]:
y = x.clone()

In [17]:
torch.normal(0., 1., size=(10, 5000))

tensor([[-0.3695,  0.2178, -0.8544,  ..., -0.5767,  0.0687,  0.9357],
        [ 0.7685, -1.7597, -0.5440,  ...,  0.0067, -0.1785, -0.2007],
        [-1.3787,  1.0032,  1.5139,  ..., -0.0311, -0.7310, -0.7357],
        ...,
        [-0.6211,  1.6740,  1.3860,  ..., -0.3418, -0.1636, -0.1092],
        [ 1.5157, -0.0277,  0.8166,  ...,  1.1793,  0.7833, -0.5789],
        [-0.3016,  1.0526,  0.3381,  ..., -0.3096,  0.3056, -1.4316]])

In [18]:
x.normal_(0, 1)

tensor([[ 0.3510,  1.1682,  1.3972,  ..., -0.5403, -1.8046,  1.1958],
        [ 1.4531, -0.5814, -0.5592,  ..., -2.4647,  0.2427, -0.5404],
        [ 0.0337,  0.9904, -0.9932,  ..., -2.0111, -0.2497,  1.1261],
        ...,
        [-0.3714,  1.3240, -0.1600,  ..., -1.9292,  1.6265,  0.3676],
        [ 0.6357,  0.2587,  0.5304,  ..., -1.2510,  0.8620,  1.0873],
        [ 0.4514, -0.1732,  0.4199,  ...,  0.6106,  1.2206, -1.0866]])

In [19]:
x.normal_(0, 1)

tensor([[ 0.3887, -0.0518, -0.6590,  ..., -0.3228,  0.7122, -1.4934],
        [ 1.3387,  2.3876,  0.5639,  ...,  0.8801, -0.1235, -0.5796],
        [ 1.4232, -0.8363,  0.4545,  ...,  0.4513, -0.0427, -0.6412],
        ...,
        [ 0.0268,  0.0838, -0.0644,  ...,  0.5830, -0.5323, -0.2533],
        [ 0.1744,  0.6938, -0.6699,  ..., -0.5077, -0.0810,  0.5587],
        [ 0.1309,  0.6458,  1.9199,  ...,  0.8345, -1.2508,  0.6531]])

In [20]:
x

tensor([[ 0.3887, -0.0518, -0.6590,  ..., -0.3228,  0.7122, -1.4934],
        [ 1.3387,  2.3876,  0.5639,  ...,  0.8801, -0.1235, -0.5796],
        [ 1.4232, -0.8363,  0.4545,  ...,  0.4513, -0.0427, -0.6412],
        ...,
        [ 0.0268,  0.0838, -0.0644,  ...,  0.5830, -0.5323, -0.2533],
        [ 0.1744,  0.6938, -0.6699,  ..., -0.5077, -0.0810,  0.5587],
        [ 0.1309,  0.6458,  1.9199,  ...,  0.8345, -1.2508,  0.6531]])

In [21]:
x.sum((-1)) / 5000

tensor([ 0.0124, -0.0021,  0.0146, -0.0086,  0.0119, -0.0051,  0.0012,  0.0191,
         0.0050,  0.0265])

In [22]:
y - y.mean(axis=(1, ), keepdim=True), y -  y.sum() / 50000

(tensor([[-0.3817, -0.1835, -1.5463,  ..., -2.1051, -1.2046,  3.5418],
         [ 3.8134,  2.7599, -3.0942,  ..., -3.6861,  3.3261, -3.9601],
         [-2.9215, -3.5598, -2.8361,  ..., -3.5278,  0.1972, -0.7693],
         ...,
         [-0.8184, -3.0790,  2.2531,  ..., -3.7783, -3.3329,  1.3009],
         [ 3.3563,  1.7762,  0.0914,  ...,  0.9927,  1.0587, -1.5650],
         [ 3.8360,  0.8514, -2.5571,  ...,  3.6733,  0.1638,  2.8013]]),
 tensor([[-0.3500, -0.1518, -1.5146,  ..., -2.0734, -1.1729,  3.5735],
         [ 3.7703,  2.7168, -3.1373,  ..., -3.7292,  3.2830, -4.0032],
         [-2.9363, -3.5746, -2.8509,  ..., -3.5426,  0.1824, -0.7841],
         ...,
         [-0.7874, -3.0481,  2.2840,  ..., -3.7473, -3.3019,  1.3318],
         [ 3.3932,  1.8130,  0.1283,  ...,  1.0296,  1.0956, -1.5282],
         [ 3.8346,  0.8500, -2.5585,  ...,  3.6719,  0.1623,  2.7999]]))

In [23]:
z = y.sum(axis=-1, keepdim=True) / 5000

In [24]:
w = y - z

In [25]:
w.mean(axis=(-1))

tensor([ 5.7602e-08, -7.6294e-08,  1.2207e-08,  2.1362e-08, -3.3569e-08,
        -3.0518e-08, -5.2643e-08,  4.5776e-08,  4.5776e-08,  2.5177e-08])

In [26]:
w + 2

tensor([[ 1.6183,  1.8165,  0.4537,  ..., -0.1051,  0.7954,  5.5418],
        [ 5.8134,  4.7599, -1.0942,  ..., -1.6861,  5.3261, -1.9601],
        [-0.9215, -1.5598, -0.8361,  ..., -1.5278,  2.1972,  1.2307],
        ...,
        [ 1.1816, -1.0790,  4.2531,  ..., -1.7783, -1.3329,  3.3009],
        [ 5.3563,  3.7762,  2.0914,  ...,  2.9927,  3.0587,  0.4350],
        [ 5.8360,  2.8514, -0.5571,  ...,  5.6733,  2.1638,  4.8013]])

In [27]:
torch.manual_seed(10)
x = torch.empty((10, 5, 10, 5000)).uniform_(-4, 4)

In [28]:
x.mean(axis=(-1, -2))

tensor([[ 0.0146,  0.0002, -0.0002, -0.0103,  0.0040],
        [ 0.0043, -0.0058,  0.0041,  0.0007,  0.0131],
        [-0.0122,  0.0037, -0.0264, -0.0108, -0.0075],
        [ 0.0198, -0.0003, -0.0140,  0.0062, -0.0056],
        [-0.0018,  0.0028,  0.0114, -0.0059, -0.0080],
        [ 0.0002, -0.0061, -0.0109, -0.0079, -0.0001],
        [ 0.0123, -0.0162,  0.0010,  0.0027, -0.0017],
        [-0.0154, -0.0113, -0.0122,  0.0016, -0.0126],
        [ 0.0298,  0.0111, -0.0063,  0.0095, -0.0102],
        [-0.0012,  0.0038, -0.0087,  0.0119, -0.0023]])

MLP

In [29]:
net = nn.Linear(4, 10)

In [30]:
x = torch.randn(2, 4)

In [31]:
y = net(x)
y.shape

torch.Size([2, 10])

In [32]:
y

tensor([[-0.5986,  0.2001,  1.2537,  0.5834, -0.5716,  0.2312,  0.0540,  0.0463,
         -0.3411,  0.3042],
        [-0.4324,  0.1083, -0.6668, -0.4291, -0.7299, -0.0870, -1.0466,  0.3723,
         -0.6390, -0.0645]], grad_fn=<AddmmBackward0>)

In [33]:
net.weight

Parameter containing:
tensor([[ 0.0322, -0.0182, -0.4234, -0.4418],
        [ 0.4645, -0.0485,  0.1915,  0.4401],
        [-0.2199,  0.2342, -0.1968,  0.4420],
        [-0.3294, -0.1101, -0.0606,  0.2784],
        [-0.4155,  0.4957, -0.1378, -0.4509],
        [-0.2811,  0.3955, -0.3359, -0.4654],
        [ 0.0860,  0.1035, -0.4661,  0.0312],
        [ 0.4474,  0.0618,  0.0999,  0.1228],
        [ 0.0265,  0.4594,  0.2514,  0.1779],
        [ 0.1866,  0.4216,  0.1418,  0.1924]], requires_grad=True)

In [34]:
net.weight.shape

torch.Size([10, 4])

In [35]:
torch.matmul(x, net.weight.T) + net.bias

tensor([[-0.5986,  0.2001,  1.2537,  0.5834, -0.5716,  0.2312,  0.0540,  0.0463,
         -0.3411,  0.3042],
        [-0.4324,  0.1083, -0.6668, -0.4291, -0.7299, -0.0870, -1.0466,  0.3723,
         -0.6390, -0.0645]], grad_fn=<AddBackward0>)

In [36]:
torch.einsum('bj, ij -> bi', x, net.weight) + net.bias

tensor([[-0.5986,  0.2001,  1.2537,  0.5834, -0.5716,  0.2312,  0.0540,  0.0463,
         -0.3411,  0.3042],
        [-0.4324,  0.1083, -0.6668, -0.4291, -0.7299, -0.0870, -1.0466,  0.3723,
         -0.6390, -0.0645]], grad_fn=<AddBackward0>)

In [37]:
import torch.nn.functional as F

In [38]:
x.shape, net.weight.shape, net.bias.shape

(torch.Size([2, 4]), torch.Size([10, 4]), torch.Size([10]))

In [39]:
F.linear(x, net.weight, net.bias)

tensor([[-0.5986,  0.2001,  1.2537,  0.5834, -0.5716,  0.2312,  0.0540,  0.0463,
         -0.3411,  0.3042],
        [-0.4324,  0.1083, -0.6668, -0.4291, -0.7299, -0.0870, -1.0466,  0.3723,
         -0.6390, -0.0645]], grad_fn=<AddmmBackward0>)

In [40]:
torch.manual_seed(42)
net = nn.Sequential()
net.add_module('lin1', nn.Linear(32, 64))
net.add_module('lin2', nn.Linear(64, 10))

In [41]:
x = torch.randn((4, 32))

In [42]:
y = net(x)
y[0], y.shape


(tensor([-0.0630, -0.0022, -0.0127, -0.3661,  0.0866,  0.0741,  0.0963,  0.1773,
         -0.0797,  0.3435], grad_fn=<SelectBackward0>),
 torch.Size([4, 10]))

In [43]:
z = net.lin2(net.lin1(x))
z[0]

tensor([-0.0630, -0.0022, -0.0127, -0.3661,  0.0866,  0.0741,  0.0963,  0.1773,
        -0.0797,  0.3435], grad_fn=<SelectBackward0>)

In [44]:
net.state_dict().keys()

odict_keys(['lin1.weight', 'lin1.bias', 'lin2.weight', 'lin2.bias'])

In [45]:
x = torch.randn(20, 10, 4, 32)
y = net(x)
y.shape

torch.Size([20, 10, 4, 10])

In [46]:
x = torch.empty((4, 5)).uniform_(-10, 10)

In [47]:
x

tensor([[ 9.6053,  6.1465, -3.9468, -6.8474,  6.5705],
        [ 7.9896,  7.8190, -2.3512,  7.2122,  8.1273],
        [ 7.9416,  9.6219, -9.1863,  9.3812,  7.5133],
        [ 2.9351,  5.0090,  1.0653, -6.3083,  4.4218]])

In [48]:
bn = nn.BatchNorm1d(x.shape[1])
y = bn(x)

In [49]:
bn.weight, bn.bias, bn.weight.shape, bn.bias.size()

(Parameter containing:
 tensor([1., 1., 1., 1., 1.], requires_grad=True),
 Parameter containing:
 tensor([0., 0., 0., 0., 0.], requires_grad=True),
 torch.Size([5]),
 torch.Size([5]))

In [50]:
y, y.mean(dim=0), y.std(0)

(tensor([[ 0.9926, -0.5753, -0.0925, -1.0304, -0.0625],
         [ 0.3478,  0.3844,  0.3391,  0.8494,  1.0455],
         [ 0.3287,  1.4189, -1.5100,  1.1394,  0.6085],
         [-1.6691, -1.2280,  1.2634, -0.9584, -1.5915]],
        grad_fn=<NativeBatchNormBackward0>),
 tensor([ 5.9605e-08,  5.9605e-08,  5.9605e-08, -1.4901e-08, -1.4901e-07],
        grad_fn=<MeanBackward1>),
 tensor([1.1547, 1.1547, 1.1547, 1.1547, 1.1547], grad_fn=<StdBackward0>))

In [51]:
x.mean(dim=0)

tensor([ 7.1179,  7.1491, -3.6047,  0.8594,  6.6582])

In [52]:
(x - x.mean(dim=0)) / (x.std(dim=0) + 1e-9)

tensor([[ 0.8596, -0.4982, -0.0801, -0.8924, -0.0541],
        [ 0.3012,  0.3329,  0.2937,  0.7356,  0.9054],
        [ 0.2846,  1.2288, -1.3077,  0.9868,  0.5270],
        [-1.4455, -1.0635,  1.0942, -0.8300, -1.3783]])

In [53]:
x = torch.randint(0, 4, (3, 2, 4))
x

tensor([[[3, 3, 3, 1],
         [3, 1, 1, 3]],

        [[0, 0, 2, 3],
         [2, 3, 2, 1]],

        [[3, 0, 3, 2],
         [2, 2, 2, 2]]])

In [54]:
x.shape, F.one_hot(x, 6).shape, F.one_hot(x, 6)

(torch.Size([3, 2, 4]),
 torch.Size([3, 2, 4, 6]),
 tensor([[[[0, 0, 0, 1, 0, 0],
           [0, 0, 0, 1, 0, 0],
           [0, 0, 0, 1, 0, 0],
           [0, 1, 0, 0, 0, 0]],
 
          [[0, 0, 0, 1, 0, 0],
           [0, 1, 0, 0, 0, 0],
           [0, 1, 0, 0, 0, 0],
           [0, 0, 0, 1, 0, 0]]],
 
 
         [[[1, 0, 0, 0, 0, 0],
           [1, 0, 0, 0, 0, 0],
           [0, 0, 1, 0, 0, 0],
           [0, 0, 0, 1, 0, 0]],
 
          [[0, 0, 1, 0, 0, 0],
           [0, 0, 0, 1, 0, 0],
           [0, 0, 1, 0, 0, 0],
           [0, 1, 0, 0, 0, 0]]],
 
 
         [[[0, 0, 0, 1, 0, 0],
           [1, 0, 0, 0, 0, 0],
           [0, 0, 0, 1, 0, 0],
           [0, 0, 1, 0, 0, 0]],
 
          [[0, 0, 1, 0, 0, 0],
           [0, 0, 1, 0, 0, 0],
           [0, 0, 1, 0, 0, 0],
           [0, 0, 1, 0, 0, 0]]]]))

In [55]:
input = torch.normal(4, 10, size=(10, )).requires_grad_()

In [56]:
input

tensor([-10.9103,   5.8988,  -4.5014,   3.9894,  26.0803,   0.7348,  -1.2472,
          4.5035,  -0.0993,   2.3917], requires_grad=True)

In [57]:
target = torch.randint(0, 2, size=input.size(), dtype=torch.float).requires_grad_()
target

tensor([1., 0., 1., 1., 0., 0., 1., 1., 0., 0.], requires_grad=True)

In [58]:
target

tensor([1., 0., 1., 1., 0., 0., 1., 1., 0., 0.], requires_grad=True)

In [59]:
F.binary_cross_entropy(F.sigmoid(input), target, reduce=None)

tensor(12.7104, grad_fn=<BinaryCrossEntropyBackward0>)

In [60]:
def binary_cross_entropy(input, target):
    mu = nn.Sigmoid()(input)
    
    loss = target * torch.log(mu) + (1 - target) * torch.log( 1 - mu)
    
    return -loss.mean()
    
binary_cross_entropy(input, target)
    

tensor(inf, grad_fn=<NegBackward0>)

In [61]:
target = torch.empty_like(target).uniform_(0, 1).requires_grad_()

In [62]:
target

tensor([0.4711, 0.7032, 0.9075, 0.0051, 0.0616, 0.8857, 0.4707, 0.7001, 0.8452,
        0.8964], requires_grad=True)

In [63]:
F.binary_cross_entropy(F.sigmoid(input), target, reduce=None)

tensor(11.2562, grad_fn=<BinaryCrossEntropyBackward0>)

In [64]:
binary_cross_entropy(input, target)

tensor(inf, grad_fn=<NegBackward0>)

In [65]:
torch.Tensor(25)

tensor([-1.0316e-23,  4.5688e-41, -9.9713e-24,  4.5688e-41, -1.0599e-23,
         4.5688e-41, -1.0662e-23,  4.5688e-41, -1.0043e-23,  4.5688e-41,
        -1.0031e-23,  4.5688e-41, -1.0031e-23,  4.5688e-41, -1.0003e-23,
         4.5688e-41, -1.0638e-23,  4.5688e-41, -1.0022e-23,  4.5688e-41,
        -9.6668e-24,  4.5688e-41, -9.7150e-24,  4.5688e-41, -9.6879e-24])

LSTM

In [66]:
net = nn.LSTM(input_size=128, 
                hidden_size=256,
                num_layers=1, 
                )

In [67]:
inp = torch.randn((64, 32, 128))

In [68]:
out, (hn, cn)= net(inp)

In [69]:
out.shape

torch.Size([64, 32, 256])

In [70]:
hn.shape

torch.Size([1, 32, 256])

In [71]:
h0 = torch.randn((1, 32, 256))
c0 = torch.zeros_like(h0)

In [72]:
out, (hn, cn) = net(inp, (h0, c0))

In [73]:
hn.shape

torch.Size([1, 32, 256])

In [74]:
net = nn.LSTM(input_size=128, 
                hidden_size=256,
                num_layers=1, 
                proj_size=96
                )

In [75]:
h0 = torch.randn((1, 32, 96))
c0 = torch.randn((1, 32, 256))
out, (hn, cn) = net(inp, (h0, c0))

/home/mtb/env/lib/python3.9/site-packages/torch/nn/modules/rnn.py:812: UserWarning: LSTM with projections is not supported with oneDNN. Using default implementation. (Triggered internally at ../aten/src/ATen/native/RNN.cpp:1463.)
  result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,


In [76]:
out.shape

torch.Size([64, 32, 96])

In [77]:
hn.shape

torch.Size([1, 32, 96])

In [78]:
cn.shape

torch.Size([1, 32, 256])

In [79]:
net = nn.LSTM(input_size=128, 
                hidden_size=256,
                num_layers=1, 
                bidirectional=True
                )

In [80]:
out, (hn, cn) = net(inp)

In [81]:
out.shape

torch.Size([64, 32, 512])

In [82]:
hn.shape

torch.Size([2, 32, 256])

In [83]:
cn.shape

torch.Size([2, 32, 256])

In [84]:
net = nn.LSTM(input_size=128, 
                hidden_size=256,
                num_layers=4, 
                bidirectional=True
                )

In [85]:
out, (hn, cn) = net(inp)

In [86]:
out.shape

torch.Size([64, 32, 512])

In [87]:
hn.shape

torch.Size([8, 32, 256])

In [88]:
cn.shape

torch.Size([8, 32, 256])

In [89]:
x = torch.arange(0, 100)

In [90]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [91]:
y = x.view(2, 50)

In [92]:
y+= 1
x, y

(tensor([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
          15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
          29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
          43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
          57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
          71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
          85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
          99, 100]),
 tensor([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
           15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
           29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
           43,  44,  45,  46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
           65,  66,  67,  68,  69,  70,  71,  72,  73, 

In [93]:
y = x.view(20, 5)

In [94]:
y

tensor([[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75],
        [ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]])

In [95]:
y.view(4, 5, -1)

tensor([[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20],
         [ 21,  22,  23,  24,  25]],

        [[ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40],
         [ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50]],

        [[ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60],
         [ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75]],

        [[ 76,  77,  78,  79,  80],
         [ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]]])

In [96]:
net.weight_ih_l0.shape

torch.Size([1024, 128])

In [97]:
emb_net = nn.Embedding(1000, 128, padding_idx=0)

In [98]:
x = torch.randint(0, 1000, size=(64, 20))

In [99]:
x.shape

torch.Size([64, 20])

In [100]:
emb = emb_net(x)

In [101]:
emb.shape

torch.Size([64, 20, 128])

In [102]:
emb[0][0]

tensor([-9.0001e-01, -4.5618e-01, -3.3796e-01,  5.4977e-02,  2.1113e+00,
        -1.2687e+00,  2.2862e+00,  2.0994e+00,  1.1920e-01,  1.9923e-01,
         9.4172e-01, -1.7726e-01,  1.1779e+00,  1.1366e+00, -1.1261e+00,
        -1.3342e+00,  8.5693e-01, -1.9372e+00,  1.7511e+00,  1.1171e+00,
         1.0702e+00,  3.2450e-04,  1.1027e+00,  6.2287e-02, -1.1783e-01,
        -6.0368e-01, -5.4402e-01,  6.4613e-01,  1.1293e+00,  1.0740e+00,
         1.0198e+00,  4.9398e-01,  2.8837e-01,  7.4511e-01, -9.0288e-01,
        -8.9145e-02,  5.0449e-01,  2.2546e+00, -5.8698e-01,  6.1598e-02,
         7.3877e-01, -2.3824e-01, -3.3074e-01,  1.3412e+00,  5.6607e-02,
         7.2386e-01, -1.0868e+00,  3.5732e-01,  2.0704e+00, -2.2176e-01,
        -6.3954e-01, -1.1623e+00, -7.9249e-01, -1.5707e+00,  5.0808e-01,
         1.7823e-01,  4.4992e-01,  2.2511e-01,  1.0701e+00, -1.1095e+00,
         2.1271e-01, -5.1025e-01,  5.1649e-01,  9.7876e-01,  4.2928e-02,
        -3.4780e-01, -4.9096e-01,  9.8162e-01,  8.6

In [103]:
x = torch.randn((10, ))

In [104]:
x

tensor([-0.2459, -0.5377,  0.2185,  0.9448, -0.2103,  0.7507,  1.4196, -0.7844,
        -0.0427, -0.8096])

In [105]:
dropout = nn.Dropout(p=0.2)

In [106]:
y = dropout(x)

In [107]:
y

tensor([-0.0000, -0.6722,  0.0000,  1.1810, -0.2629,  0.9384,  1.7746, -0.9805,
        -0.0534, -1.0119])

In [108]:
x

tensor([-0.2459, -0.5377,  0.2185,  0.9448, -0.2103,  0.7507,  1.4196, -0.7844,
        -0.0427, -0.8096])

In [109]:
x / y

tensor([   inf, 0.8000,    inf, 0.8000, 0.8000, 0.8000, 0.8000, 0.8000, 0.8000,
        0.8000])

In [110]:
y * 0.8

tensor([-0.0000, -0.5377,  0.0000,  0.9448, -0.2103,  0.7507,  1.4196, -0.7844,
        -0.0427, -0.8096])

Pack padding

In [111]:
seqs = ['Long_str', 'tiny', 'medium']

In [112]:
vocab = ['<pad>'] + sorted(set(c for s in seqs for c in s))

In [113]:
vocab

['<pad>', 'L', '_', 'd', 'e', 'g', 'i', 'm', 'n', 'o', 'r', 's', 't', 'u', 'y']

In [114]:
tok_dict = {c: i for i, c in enumerate(vocab)}

In [115]:
tok_dict

{'<pad>': 0,
 'L': 1,
 '_': 2,
 'd': 3,
 'e': 4,
 'g': 5,
 'i': 6,
 'm': 7,
 'n': 8,
 'o': 9,
 'r': 10,
 's': 11,
 't': 12,
 'u': 13,
 'y': 14}

In [116]:
tensor_seqs = [[tok_dict[c] for c in seq] for seq in seqs ]

In [117]:
tensor_seqs

[[1, 9, 8, 5, 2, 11, 12, 10], [12, 6, 8, 14], [7, 4, 3, 6, 13, 7]]

In [118]:
lengths = [len(s) for s in seqs]

In [119]:
lengths

[8, 4, 6]

In [120]:
seq_tensor = torch.full((len(seqs), max(lengths)),  0)

In [121]:
for i, s in enumerate(tensor_seqs):
    seq_tensor[i, :lengths[i]].copy_(torch.tensor(s))

In [122]:
seq_tensor

tensor([[ 1,  9,  8,  5,  2, 11, 12, 10],
        [12,  6,  8, 14,  0,  0,  0,  0],
        [ 7,  4,  3,  6, 13,  7,  0,  0]])

In [123]:
seq_tensor.shape

torch.Size([3, 8])

In [124]:
seq_tensor = seq_tensor[[0, 2, 1]]

In [125]:
seq_tensor

tensor([[ 1,  9,  8,  5,  2, 11, 12, 10],
        [ 7,  4,  3,  6, 13,  7,  0,  0],
        [12,  6,  8, 14,  0,  0,  0,  0]])

In [126]:
emb_net = nn.Embedding(len(vocab), 4, padding_idx=0)

In [127]:
emb = emb_net(seq_tensor)

In [128]:
emb.shape

torch.Size([3, 8, 4])

In [129]:
lstm = nn.LSTM(4, 5, batch_first=True)

In [130]:
emb

tensor([[[ 0.3671,  1.3340,  0.8594, -0.3965],
         [ 1.0585, -1.7917,  1.2432, -0.4402],
         [-0.6276,  0.2203,  0.0834,  0.0284],
         [-1.3854,  0.5379, -0.2663, -0.4320],
         [-2.2702, -0.1355, -0.2149,  0.1521],
         [ 1.0618,  1.0721,  0.7986,  0.1014],
         [ 0.1155,  0.7137,  0.3804, -2.0123],
         [-1.1377, -1.4786,  0.9397, -0.7802]],

        [[-1.2943,  0.5872, -1.7636,  0.6925],
         [ 1.7885,  1.1710,  0.5277, -0.0941],
         [-1.3338, -1.9147, -0.6878,  0.2971],
         [-0.4266, -0.8293, -0.5631,  2.1739],
         [ 0.4974, -0.5883,  0.2990, -0.4474],
         [-1.2943,  0.5872, -1.7636,  0.6925],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.1155,  0.7137,  0.3804, -2.0123],
         [-0.4266, -0.8293, -0.5631,  2.1739],
         [-0.6276,  0.2203,  0.0834,  0.0284],
         [ 0.7318,  0.0792,  0.5259,  0.2827],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         

In [131]:
seq_lengths = torch.tensor([lengths[0], lengths[2], lengths[1]])

In [132]:
seq_lengths

tensor([8, 6, 4])

In [133]:
emb, emb.shape

(tensor([[[ 0.3671,  1.3340,  0.8594, -0.3965],
          [ 1.0585, -1.7917,  1.2432, -0.4402],
          [-0.6276,  0.2203,  0.0834,  0.0284],
          [-1.3854,  0.5379, -0.2663, -0.4320],
          [-2.2702, -0.1355, -0.2149,  0.1521],
          [ 1.0618,  1.0721,  0.7986,  0.1014],
          [ 0.1155,  0.7137,  0.3804, -2.0123],
          [-1.1377, -1.4786,  0.9397, -0.7802]],
 
         [[-1.2943,  0.5872, -1.7636,  0.6925],
          [ 1.7885,  1.1710,  0.5277, -0.0941],
          [-1.3338, -1.9147, -0.6878,  0.2971],
          [-0.4266, -0.8293, -0.5631,  2.1739],
          [ 0.4974, -0.5883,  0.2990, -0.4474],
          [-1.2943,  0.5872, -1.7636,  0.6925],
          [ 0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000]],
 
         [[ 0.1155,  0.7137,  0.3804, -2.0123],
          [-0.4266, -0.8293, -0.5631,  2.1739],
          [-0.6276,  0.2203,  0.0834,  0.0284],
          [ 0.7318,  0.0792,  0.5259,  0.2827],
          [ 0.0000,  0.0000,  0.00

In [134]:
pack = nn.utils.rnn.pack_padded_sequence(emb, seq_lengths, batch_first=True)

In [135]:
pack

PackedSequence(data=tensor([[ 0.3671,  1.3340,  0.8594, -0.3965],
        [-1.2943,  0.5872, -1.7636,  0.6925],
        [ 0.1155,  0.7137,  0.3804, -2.0123],
        [ 1.0585, -1.7917,  1.2432, -0.4402],
        [ 1.7885,  1.1710,  0.5277, -0.0941],
        [-0.4266, -0.8293, -0.5631,  2.1739],
        [-0.6276,  0.2203,  0.0834,  0.0284],
        [-1.3338, -1.9147, -0.6878,  0.2971],
        [-0.6276,  0.2203,  0.0834,  0.0284],
        [-1.3854,  0.5379, -0.2663, -0.4320],
        [-0.4266, -0.8293, -0.5631,  2.1739],
        [ 0.7318,  0.0792,  0.5259,  0.2827],
        [-2.2702, -0.1355, -0.2149,  0.1521],
        [ 0.4974, -0.5883,  0.2990, -0.4474],
        [ 1.0618,  1.0721,  0.7986,  0.1014],
        [-1.2943,  0.5872, -1.7636,  0.6925],
        [ 0.1155,  0.7137,  0.3804, -2.0123],
        [-1.1377, -1.4786,  0.9397, -0.7802]],
       grad_fn=<PackPaddedSequenceBackward0>), batch_sizes=tensor([3, 3, 3, 3, 2, 2, 1, 1]), sorted_indices=None, unsorted_indices=None)

In [136]:
pack_out, (hn, cn) = lstm(pack)

In [137]:
pack_out

PackedSequence(data=tensor([[-0.0479,  0.1212,  0.1360, -0.0552, -0.0867],
        [-0.2239, -0.0018, -0.0403,  0.0916,  0.0348],
        [-0.0582,  0.0309,  0.1993, -0.0363, -0.1940],
        [ 0.0527,  0.3471,  0.1746, -0.0436,  0.1176],
        [-0.1283,  0.1882,  0.1621, -0.1178,  0.0758],
        [ 0.1396,  0.1737,  0.0049,  0.2628,  0.0236],
        [ 0.0521,  0.1669,  0.1245,  0.0671,  0.0438],
        [ 0.0601,  0.0435,  0.0103,  0.0845,  0.1172],
        [ 0.0191,  0.0935,  0.0060,  0.1596, -0.0057],
        [-0.0837,  0.0347,  0.0886,  0.0900, -0.0941],
        [ 0.1646,  0.1336, -0.0343,  0.3357,  0.2339],
        [ 0.0511,  0.2284,  0.0769,  0.1150,  0.0718],
        [-0.1049, -0.0510,  0.0171,  0.1851, -0.0958],
        [ 0.0759,  0.1482, -0.0040,  0.2034,  0.2706],
        [-0.0709,  0.1320,  0.1601,  0.0020, -0.1178],
        [-0.1885,  0.0074, -0.0555,  0.1314,  0.2051],
        [-0.1011,  0.1170,  0.3258, -0.0443, -0.2554],
        [ 0.0254,  0.0929,  0.1277,  0.0225, 

In [138]:
hn, hn.shape

(tensor([[[ 0.0254,  0.0929,  0.1277,  0.0225, -0.1082],
          [-0.1885,  0.0074, -0.0555,  0.1314,  0.2051],
          [ 0.0511,  0.2284,  0.0769,  0.1150,  0.0718]]],
        grad_fn=<StackBackward0>),
 torch.Size([1, 3, 5]))

In [139]:
cn, cn.shape

(tensor([[[ 0.0780,  0.1852,  0.2993,  0.0389, -0.3620],
          [-0.2909,  0.0284, -0.1417,  0.5317,  0.3060],
          [ 0.1402,  0.4977,  0.1136,  0.2195,  0.1058]]],
        grad_fn=<StackBackward0>),
 torch.Size([1, 3, 5]))

In [140]:
out = nn.utils.rnn.pad_packed_sequence(pack_out, batch_first=True)

In [141]:
out

(tensor([[[-0.0479,  0.1212,  0.1360, -0.0552, -0.0867],
          [ 0.0527,  0.3471,  0.1746, -0.0436,  0.1176],
          [ 0.0521,  0.1669,  0.1245,  0.0671,  0.0438],
          [-0.0837,  0.0347,  0.0886,  0.0900, -0.0941],
          [-0.1049, -0.0510,  0.0171,  0.1851, -0.0958],
          [-0.0709,  0.1320,  0.1601,  0.0020, -0.1178],
          [-0.1011,  0.1170,  0.3258, -0.0443, -0.2554],
          [ 0.0254,  0.0929,  0.1277,  0.0225, -0.1082]],
 
         [[-0.2239, -0.0018, -0.0403,  0.0916,  0.0348],
          [-0.1283,  0.1882,  0.1621, -0.1178,  0.0758],
          [ 0.0601,  0.0435,  0.0103,  0.0845,  0.1172],
          [ 0.1646,  0.1336, -0.0343,  0.3357,  0.2339],
          [ 0.0759,  0.1482, -0.0040,  0.2034,  0.2706],
          [-0.1885,  0.0074, -0.0555,  0.1314,  0.2051],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],
 
         [[-0.0582,  0.0309,  0.1993, -0.0363, -0.1940],
          [ 0.1396,  0.17

In [142]:
out[0].shape

torch.Size([3, 8, 5])

In [143]:
emb.shape

torch.Size([3, 8, 4])

In [144]:
nn.Dropout(p=0.1)(torch.randn(2, 5, 10))

tensor([[[-1.5460, -2.5042,  0.4786,  0.8921,  1.4133,  0.7514,  2.1048,
          -0.0121,  2.6287, -3.4389],
         [-0.4235,  0.0000,  1.4360,  0.6238,  0.0000,  0.0000,  1.2670,
           2.7964, -0.6498,  0.4897],
         [-0.9694, -0.2152,  0.3140, -0.3766,  0.0000,  1.1677, -0.9263,
           0.0385, -1.9612,  0.2844],
         [-0.3100,  1.5022,  0.5568, -0.7406, -0.0820, -1.3247,  0.1136,
           1.3514,  0.7137,  0.5456],
         [ 0.3754, -0.7686,  0.0527,  0.3326, -0.5875,  0.0000, -1.5427,
           1.2762, -0.2588,  0.6040]],

        [[ 1.6713, -0.1814, -0.1206, -0.0000,  1.7031,  1.2326, -0.8841,
           0.3153, -0.5282, -2.3104],
         [-1.4563,  1.5149, -0.7979,  1.0994, -1.4102,  0.4619,  0.1596,
           0.8654,  1.3375,  0.0607],
         [ 1.4168,  0.3127,  0.3840, -0.3514,  0.3749,  0.4348,  1.9042,
           0.6755, -1.8836,  0.9926],
         [-0.8742,  1.3405,  0.6788,  0.5404,  1.0181,  2.5527, -0.4064,
          -0.0000,  2.8675,  0.5209],

In [145]:
lstm.weight_hh_l0

Parameter containing:
tensor([[-0.0333,  0.1173, -0.0640,  0.0197,  0.0359],
        [-0.3169, -0.4083,  0.3587,  0.3638,  0.0152],
        [ 0.3171, -0.0092, -0.0725, -0.3896,  0.0393],
        [-0.0629,  0.0823,  0.3987, -0.3283, -0.1105],
        [ 0.3074, -0.3461, -0.4293, -0.2412, -0.1811],
        [ 0.1837, -0.3388,  0.0512,  0.2533, -0.4404],
        [-0.1301,  0.2809,  0.2151,  0.3206,  0.2904],
        [-0.0255, -0.4137,  0.1480, -0.2196,  0.1552],
        [ 0.2892, -0.0090,  0.0429, -0.3924, -0.2510],
        [-0.3423,  0.2023,  0.0337,  0.2497,  0.1350],
        [ 0.4103,  0.3104,  0.2279, -0.3925,  0.1034],
        [-0.0767, -0.0106,  0.0750, -0.3789, -0.3944],
        [-0.4202,  0.3310,  0.0324, -0.2236, -0.3058],
        [ 0.3241, -0.2345,  0.0772,  0.0695,  0.4145],
        [-0.3109, -0.4248, -0.2422,  0.2540, -0.0280],
        [-0.3810,  0.4236, -0.1972, -0.1865, -0.0556],
        [-0.0341,  0.4008,  0.2638, -0.2003,  0.0666],
        [-0.4169,  0.1741, -0.4416,  0.0811

In [146]:
w = lstm.weight_hh_l0
w.shape

torch.Size([20, 5])

In [147]:
u, v = w.chunk(2, dim=1)

In [148]:
u

tensor([[-0.0333,  0.1173, -0.0640],
        [-0.3169, -0.4083,  0.3587],
        [ 0.3171, -0.0092, -0.0725],
        [-0.0629,  0.0823,  0.3987],
        [ 0.3074, -0.3461, -0.4293],
        [ 0.1837, -0.3388,  0.0512],
        [-0.1301,  0.2809,  0.2151],
        [-0.0255, -0.4137,  0.1480],
        [ 0.2892, -0.0090,  0.0429],
        [-0.3423,  0.2023,  0.0337],
        [ 0.4103,  0.3104,  0.2279],
        [-0.0767, -0.0106,  0.0750],
        [-0.4202,  0.3310,  0.0324],
        [ 0.3241, -0.2345,  0.0772],
        [-0.3109, -0.4248, -0.2422],
        [-0.3810,  0.4236, -0.1972],
        [-0.0341,  0.4008,  0.2638],
        [-0.4169,  0.1741, -0.4416],
        [-0.2715, -0.1549,  0.3251],
        [ 0.3530,  0.3771,  0.2422]], grad_fn=<SplitBackward0>)

In [149]:
v

tensor([[ 0.0197,  0.0359],
        [ 0.3638,  0.0152],
        [-0.3896,  0.0393],
        [-0.3283, -0.1105],
        [-0.2412, -0.1811],
        [ 0.2533, -0.4404],
        [ 0.3206,  0.2904],
        [-0.2196,  0.1552],
        [-0.3924, -0.2510],
        [ 0.2497,  0.1350],
        [-0.3925,  0.1034],
        [-0.3789, -0.3944],
        [-0.2236, -0.3058],
        [ 0.0695,  0.4145],
        [ 0.2540, -0.0280],
        [-0.1865, -0.0556],
        [-0.2003,  0.0666],
        [ 0.0811, -0.0734],
        [-0.1380,  0.3148],
        [ 0.4266,  0.3653]], grad_fn=<SplitBackward0>)

In [150]:
(torch.arange(0, 10,) >= torch.randint(4, 8, (30, )).view(3, 10).unsqueeze_(1)).size(0)

3

In [151]:
torch.arange(0, 10,) >= torch.randint(4, 8, (9, )).view(9).unsqueeze(1)

tensor([[False, False, False, False,  True,  True,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True,  True,  True],
        [False, False, False, False, False, False, False,  True,  True,  True],
        [False, False, False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False, False,  True,  True,  True,  True,  True],
        [False, False, False, False, False, False, False,  True,  True,  True],
        [False, False, False, False, False, False, False,  True,  True,  True]])

In [152]:
nn.Linear(128, 256)(torch.randn((16, 64, 92, 128))).shape

torch.Size([16, 64, 92, 256])

In [153]:
(torch.randn((3, 1, 4)) + torch.randn(( 4))).shape

torch.Size([3, 1, 4])

In [154]:
torch.exp(torch.tensor(-65504.))

tensor(0.)

Cross entropy loss

In [155]:
x = torch.randn((16, 48, 128))

In [156]:
mask = torch.randint(10, 128, size=(16, 48, 1))
mask[0][0]

tensor([104])

In [157]:
target = torch.empty((16, 48, 128), dtype=torch.int64).random_(1, 128)
target[0][0]

tensor([  1,  66,  94,  85,  29,  79,  97,  99, 100,  72,  15,  27,  79,  52,
         79,  85,  17, 104,  93,  85,  48, 122,  17,  10,  52,  98,  42,  38,
         14,  26,  14,  87,  85,  92,  80, 120,  95, 100,  50,  70,  26, 122,
         89,  64,   1,  82,   1, 109,  34, 124,  26,  82,  59,  73, 104,  73,
         63,  78, 107, 113,  40,  21,  64, 112,  13, 100,  56,  81,  66, 119,
          6,  13,  39,  85, 107,  82,  85,  65,  31,  31, 104,  98,  22,  69,
         75,  56,  45,  17,  46,  18,  59,  58,  25,  67,  11,  14,  33,  98,
         92,   8,  98,  79,  85, 116,  46,  62,  32, 106,  29,  23, 107,  98,
         96,  75,  22, 110, 122,  20,  94,  74,  25,   8, 101, 121,  44,  50,
          4,  28])

In [158]:
masked = torch.arange(0, 128, dtype=torch.long) >= mask
target.masked_fill_(masked, 0) 
pass

In [159]:
target[0][0][mask[0][0]-1:]

tensor([116,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0])

In [160]:
cross_loss = nn.CrossEntropyLoss(ignore_index=0)

In [161]:
# loss = cross_loss(input, target)

In [162]:
target[0][0]

tensor([  1,  66,  94,  85,  29,  79,  97,  99, 100,  72,  15,  27,  79,  52,
         79,  85,  17, 104,  93,  85,  48, 122,  17,  10,  52,  98,  42,  38,
         14,  26,  14,  87,  85,  92,  80, 120,  95, 100,  50,  70,  26, 122,
         89,  64,   1,  82,   1, 109,  34, 124,  26,  82,  59,  73, 104,  73,
         63,  78, 107, 113,  40,  21,  64, 112,  13, 100,  56,  81,  66, 119,
          6,  13,  39,  85, 107,  82,  85,  65,  31,  31, 104,  98,  22,  69,
         75,  56,  45,  17,  46,  18,  59,  58,  25,  67,  11,  14,  33,  98,
         92,   8,  98,  79,  85, 116,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0])

In [163]:
x = torch.randn((2, 4, 8))
x

tensor([[[ 0.2552, -0.1802,  0.2588, -0.7061, -0.8777, -1.2653,  0.0321,
           1.5530],
         [ 0.3243,  0.2790,  0.1466,  0.7425,  0.5751, -0.4438,  0.9766,
           0.1799],
         [-0.0652, -0.1049, -0.1837, -0.6695,  1.3287, -1.7559,  0.6593,
           0.4805],
         [ 0.5903,  0.8178, -0.9333, -0.6854,  0.9481,  0.7393,  0.3437,
           0.0594]],

        [[ 0.7289,  0.7445,  0.5808,  0.7623, -2.6973,  0.2699, -0.7284,
           1.2703],
         [-0.9471, -0.5631,  0.7597, -0.1863, -0.0955, -1.4100,  0.2837,
           2.0454],
         [ 0.2972, -0.9666, -1.2491, -0.0188, -0.7169,  1.4711,  1.8277,
          -0.6550],
         [-1.7866, -0.5917,  1.0615, -0.8268, -0.9765,  0.1190, -2.1398,
           1.4746]]])

In [164]:
target = torch.empty((2, 4), dtype=torch.int64).random_(1, 8)
target

tensor([[1, 7, 1, 3],
        [5, 4, 6, 2]])

In [165]:
y = x.gather(dim=-1, index=target.unsqueeze(2))

In [166]:
y.shape, y

(torch.Size([2, 4, 1]),
 tensor([[[-0.1802],
          [ 0.1799],
          [-0.1049],
          [-0.6854]],
 
         [[ 0.2699],
          [-0.0955],
          [ 1.8277],
          [ 1.0615]]]))

In [167]:
net = nn.Linear(10, 50)

In [168]:
net.half()

Linear(in_features=10, out_features=50, bias=True)

In [169]:
for p in net.parameters():
    print(p.dtype)

torch.float16
torch.float16


In [170]:
for p in net.parameters():
    p.to(torch.float)
    print(p.dtype)
    

torch.float16
torch.float16


In [171]:
for p in net.parameters():
    print(p.requires_grad)

True
True


In [172]:
for p in net.parameters():
    print(p.detach().requires_grad, p.dtype)

False torch.float16
False torch.float16


In [173]:
net.float()
loss = net(torch.randn((32, 10), dtype=torch.float32)).sum()

In [174]:
loss.backward()

In [175]:
for p in net.parameters():
    print(type(p.grad), p.grad.requires_grad)

<class 'torch.Tensor'> False
<class 'torch.Tensor'> False


In [176]:
nn.utils.clip_grad_norm_(net.parameters(), 5.0)

tensor(267.4038)

In [177]:
math.exp(math.log(0.01) / 100)

0.954992586021436

In [178]:
0.954992586021436 ** 100

0.010000000000000049

In [179]:
x = torch.empty((4, 5)).float().uniform_(-1, 1)

In [180]:
x

tensor([[ 0.7856, -0.7376, -0.3534, -0.2913, -0.6105],
        [ 0.5831, -0.2230, -0.5985, -0.2779,  0.9229],
        [ 0.6013,  0.0888, -0.3773,  0.8554,  0.2857],
        [-0.2183, -0.9263,  0.0471,  0.4908,  0.4940]])

In [181]:
y = torch.zeros_like(x)

In [182]:
y

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [183]:
z = x.to(y)

In [184]:
z += 3

In [185]:
z, y, x

(tensor([[3.7856, 2.2624, 2.6466, 2.7087, 2.3895],
         [3.5831, 2.7770, 2.4015, 2.7221, 3.9229],
         [3.6013, 3.0888, 2.6227, 3.8554, 3.2857],
         [2.7817, 2.0737, 3.0471, 3.4908, 3.4940]]),
 tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 tensor([[3.7856, 2.2624, 2.6466, 2.7087, 2.3895],
         [3.5831, 2.7770, 2.4015, 2.7221, 3.9229],
         [3.6013, 3.0888, 2.6227, 3.8554, 3.2857],
         [2.7817, 2.0737, 3.0471, 3.4908, 3.4940]]))

In [186]:
x = torch.randn(4, 5)

In [187]:
x = x.cuda()

In [188]:
x

tensor([[-1.2026,  0.4336,  1.5385, -0.2196,  0.5242],
        [ 0.3118,  0.3979, -0.9387, -1.3952,  1.2149],
        [ 0.8543,  0.3101, -0.2559, -1.3743, -0.5957],
        [ 1.9387, -0.8684,  0.3165, -0.1275,  0.2961]], device='cuda:0')

In [189]:
x.new_zeros(8, 20)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       device='cuda:0')

In [190]:
x

tensor([[-1.2026,  0.4336,  1.5385, -0.2196,  0.5242],
        [ 0.3118,  0.3979, -0.9387, -1.3952,  1.2149],
        [ 0.8543,  0.3101, -0.2559, -1.3743, -0.5957],
        [ 1.9387, -0.8684,  0.3165, -0.1275,  0.2961]], device='cuda:0')

In [191]:
x.shape

torch.Size([4, 5])

In [192]:
x.expand(2, -1, -1)

tensor([[[-1.2026,  0.4336,  1.5385, -0.2196,  0.5242],
         [ 0.3118,  0.3979, -0.9387, -1.3952,  1.2149],
         [ 0.8543,  0.3101, -0.2559, -1.3743, -0.5957],
         [ 1.9387, -0.8684,  0.3165, -0.1275,  0.2961]],

        [[-1.2026,  0.4336,  1.5385, -0.2196,  0.5242],
         [ 0.3118,  0.3979, -0.9387, -1.3952,  1.2149],
         [ 0.8543,  0.3101, -0.2559, -1.3743, -0.5957],
         [ 1.9387, -0.8684,  0.3165, -0.1275,  0.2961]]], device='cuda:0')

In [193]:
torch.cat([x, x])

tensor([[-1.2026,  0.4336,  1.5385, -0.2196,  0.5242],
        [ 0.3118,  0.3979, -0.9387, -1.3952,  1.2149],
        [ 0.8543,  0.3101, -0.2559, -1.3743, -0.5957],
        [ 1.9387, -0.8684,  0.3165, -0.1275,  0.2961],
        [-1.2026,  0.4336,  1.5385, -0.2196,  0.5242],
        [ 0.3118,  0.3979, -0.9387, -1.3952,  1.2149],
        [ 0.8543,  0.3101, -0.2559, -1.3743, -0.5957],
        [ 1.9387, -0.8684,  0.3165, -0.1275,  0.2961]], device='cuda:0')

In [194]:
torch.arange(4*2*5).view(4,2,5) @ torch.arange(5)

tensor([[ 30,  80],
        [130, 180],
        [230, 280],
        [330, 380]])

In [195]:
torch.arange(4*2*5).view(4,2,5)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]])

In [196]:
a = torch.tensor([ 0,  1,  2,  3,  4]) 
b = torch.tensor([ 5,  6,  7,  8,  9]) 
torch.dot(a, b) 

tensor(80)

In [197]:
torch.exp(torch.tensor(-torch.inf))

tensor(0.)

In [198]:
a = torch.tensor([ 0,  1,  2,  3,  4]) 
b = a.expand(4, -1)
b

tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])

In [199]:
b[0][0] = -1

In [200]:
b

tensor([[-1,  1,  2,  3,  4],
        [-1,  1,  2,  3,  4],
        [-1,  1,  2,  3,  4],
        [-1,  1,  2,  3,  4]])

In [201]:
c = a.tile((4, 1))
c

tensor([[-1,  1,  2,  3,  4],
        [-1,  1,  2,  3,  4],
        [-1,  1,  2,  3,  4],
        [-1,  1,  2,  3,  4]])

In [202]:
c[0][0] = 5

In [203]:
c

tensor([[ 5,  1,  2,  3,  4],
        [-1,  1,  2,  3,  4],
        [-1,  1,  2,  3,  4],
        [-1,  1,  2,  3,  4]])

In [204]:
torch.randn( 4, 3) @ torch.randn(4,3,5)

tensor([[[ 1.0379, -1.2986,  3.6725,  6.4050, -1.8806],
         [ 0.5234,  0.5678,  0.1198, -0.8536, -0.0784],
         [-0.5930,  1.6018, -1.6862, -1.7482,  0.9474],
         [-2.9078, -4.2625, -2.9139, -2.7605,  1.3777]],

        [[ 0.9528,  1.2752, -2.7449, -0.4769,  2.6711],
         [-0.0438,  0.2637, -0.3784,  0.3944, -0.5114],
         [-0.1442, -0.8427,  0.8159,  0.2917, -0.3605],
         [-1.0823, -1.4784,  4.6096, -1.7656, -1.2659]],

        [[ 3.3463,  0.1492,  1.6178,  0.7421,  0.1577],
         [-0.3393, -0.1095, -0.0792,  0.2257,  0.2204],
         [-0.9660, -0.1936, -0.5210,  0.3073, -1.1235],
         [-1.8322,  0.7251, -1.1677, -3.0768,  1.3006]],

        [[ 1.3937,  1.0690, -2.4575,  1.4787, -2.0818],
         [ 0.0680,  0.3015, -0.2224, -0.2757,  0.5324],
         [-1.4089, -0.0089,  1.5750, -0.4738,  1.1633],
         [ 0.5870, -3.2606,  1.5887, -0.0941, -1.7241]]])

In [205]:
a, b = torch.arange(3*2*4).view(3,2,4), torch.arange(3* 2).view(3, 2)
c = a * b.unsqueeze(2)
b, a, c

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7]],
 
         [[ 8,  9, 10, 11],
          [12, 13, 14, 15]],
 
         [[16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[  0,   0,   0,   0],
          [  4,   5,   6,   7]],
 
         [[ 16,  18,  20,  22],
          [ 36,  39,  42,  45]],
 
         [[ 64,  68,  72,  76],
          [100, 105, 110, 115]]]))

In [206]:
a, b = torch.arange(3*2*4).view(3,2,4), torch.arange(3* 2).view(3, 2)
c = b.unsqueeze(2) * a
b, a, c

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7]],
 
         [[ 8,  9, 10, 11],
          [12, 13, 14, 15]],
 
         [[16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[  0,   0,   0,   0],
          [  4,   5,   6,   7]],
 
         [[ 16,  18,  20,  22],
          [ 36,  39,  42,  45]],
 
         [[ 64,  68,  72,  76],
          [100, 105, 110, 115]]]))

In [207]:
b.shape, a.shape, c.shape

(torch.Size([3, 2]), torch.Size([3, 2, 4]), torch.Size([3, 2, 4]))

In [208]:
x = torch.randn(10, 5, 4)
y = torch.randn(5, 4)
x[:,] = y

In [209]:
x[:3]

tensor([[[ 0.2611, -1.6730,  0.8805, -1.2368],
         [ 0.9056, -1.6026,  0.8037, -0.0968],
         [ 0.0798,  0.7070,  0.7029,  1.2827],
         [ 0.4760, -0.3411, -0.6110, -2.0911],
         [ 1.2856,  0.5431, -1.7813, -1.2636]],

        [[ 0.2611, -1.6730,  0.8805, -1.2368],
         [ 0.9056, -1.6026,  0.8037, -0.0968],
         [ 0.0798,  0.7070,  0.7029,  1.2827],
         [ 0.4760, -0.3411, -0.6110, -2.0911],
         [ 1.2856,  0.5431, -1.7813, -1.2636]],

        [[ 0.2611, -1.6730,  0.8805, -1.2368],
         [ 0.9056, -1.6026,  0.8037, -0.0968],
         [ 0.0798,  0.7070,  0.7029,  1.2827],
         [ 0.4760, -0.3411, -0.6110, -2.0911],
         [ 1.2856,  0.5431, -1.7813, -1.2636]]])

In [210]:
y

tensor([[ 0.2611, -1.6730,  0.8805, -1.2368],
        [ 0.9056, -1.6026,  0.8037, -0.0968],
        [ 0.0798,  0.7070,  0.7029,  1.2827],
        [ 0.4760, -0.3411, -0.6110, -2.0911],
        [ 1.2856,  0.5431, -1.7813, -1.2636]])

In [211]:
y[0] = 0

In [212]:
y

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.9056, -1.6026,  0.8037, -0.0968],
        [ 0.0798,  0.7070,  0.7029,  1.2827],
        [ 0.4760, -0.3411, -0.6110, -2.0911],
        [ 1.2856,  0.5431, -1.7813, -1.2636]])

In [213]:
x[0]

tensor([[ 0.2611, -1.6730,  0.8805, -1.2368],
        [ 0.9056, -1.6026,  0.8037, -0.0968],
        [ 0.0798,  0.7070,  0.7029,  1.2827],
        [ 0.4760, -0.3411, -0.6110, -2.0911],
        [ 1.2856,  0.5431, -1.7813, -1.2636]])

In [214]:
tuple(x.size())

(10, 5, 4)

In [215]:
list(y.size())

[5, 4]

In [216]:
x = torch.randn(4, 5)
A = torch.Tensor(torch.ones(2, 5)).requires_grad_()
y = x @ A.t()

In [217]:
y

tensor([[-0.0106, -0.0106],
        [-1.5656, -1.5656],
        [ 3.5710,  3.5710],
        [ 1.8564,  1.8564]], grad_fn=<MmBackward0>)

In [218]:
mask = torch.zeros_like(y)
mask[0][0] = 1.
y = y * mask
z = y.sum()

In [219]:
z

tensor(-0.0106, grad_fn=<SumBackward0>)

In [220]:
z.backward(retain_graph=True)

In [221]:
A.grad

tensor([[ 0.8339,  0.2999, -0.4332, -0.4029, -0.3084],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])

In [222]:
A

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)

In [223]:
x

tensor([[ 0.8339,  0.2999, -0.4332, -0.4029, -0.3084],
        [ 0.2644,  0.1852, -0.1659,  0.2319, -2.0811],
        [ 3.1821,  0.8301, -1.0467, -0.6358,  1.2415],
        [ 1.3403, -0.1496,  1.1866,  0.8511, -1.3719]])

In [224]:
torch.Tensor([3, 4])

tensor([3., 4.])

In [225]:
torch.Tensor(3, 4)

tensor([[-8.4212e+26,  3.0934e-41, -8.4209e+26,  3.0934e-41],
        [ 1.1210e-43,  0.0000e+00,  8.9683e-44,  0.0000e+00],
        [-8.3748e+26,  3.0934e-41,  1.1351e-43,  0.0000e+00]])

In [226]:
torch.DoubleTensor([3.])

tensor([3.], dtype=torch.float64)

In [227]:
torch.IntTensor([5])

tensor([5], dtype=torch.int32)

In [228]:
torch.LongTensor(5), torch.LongTensor(5).dtype

(tensor([140035826068784, 140035826068784,              32,             128,
                       0]),
 torch.int64)

In [229]:
torch.LongTensor(5)

tensor([140035826068800, 140035826068800,              32,             112,
         94815304830160])

In [230]:
torch.manual_seed(10)
x = torch.randn(3, 2, 4)
y = torch.triu(x, 0)
x, "---", y, x.shape, y.shape

(tensor([[[-0.8173, -0.5556, -0.8267, -1.2970],
          [-0.1974, -0.9643, -0.5133,  2.6278]],
 
         [[ 0.0178, -0.1282, -0.0944,  0.0526],
          [ 0.2386, -1.5565,  1.6471, -1.0891]],
 
         [[-0.1460, -0.2311, -0.4995,  0.3127],
          [-0.0772,  0.3426, -0.7574, -1.5660]]]),
 '---',
 tensor([[[-0.8173, -0.5556, -0.8267, -1.2970],
          [ 0.0000, -0.9643, -0.5133,  2.6278]],
 
         [[ 0.0178, -0.1282, -0.0944,  0.0526],
          [ 0.0000, -1.5565,  1.6471, -1.0891]],
 
         [[-0.1460, -0.2311, -0.4995,  0.3127],
          [ 0.0000,  0.3426, -0.7574, -1.5660]]]),
 torch.Size([3, 2, 4]),
 torch.Size([3, 2, 4]))

In [231]:
torch.manual_seed(10)
x = torch.randn(3, 2, 4)
y = torch.triu(x, 1)
x, "---", y, x.shape, y.shape

(tensor([[[-0.8173, -0.5556, -0.8267, -1.2970],
          [-0.1974, -0.9643, -0.5133,  2.6278]],
 
         [[ 0.0178, -0.1282, -0.0944,  0.0526],
          [ 0.2386, -1.5565,  1.6471, -1.0891]],
 
         [[-0.1460, -0.2311, -0.4995,  0.3127],
          [-0.0772,  0.3426, -0.7574, -1.5660]]]),
 '---',
 tensor([[[ 0.0000, -0.5556, -0.8267, -1.2970],
          [ 0.0000,  0.0000, -0.5133,  2.6278]],
 
         [[ 0.0000, -0.1282, -0.0944,  0.0526],
          [ 0.0000,  0.0000,  1.6471, -1.0891]],
 
         [[ 0.0000, -0.2311, -0.4995,  0.3127],
          [ 0.0000,  0.0000, -0.7574, -1.5660]]]),
 torch.Size([3, 2, 4]),
 torch.Size([3, 2, 4]))

In [232]:
torch.empty(0)

tensor([])

In [233]:
torch.empty(0).dtype

torch.float32

In [234]:
dim = 5
torch.triu(torch.zeros([dim, dim]).float().fill_(float("-inf")), 1), torch.exp(torch.triu(torch.zeros([dim, dim]).float().fill_(float("-inf")), 1))

(tensor([[0., -inf, -inf, -inf, -inf],
         [0., 0., -inf, -inf, -inf],
         [0., 0., 0., -inf, -inf],
         [0., 0., 0., 0., -inf],
         [0., 0., 0., 0., 0.]]),
 tensor([[1., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0.],
         [1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 0.],
         [1., 1., 1., 1., 1.]]))

In [235]:
x.dtype

torch.float32

In [236]:
x = x.to(torch.float64)

In [237]:
x.dtype

torch.float64

In [238]:
y.dtype

torch.float32

In [239]:
y = y.to(x)

In [240]:
y.dtype

torch.float64

In [241]:
x = torch.randn(5).requires_grad_()
y = x.sum()
y.backward()
x.grad


tensor([1., 1., 1., 1., 1.])

In [242]:
x = torch.randn(5).requires_grad_()
z = x + 5
z += x
y = z.sum()
y.backward()
x.grad

tensor([2., 2., 2., 2., 2.])

In [243]:
z = torch.randn(5)

x = torch.randn(5).requires_grad_()
z += x
y = z.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1., 1.])

In [244]:
torch.randn(())

tensor(-2.0651)

In [245]:
x

tensor([ 1.8899, -0.5093,  0.2018,  1.3687,  0.3852], requires_grad=True)

In [246]:
x.grad


tensor([1., 1., 1., 1., 1.])

In [247]:
x = x - 0.1 * x.grad

In [248]:
x

tensor([ 1.7899, -0.6093,  0.1018,  1.2687,  0.2852], grad_fn=<SubBackward0>)

In [249]:
x.grad

/tmp/ipykernel_26274/3730140797.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:486.)
  x.grad


In [250]:
x

tensor([ 1.7899, -0.6093,  0.1018,  1.2687,  0.2852], grad_fn=<SubBackward0>)

In [251]:
x.dim()

1

In [252]:
torch.tensor(5).dim()

0

In [253]:
-torch.inf + torch.tensor(5)

tensor(-inf)

In [254]:
-torch.inf * torch.tensor(0)

tensor(nan)

In [255]:
torch.randn(4, 5, 2) + torch.randn(5, 1)

tensor([[[ 0.8144,  0.1437],
         [ 0.4803, -1.0208],
         [-1.2641, -1.6355],
         [ 1.2382,  2.2412],
         [-2.5275,  0.5352]],

        [[ 1.4880, -1.8960],
         [ 0.8885, -0.0039],
         [-0.5104,  1.4639],
         [ 0.6361, -0.4052],
         [-0.5050, -0.6000]],

        [[ 0.9122,  1.1021],
         [ 1.3025,  0.1595],
         [-2.5788, -2.0133],
         [ 1.3553,  1.8816],
         [-0.4043,  0.8875]],

        [[ 1.4468,  1.7470],
         [ 2.0174,  1.1222],
         [-0.7440,  0.0533],
         [ 0.9224,  0.8589],
         [ 0.4049, -0.0221]]])

In [256]:
x = torch.randn(4, 5, 6)
y = x.expand(2, -1, -1, 6,)
x.shape, y.shape

(torch.Size([4, 5, 6]), torch.Size([2, 4, 5, 6]))

In [257]:
x = torch.randn(4, 5, 6)
y = x.expand(3, 2, -1,-1, 6,)
x.shape, y.shape

(torch.Size([4, 5, 6]), torch.Size([3, 2, 4, 5, 6]))

In [258]:
x = torch.bernoulli(torch.randn(5), 0.5)
x

tensor([1., 1., 1., 0., 0.])

In [259]:
x.new_zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [260]:
cur_device = torch.cuda.current_device()

In [261]:
cur_device

0

In [262]:
prop = torch.cuda.get_device_properties("cuda:{}".format(cur_device))
prop

_CudaDeviceProperties(name='NVIDIA TITAN RTX', major=7, minor=5, total_memory=24211MB, multi_processor_count=72)

In [263]:
prop.total_memory

25387401216

In [264]:
prop.total_memory / 1024 / 1024 /1024

23.64385986328125

In [265]:
torch.cuda.memory_usage(cur_device)

1

In [266]:
x

tensor([1., 1., 1., 0., 0.])

In [267]:
x  = torch.randn(10)
x[0] = 0.0

In [268]:
x

tensor([ 0.0000, -1.3141,  0.4699,  0.4385,  0.1432,  1.0163, -0.2541,  0.8300,
        -1.0317, -0.7860])

In [269]:
F.threshold(x, 0, -99)

tensor([-99.0000, -99.0000,   0.4699,   0.4385,   0.1432,   1.0163, -99.0000,
          0.8300, -99.0000, -99.0000])

In [270]:
x.reshape(-1, 5).ravel()

tensor([ 0.0000, -1.3141,  0.4699,  0.4385,  0.1432,  1.0163, -0.2541,  0.8300,
        -1.0317, -0.7860])

In [271]:
x.reshape(-1, 5).numel()

10

In [272]:
x = torch.randn(5, 4)

In [273]:
x.size()

torch.Size([5, 4])

In [274]:
x.new(2, 1).shape

torch.Size([2, 1])

In [275]:
x.new(2, 1)

tensor([[-8.4100e+26],
        [ 3.0934e-41]])

In [276]:
x.new(2, 1, 5, 8).shape

torch.Size([2, 1, 5, 8])

In [277]:
x.new(2, 1, 5, 8)

tensor([[[[-8.4260e+26,  3.0934e-41, -1.1599e-18,  4.5688e-41, -8.1638e-26,
            4.5688e-41,  0.0000e+00,  0.0000e+00],
          [-8.4259e+26,  3.0934e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,
            0.0000e+00,  1.4013e-45,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  1.9618e-44,  1.4013e-45,  0.0000e+00,
            0.0000e+00,  1.7096e-43,  1.1491e-43],
          [ 0.0000e+00,  4.5687e-41, -1.2333e+11,  4.5687e-41, -1.2333e+11,
            4.5687e-41, -9.3320e-38,  4.5687e-41],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00, -1.2347e+11,
            4.5687e-41,  0.0000e+00,  0.0000e+00]]],


        [[[ 0.0000e+00,  0.0000e+00, -1.3345e+20,  3.0934e-41,  7.0065e-45,
            0.0000e+00, -3.1196e-18,  4.5688e-41],
          [-2.9032e-18,  4.5688e-41, -1.2333e+11,  4.5687e-41, -1.2333e+11,
            4.5687e-41, -9.3320e-38,  4.5687e-41],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00, -1.2347e+11,
            4.5687e-41,  0.0000

In [278]:
x = torch.tensor([[1], [2], [3]])

In [279]:
y = x.expand(3, 4)

In [280]:
x[0][0] = -1

In [281]:
y

tensor([[-1, -1, -1, -1],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3]])

In [282]:
torch.rand(1).item()

0.420911967754364

In [283]:
x

tensor([[-1],
        [ 2],
        [ 3]])

In [284]:
x.new(0)

tensor([], dtype=torch.int64)

In [285]:
x.new_empty(0)

tensor([], dtype=torch.int64)

In [286]:
x.new_empty(0, 1)

tensor([], size=(0, 1), dtype=torch.int64)

In [287]:
tz, bz, sz, num_head, head_dim = 4, 32, 6, 2, 8
torch.manual_seed(0)
q = torch.randn(bz, tz, num_head * head_dim)
k = torch.randn(bz, sz, num_head * head_dim)
v = torch.randn(bz, sz, num_head * head_dim)

In [288]:
q.shape, k.shape, v.shape

(torch.Size([32, 4, 16]), torch.Size([32, 6, 16]), torch.Size([32, 6, 16]))

In [289]:
_q = q.transpose(0, 1).contiguous().view(tz, bz * num_head, head_dim).transpose(0, 1)#.contiguous()
_k = k.transpose(0, 1).contiguous().view(sz, bz * num_head, head_dim).transpose(0, 1)#.contiguous()
_v = v.transpose(0, 1).contiguous().view(sz, bz * num_head, head_dim).transpose(0, 1)#.contiguous()
_q.sum(), _k.sum(), _v.sum()

(tensor(27.1336), tensor(-65.7946), tensor(-28.6850))

In [290]:
_q.shape, _k.shape, _v.shape

(torch.Size([64, 4, 8]), torch.Size([64, 6, 8]), torch.Size([64, 6, 8]))

In [291]:
qk = torch.matmul(_q, _k.transpose(1, 2))

In [292]:
qk.shape

torch.Size([64, 4, 6])

In [293]:
qk.sum()

tensor(48.4539)

In [294]:
weights = F.softmax(qk, dim=-1)
weights.shape

torch.Size([64, 4, 6])

In [295]:
weights.sum(axis=-1)[:2]

tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000]])

In [296]:
attn = torch.matmul(weights, _v)
attn.shape, q.shape

(torch.Size([64, 4, 8]), torch.Size([32, 4, 16]))

In [297]:
attn = attn.transpose(0, 1).view(tz, bz, num_head, -1)

In [298]:
attn.shape

torch.Size([4, 32, 2, 8])

In [299]:
attn.sum()

tensor(-57.9944)

In [300]:
attn[2][0]

tensor([[ 0.5265, -0.1538, -1.3277,  0.4612, -0.5305, -1.4538,  0.1661, -0.6279],
        [-1.3330,  0.4727, -1.1413,  0.0799, -0.6708, -0.8198, -0.1158, -1.4448]])

In [301]:
q.shape, k.shape, v.shape

(torch.Size([32, 4, 16]), torch.Size([32, 6, 16]), torch.Size([32, 6, 16]))

In [302]:
_q = q.view(bz, tz, num_head, head_dim).transpose(1, 2).contiguous()
_v = v.view(bz, sz, num_head, head_dim).transpose(1, 2).contiguous()
_k = k.view(bz, sz, num_head, head_dim).transpose(1, 2).contiguous()
_q.sum(), _k.sum(), _v.sum()


(tensor(27.1336), tensor(-65.7946), tensor(-28.6850))

In [303]:
qk = torch.einsum('bhtd, bhsd -> bhts', _q, _k)

In [304]:
qk.sum()

tensor(48.4539)

In [305]:
weights = F.softmax(qk, dim=-1)

In [306]:
weights.sum(dim=-1)[0]

tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000]])

In [307]:
weights.shape

torch.Size([32, 2, 4, 6])

In [308]:
attn = torch.einsum('bhts, bhsd -> bhtd', weights, _v)

In [309]:
attn.sum()

tensor(-57.9944)

In [310]:
attn.shape

torch.Size([32, 2, 4, 8])

In [311]:
attn[0, :, 2]

tensor([[ 0.5265, -0.1538, -1.3277,  0.4612, -0.5305, -1.4538,  0.1661, -0.6279],
        [-1.3330,  0.4727, -1.1413,  0.0799, -0.6708, -0.8198, -0.1158, -1.4448]])

In [312]:
torch.triu(torch.tensor([[4., 5.], [6.0, 7.0]]), 0)

tensor([[4., 5.],
        [0., 7.]])

In [313]:
y = x.float()

In [314]:
y.dtype

torch.float32

In [315]:
y = y.half()

In [316]:
y.dtype

torch.float16

In [317]:
z = y.float()

In [318]:
z.dtype

torch.float32

In [319]:
y =x.clone()

In [320]:
y[0] = 0
y, x

(tensor([[0],
         [2],
         [3]]),
 tensor([[-1],
         [ 2],
         [ 3]]))

In [321]:
z =x.expand(2, -1, -1)
z

tensor([[[-1],
         [ 2],
         [ 3]],

        [[-1],
         [ 2],
         [ 3]]])

In [322]:
x[0][0] = 4

In [323]:
z

tensor([[[4],
         [2],
         [3]],

        [[4],
         [2],
         [3]]])

In [324]:
x = x.cuda()

In [325]:
z = x.clone()

In [326]:
z

tensor([[4],
        [2],
        [3]], device='cuda:0')

In [327]:
u = z.new_empty(0)
u

tensor([], device='cuda:0', dtype=torch.int64)

In [328]:
u.size(), z.size()

(torch.Size([0]), torch.Size([3, 1]))

In [329]:
torch.cat([z, u], 1)

tensor([[4],
        [2],
        [3]], device='cuda:0')

In [330]:
x = torch.randn(5, 4)

In [331]:
x

tensor([[ 0.2652, -0.7908,  0.9808, -0.1746],
        [ 0.7809,  0.1765,  0.6721, -0.9734],
        [ 1.0928, -0.9968, -0.6994, -1.3530],
        [ 1.1896,  0.0035, -0.2285, -0.0105],
        [ 0.3985,  1.1669, -1.8245,  0.1341]])

In [332]:
y = x[:, :1]
y

tensor([[0.2652],
        [0.7809],
        [1.0928],
        [1.1896],
        [0.3985]])

In [333]:
y[:, 0] = 5
y

tensor([[5.],
        [5.],
        [5.],
        [5.],
        [5.]])

In [334]:
x

tensor([[ 5.0000e+00, -7.9081e-01,  9.8081e-01, -1.7459e-01],
        [ 5.0000e+00,  1.7653e-01,  6.7213e-01, -9.7336e-01],
        [ 5.0000e+00, -9.9680e-01, -6.9938e-01, -1.3530e+00],
        [ 5.0000e+00,  3.4749e-03, -2.2855e-01, -1.0477e-02],
        [ 5.0000e+00,  1.1669e+00, -1.8245e+00,  1.3407e-01]])

In [336]:
x * 2

tensor([[ 1.0000e+01, -1.5816e+00,  1.9616e+00, -3.4918e-01],
        [ 1.0000e+01,  3.5307e-01,  1.3443e+00, -1.9467e+00],
        [ 1.0000e+01, -1.9936e+00, -1.3988e+00, -2.7060e+00],
        [ 1.0000e+01,  6.9498e-03, -4.5709e-01, -2.0953e-02],
        [ 1.0000e+01,  2.3338e+00, -3.6491e+00,  2.6814e-01]])

In [340]:
torch._foreach_mul((x ,), 2.)

(tensor([[ 1.0000e+01, -1.5816e+00,  1.9616e+00, -3.4918e-01],
         [ 1.0000e+01,  3.5307e-01,  1.3443e+00, -1.9467e+00],
         [ 1.0000e+01, -1.9936e+00, -1.3988e+00, -2.7060e+00],
         [ 1.0000e+01,  6.9498e-03, -4.5709e-01, -2.0953e-02],
         [ 1.0000e+01,  2.3338e+00, -3.6491e+00,  2.6814e-01]]),)

In [341]:
torch._foreach_mul((x ,), torch.tensor(2.))

(tensor([[ 1.0000e+01, -1.5816e+00,  1.9616e+00, -3.4918e-01],
         [ 1.0000e+01,  3.5307e-01,  1.3443e+00, -1.9467e+00],
         [ 1.0000e+01, -1.9936e+00, -1.3988e+00, -2.7060e+00],
         [ 1.0000e+01,  6.9498e-03, -4.5709e-01, -2.0953e-02],
         [ 1.0000e+01,  2.3338e+00, -3.6491e+00,  2.6814e-01]]),)

In [345]:
torch._foreach_mul((x , x), (torch.tensor(2.0), torch.tensor(3.0),))

(tensor([[ 1.0000e+01, -1.5816e+00,  1.9616e+00, -3.4918e-01],
         [ 1.0000e+01,  3.5307e-01,  1.3443e+00, -1.9467e+00],
         [ 1.0000e+01, -1.9936e+00, -1.3988e+00, -2.7060e+00],
         [ 1.0000e+01,  6.9498e-03, -4.5709e-01, -2.0953e-02],
         [ 1.0000e+01,  2.3338e+00, -3.6491e+00,  2.6814e-01]]),
 tensor([[ 1.5000e+01, -2.3724e+00,  2.9424e+00, -5.2377e-01],
         [ 1.5000e+01,  5.2960e-01,  2.0164e+00, -2.9201e+00],
         [ 1.5000e+01, -2.9904e+00, -2.0981e+00, -4.0591e+00],
         [ 1.5000e+01,  1.0425e-02, -6.8564e-01, -3.1430e-02],
         [ 1.5000e+01,  3.5008e+00, -5.4736e+00,  4.0222e-01]]))

In [350]:
torch.stack([torch.tensor(2), torch.tensor(6)], 0)

tensor([2, 6])

In [351]:
torch.stack([torch.tensor([2]), torch.tensor([6])], 0)

tensor([[2],
        [6]])

In [353]:
y = {x: 5}

In [355]:
hash(x)

140032206180496

In [356]:
4088192 // 64

63878

In [ ]:
lr2 = 1e-3
lr1 = 5e-5
s = 1000
c = 5
ratio = np.log(lr2 / (lr2 - lr1))
a = 1000. / (c - ratio)
b = a * ratio
x = np.arange(1, 1001)
y = lr2 * ( 1 - np.exp(-(x + b) / a ))
fig, ax = plt.subplots()
ax.plot(x, y)