In [1]:
import torch
import numpy as np
import array
import math
from torch import nn
import torch.nn.functional as F


In [2]:
math.ceil(-2.2)

-2

In [3]:
torch.arange(10)[None, None, :]

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [4]:
net = nn.LazyLinear(256)

/home/mtb/env/lib/python3.9/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [5]:
net.weight.size()

torch.Size([0])

In [6]:
x = torch.randn((10, 30))

In [7]:
y = net(x)

In [8]:
y.shape

torch.Size([10, 256])

In [9]:
net.weight.shape

torch.Size([256, 30])

In [10]:
x.to(device='cuda:0') 

tensor([[-0.0711, -0.7287, -0.8962,  0.3501,  2.1428,  0.6574, -1.3410,  0.5911,
          0.8452,  0.3379, -0.8423, -0.1479, -0.9323,  0.9383,  1.5864,  2.0727,
          0.1437,  1.6896,  0.0109,  0.6179,  0.5501, -0.6179, -0.7571, -0.4760,
         -2.3076,  1.1079,  0.3161, -0.2823,  0.3467, -1.8149],
        [-0.2055, -1.1561, -0.4401,  0.3473,  2.9118,  0.4501,  0.2212,  0.2409,
          1.1135, -0.8555, -1.7724, -1.9532,  1.1647,  0.7096, -1.3412,  0.7407,
          1.1381, -0.4520,  0.9520,  1.1187,  0.4615, -0.6393,  0.2202,  1.6608,
          1.1580,  0.5205, -2.2525, -0.7301,  0.4007,  1.9229],
        [ 0.3897,  0.0173, -0.5648, -0.1991, -0.8437, -0.0175, -0.1718, -0.7723,
          0.6423, -0.1824, -0.8979, -0.3881, -0.1498,  0.1611,  0.9230,  0.5203,
          1.1053,  0.0172,  0.2584, -2.8764, -0.2554, -0.4132,  0.2866, -0.7340,
         -1.7117, -1.2503, -0.7841,  1.0536,  1.6874,  1.3148],
        [-0.1994,  1.1508,  0.1899,  0.1986,  1.2227, -0.8071,  1.1322, -0.8977

In [11]:
x.device

device(type='cpu')

In [12]:
torch.manual_seed(10)
x = torch.empty((10, 5000)).uniform_(-4, 4)

In [13]:
y = x.clone()

In [14]:
torch.normal(0., 1., size=(10, 5000))

tensor([[-0.3695,  0.2178, -0.8544,  ..., -0.5767,  0.0687,  0.9357],
        [ 0.7685, -1.7597, -0.5440,  ...,  0.0067, -0.1785, -0.2007],
        [-1.3787,  1.0032,  1.5139,  ..., -0.0311, -0.7310, -0.7357],
        ...,
        [-0.6211,  1.6740,  1.3860,  ..., -0.3418, -0.1636, -0.1092],
        [ 1.5157, -0.0277,  0.8166,  ...,  1.1793,  0.7833, -0.5789],
        [-0.3016,  1.0526,  0.3381,  ..., -0.3096,  0.3056, -1.4316]])

In [15]:
x.normal_(0, 1)

tensor([[ 0.3510,  1.1682,  1.3972,  ..., -0.5403, -1.8046,  1.1958],
        [ 1.4531, -0.5814, -0.5592,  ..., -2.4647,  0.2427, -0.5404],
        [ 0.0337,  0.9904, -0.9932,  ..., -2.0111, -0.2497,  1.1261],
        ...,
        [-0.3714,  1.3240, -0.1600,  ..., -1.9292,  1.6265,  0.3676],
        [ 0.6357,  0.2587,  0.5304,  ..., -1.2510,  0.8620,  1.0873],
        [ 0.4514, -0.1732,  0.4199,  ...,  0.6106,  1.2206, -1.0866]])

In [16]:
x.normal_(0, 1)

tensor([[ 0.3887, -0.0518, -0.6590,  ..., -0.3228,  0.7122, -1.4934],
        [ 1.3387,  2.3876,  0.5639,  ...,  0.8801, -0.1235, -0.5796],
        [ 1.4232, -0.8363,  0.4545,  ...,  0.4513, -0.0427, -0.6412],
        ...,
        [ 0.0268,  0.0838, -0.0644,  ...,  0.5830, -0.5323, -0.2533],
        [ 0.1744,  0.6938, -0.6699,  ..., -0.5077, -0.0810,  0.5587],
        [ 0.1309,  0.6458,  1.9199,  ...,  0.8345, -1.2508,  0.6531]])

In [17]:
x

tensor([[ 0.3887, -0.0518, -0.6590,  ..., -0.3228,  0.7122, -1.4934],
        [ 1.3387,  2.3876,  0.5639,  ...,  0.8801, -0.1235, -0.5796],
        [ 1.4232, -0.8363,  0.4545,  ...,  0.4513, -0.0427, -0.6412],
        ...,
        [ 0.0268,  0.0838, -0.0644,  ...,  0.5830, -0.5323, -0.2533],
        [ 0.1744,  0.6938, -0.6699,  ..., -0.5077, -0.0810,  0.5587],
        [ 0.1309,  0.6458,  1.9199,  ...,  0.8345, -1.2508,  0.6531]])

In [18]:
x.sum((-1)) / 5000

tensor([ 0.0124, -0.0021,  0.0146, -0.0086,  0.0119, -0.0051,  0.0012,  0.0191,
         0.0050,  0.0265])

In [19]:
y - y.mean(axis=(1, ), keepdim=True), y -  y.sum() / 50000

(tensor([[-0.3817, -0.1835, -1.5463,  ..., -2.1051, -1.2046,  3.5418],
         [ 3.8134,  2.7599, -3.0942,  ..., -3.6861,  3.3261, -3.9601],
         [-2.9215, -3.5598, -2.8361,  ..., -3.5278,  0.1972, -0.7693],
         ...,
         [-0.8184, -3.0790,  2.2531,  ..., -3.7783, -3.3329,  1.3009],
         [ 3.3563,  1.7762,  0.0914,  ...,  0.9927,  1.0587, -1.5650],
         [ 3.8360,  0.8514, -2.5571,  ...,  3.6733,  0.1638,  2.8013]]),
 tensor([[-0.3500, -0.1518, -1.5146,  ..., -2.0734, -1.1729,  3.5735],
         [ 3.7703,  2.7168, -3.1373,  ..., -3.7292,  3.2830, -4.0032],
         [-2.9363, -3.5746, -2.8509,  ..., -3.5426,  0.1824, -0.7841],
         ...,
         [-0.7874, -3.0481,  2.2840,  ..., -3.7473, -3.3019,  1.3318],
         [ 3.3932,  1.8130,  0.1283,  ...,  1.0296,  1.0956, -1.5282],
         [ 3.8346,  0.8500, -2.5585,  ...,  3.6719,  0.1623,  2.7999]]))

In [20]:
z = y.sum(axis=-1, keepdim=True) / 5000

In [21]:
w = y - z

In [22]:
w.mean(axis=(-1))

tensor([ 5.7602e-08, -7.6294e-08,  1.2207e-08,  2.1362e-08, -3.3569e-08,
        -3.0518e-08, -5.2643e-08,  4.5776e-08,  4.5776e-08,  2.5177e-08])

In [23]:
w + 2

tensor([[ 1.6183,  1.8165,  0.4537,  ..., -0.1051,  0.7954,  5.5418],
        [ 5.8134,  4.7599, -1.0942,  ..., -1.6861,  5.3261, -1.9601],
        [-0.9215, -1.5598, -0.8361,  ..., -1.5278,  2.1972,  1.2307],
        ...,
        [ 1.1816, -1.0790,  4.2531,  ..., -1.7783, -1.3329,  3.3009],
        [ 5.3563,  3.7762,  2.0914,  ...,  2.9927,  3.0587,  0.4350],
        [ 5.8360,  2.8514, -0.5571,  ...,  5.6733,  2.1638,  4.8013]])

In [24]:
torch.manual_seed(10)
x = torch.empty((10, 5, 10, 5000)).uniform_(-4, 4)

In [25]:
x.mean(axis=(-1, -2))

tensor([[ 0.0146,  0.0002, -0.0002, -0.0103,  0.0040],
        [ 0.0043, -0.0058,  0.0041,  0.0007,  0.0131],
        [-0.0122,  0.0037, -0.0264, -0.0108, -0.0075],
        [ 0.0198, -0.0003, -0.0140,  0.0062, -0.0056],
        [-0.0018,  0.0028,  0.0114, -0.0059, -0.0080],
        [ 0.0002, -0.0061, -0.0109, -0.0079, -0.0001],
        [ 0.0123, -0.0162,  0.0010,  0.0027, -0.0017],
        [-0.0154, -0.0113, -0.0122,  0.0016, -0.0126],
        [ 0.0298,  0.0111, -0.0063,  0.0095, -0.0102],
        [-0.0012,  0.0038, -0.0087,  0.0119, -0.0023]])

MLP

In [26]:
net = nn.Linear(4, 10)

In [27]:
x = torch.randn(2, 4)

In [28]:
y = net(x)
y.shape

torch.Size([2, 10])

In [29]:
y

tensor([[-0.5986,  0.2001,  1.2537,  0.5834, -0.5716,  0.2312,  0.0540,  0.0463,
         -0.3411,  0.3042],
        [-0.4324,  0.1083, -0.6668, -0.4291, -0.7299, -0.0870, -1.0466,  0.3723,
         -0.6390, -0.0645]], grad_fn=<AddmmBackward0>)

In [30]:
net.weight

Parameter containing:
tensor([[ 0.0322, -0.0182, -0.4234, -0.4418],
        [ 0.4645, -0.0485,  0.1915,  0.4401],
        [-0.2199,  0.2342, -0.1968,  0.4420],
        [-0.3294, -0.1101, -0.0606,  0.2784],
        [-0.4155,  0.4957, -0.1378, -0.4509],
        [-0.2811,  0.3955, -0.3359, -0.4654],
        [ 0.0860,  0.1035, -0.4661,  0.0312],
        [ 0.4474,  0.0618,  0.0999,  0.1228],
        [ 0.0265,  0.4594,  0.2514,  0.1779],
        [ 0.1866,  0.4216,  0.1418,  0.1924]], requires_grad=True)

In [31]:
net.weight.shape

torch.Size([10, 4])

In [32]:
torch.matmul(x, net.weight.T) + net.bias

tensor([[-0.5986,  0.2001,  1.2537,  0.5834, -0.5716,  0.2312,  0.0540,  0.0463,
         -0.3411,  0.3042],
        [-0.4324,  0.1083, -0.6668, -0.4291, -0.7299, -0.0870, -1.0466,  0.3723,
         -0.6390, -0.0645]], grad_fn=<AddBackward0>)

In [33]:
torch.einsum('bj, ij -> bi', x, net.weight) + net.bias

tensor([[-0.5986,  0.2001,  1.2537,  0.5834, -0.5716,  0.2312,  0.0540,  0.0463,
         -0.3411,  0.3042],
        [-0.4324,  0.1083, -0.6668, -0.4291, -0.7299, -0.0870, -1.0466,  0.3723,
         -0.6390, -0.0645]], grad_fn=<AddBackward0>)

In [34]:
import torch.nn.functional as F

In [35]:
F.linear(x, net.weight, net.bias)

tensor([[-0.5986,  0.2001,  1.2537,  0.5834, -0.5716,  0.2312,  0.0540,  0.0463,
         -0.3411,  0.3042],
        [-0.4324,  0.1083, -0.6668, -0.4291, -0.7299, -0.0870, -1.0466,  0.3723,
         -0.6390, -0.0645]], grad_fn=<AddmmBackward0>)

In [36]:
torch.manual_seed(42)
net = nn.Sequential()
net.add_module('lin1', nn.Linear(32, 64))
net.add_module('lin2', nn.Linear(64, 10))

In [37]:
x = torch.randn((4, 32))

In [38]:
y = net(x)
y[0], y.shape


(tensor([-0.0630, -0.0022, -0.0127, -0.3661,  0.0866,  0.0741,  0.0963,  0.1773,
         -0.0797,  0.3435], grad_fn=<SelectBackward0>),
 torch.Size([4, 10]))

In [39]:
z = net.lin2(net.lin1(x))
z[0]

tensor([-0.0630, -0.0022, -0.0127, -0.3661,  0.0866,  0.0741,  0.0963,  0.1773,
        -0.0797,  0.3435], grad_fn=<SelectBackward0>)

In [40]:
net.state_dict().keys()

odict_keys(['lin1.weight', 'lin1.bias', 'lin2.weight', 'lin2.bias'])

In [41]:
x = torch.randn(20, 10, 4, 32)
y = net(x)
y.shape

torch.Size([20, 10, 4, 10])

In [42]:
x = torch.empty((4, 5)).uniform_(-10, 10)

In [43]:
x

tensor([[ 9.6053,  6.1465, -3.9468, -6.8474,  6.5705],
        [ 7.9896,  7.8190, -2.3512,  7.2122,  8.1273],
        [ 7.9416,  9.6219, -9.1863,  9.3812,  7.5133],
        [ 2.9351,  5.0090,  1.0653, -6.3083,  4.4218]])

In [44]:
bn = nn.BatchNorm1d(x.shape[1])
y = bn(x)

In [45]:
bn.weight, bn.bias, bn.weight.shape, bn.bias.size()

(Parameter containing:
 tensor([1., 1., 1., 1., 1.], requires_grad=True),
 Parameter containing:
 tensor([0., 0., 0., 0., 0.], requires_grad=True),
 torch.Size([5]),
 torch.Size([5]))

In [46]:
y, y.mean(dim=0), y.std(0)

(tensor([[ 0.9926, -0.5753, -0.0925, -1.0304, -0.0625],
         [ 0.3478,  0.3844,  0.3391,  0.8494,  1.0455],
         [ 0.3287,  1.4189, -1.5100,  1.1394,  0.6085],
         [-1.6691, -1.2280,  1.2634, -0.9584, -1.5915]],
        grad_fn=<NativeBatchNormBackward0>),
 tensor([ 5.9605e-08,  5.9605e-08,  5.9605e-08, -1.4901e-08, -1.4901e-07],
        grad_fn=<MeanBackward1>),
 tensor([1.1547, 1.1547, 1.1547, 1.1547, 1.1547], grad_fn=<StdBackward0>))

In [47]:
x.mean(dim=0)

tensor([ 7.1179,  7.1491, -3.6047,  0.8594,  6.6582])

In [48]:
(x - x.mean(dim=0)) / (x.std(dim=0) + 1e-9)

tensor([[ 0.8596, -0.4982, -0.0801, -0.8924, -0.0541],
        [ 0.3012,  0.3329,  0.2937,  0.7356,  0.9054],
        [ 0.2846,  1.2288, -1.3077,  0.9868,  0.5270],
        [-1.4455, -1.0635,  1.0942, -0.8300, -1.3783]])

In [49]:
x = torch.randint(0, 4, (3, 2, 4))
x

tensor([[[3, 3, 3, 1],
         [3, 1, 1, 3]],

        [[0, 0, 2, 3],
         [2, 3, 2, 1]],

        [[3, 0, 3, 2],
         [2, 2, 2, 2]]])

In [50]:
x.shape, F.one_hot(x, 6).shape, F.one_hot(x, 6)

(torch.Size([3, 2, 4]),
 torch.Size([3, 2, 4, 6]),
 tensor([[[[0, 0, 0, 1, 0, 0],
           [0, 0, 0, 1, 0, 0],
           [0, 0, 0, 1, 0, 0],
           [0, 1, 0, 0, 0, 0]],
 
          [[0, 0, 0, 1, 0, 0],
           [0, 1, 0, 0, 0, 0],
           [0, 1, 0, 0, 0, 0],
           [0, 0, 0, 1, 0, 0]]],
 
 
         [[[1, 0, 0, 0, 0, 0],
           [1, 0, 0, 0, 0, 0],
           [0, 0, 1, 0, 0, 0],
           [0, 0, 0, 1, 0, 0]],
 
          [[0, 0, 1, 0, 0, 0],
           [0, 0, 0, 1, 0, 0],
           [0, 0, 1, 0, 0, 0],
           [0, 1, 0, 0, 0, 0]]],
 
 
         [[[0, 0, 0, 1, 0, 0],
           [1, 0, 0, 0, 0, 0],
           [0, 0, 0, 1, 0, 0],
           [0, 0, 1, 0, 0, 0]],
 
          [[0, 0, 1, 0, 0, 0],
           [0, 0, 1, 0, 0, 0],
           [0, 0, 1, 0, 0, 0],
           [0, 0, 1, 0, 0, 0]]]]))

In [51]:
input = torch.normal(4, 10, size=(10, )).requires_grad_()

In [52]:
input

tensor([-10.9103,   5.8988,  -4.5014,   3.9894,  26.0803,   0.7348,  -1.2472,
          4.5035,  -0.0993,   2.3917], requires_grad=True)

In [53]:
target = torch.randint(0, 2, size=input.size(), dtype=torch.float).requires_grad_()
target

tensor([1., 0., 1., 1., 0., 0., 1., 1., 0., 0.], requires_grad=True)

In [54]:
target

tensor([1., 0., 1., 1., 0., 0., 1., 1., 0., 0.], requires_grad=True)

In [55]:
F.binary_cross_entropy(F.sigmoid(input), target, reduce=None)

tensor(12.7104, grad_fn=<BinaryCrossEntropyBackward0>)

In [56]:
def binary_cross_entropy(input, target):
    mu = nn.Sigmoid()(input)
    
    loss = target * torch.log(mu) + (1 - target) * torch.log( 1 - mu)
    
    return -loss.mean()
    
binary_cross_entropy(input, target)
    

tensor(inf, grad_fn=<NegBackward0>)

In [57]:
target = torch.empty_like(target).uniform_(0, 1).requires_grad_()

In [58]:
target

tensor([0.4711, 0.7032, 0.9075, 0.0051, 0.0616, 0.8857, 0.4707, 0.7001, 0.8452,
        0.8964], requires_grad=True)

In [59]:
F.binary_cross_entropy(F.sigmoid(input), target, reduce=None)

tensor(11.2562, grad_fn=<BinaryCrossEntropyBackward0>)

In [60]:
binary_cross_entropy(input, target)

tensor(inf, grad_fn=<NegBackward0>)

In [61]:
torch.Tensor(25)

tensor([7.5556e+31, 2.1707e-18, 7.0976e+22, 2.1715e-18, 2.8828e+26, 1.9144e+28,
        1.4580e-19, 1.1024e+24, 3.0979e+32, 6.1949e-04, 1.3470e+37, 3.4034e-18,
        4.4656e+30, 1.5766e-19, 2.1707e-18, 3.0958e-18, 1.0310e-08, 5.1380e+31,
        3.3132e-18, 5.1380e+31, 4.2964e+24, 1.7443e+28, 7.5556e+31, 2.8219e+26,
        1.4580e-19])

LSTM

In [62]:
net = nn.LSTM(input_size=128, 
                hidden_size=256,
                num_layers=1, 
                )

In [63]:
inp = torch.randn((64, 32, 128))

In [64]:
out, (hn, cn)= net(inp)

In [65]:
out.shape

torch.Size([64, 32, 256])

In [66]:
hn.shape

torch.Size([1, 32, 256])

In [67]:
h0 = torch.randn((1, 32, 256))
c0 = torch.zeros_like(h0)

In [68]:
out, (hn, cn) = net(inp, (h0, c0))

In [69]:
hn.shape

torch.Size([1, 32, 256])

In [70]:
net = nn.LSTM(input_size=128, 
                hidden_size=256,
                num_layers=1, 
                proj_size=96
                )

In [71]:
h0 = torch.randn((1, 32, 96))
c0 = torch.randn((1, 32, 256))
out, (hn, cn) = net(inp, (h0, c0))

/home/mtb/env/lib/python3.9/site-packages/torch/nn/modules/rnn.py:812: UserWarning: LSTM with projections is not supported with oneDNN. Using default implementation. (Triggered internally at ../aten/src/ATen/native/RNN.cpp:1463.)
  result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,


In [72]:
out.shape

torch.Size([64, 32, 96])

In [73]:
hn.shape

torch.Size([1, 32, 96])

In [74]:
cn.shape

torch.Size([1, 32, 256])

In [75]:
net = nn.LSTM(input_size=128, 
                hidden_size=256,
                num_layers=1, 
                bidirectional=True
                )

In [76]:
out, (hn, cn) = net(inp)

In [77]:
out.shape

torch.Size([64, 32, 512])

In [78]:
hn.shape

torch.Size([2, 32, 256])

In [79]:
cn.shape

torch.Size([2, 32, 256])

In [80]:
net = nn.LSTM(input_size=128, 
                hidden_size=256,
                num_layers=4, 
                bidirectional=True
                )

In [81]:
out, (hn, cn) = net(inp)

In [82]:
out.shape

torch.Size([64, 32, 512])

In [83]:
hn.shape

torch.Size([8, 32, 256])

In [84]:
cn.shape

torch.Size([8, 32, 256])

In [85]:
x = torch.arange(0, 100)

In [86]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [87]:
y = x.view(2, 50)

In [88]:
y+= 1
x, y

(tensor([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
          15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
          29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
          43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
          57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
          71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
          85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
          99, 100]),
 tensor([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
           15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
           29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
           43,  44,  45,  46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
           65,  66,  67,  68,  69,  70,  71,  72,  73, 

In [89]:
y = x.view(20, 5)

In [90]:
y

tensor([[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75],
        [ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]])

In [91]:
y.view(4, 5, -1)

tensor([[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20],
         [ 21,  22,  23,  24,  25]],

        [[ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40],
         [ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50]],

        [[ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60],
         [ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75]],

        [[ 76,  77,  78,  79,  80],
         [ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]]])

In [92]:
net.weight_ih_l0.shape

torch.Size([1024, 128])

In [93]:
emb_net = nn.Embedding(1000, 128, padding_idx=0)

In [94]:
x = torch.randint(0, 1000, size=(64, 20))

In [95]:
x.shape

torch.Size([64, 20])

In [96]:
emb = emb_net(x)

In [97]:
emb.shape

torch.Size([64, 20, 128])

In [98]:
emb[0][0]

tensor([-9.0001e-01, -4.5618e-01, -3.3796e-01,  5.4977e-02,  2.1113e+00,
        -1.2687e+00,  2.2862e+00,  2.0994e+00,  1.1920e-01,  1.9923e-01,
         9.4172e-01, -1.7726e-01,  1.1779e+00,  1.1366e+00, -1.1261e+00,
        -1.3342e+00,  8.5693e-01, -1.9372e+00,  1.7511e+00,  1.1171e+00,
         1.0702e+00,  3.2450e-04,  1.1027e+00,  6.2287e-02, -1.1783e-01,
        -6.0368e-01, -5.4402e-01,  6.4613e-01,  1.1293e+00,  1.0740e+00,
         1.0198e+00,  4.9398e-01,  2.8837e-01,  7.4511e-01, -9.0288e-01,
        -8.9145e-02,  5.0449e-01,  2.2546e+00, -5.8698e-01,  6.1598e-02,
         7.3877e-01, -2.3824e-01, -3.3074e-01,  1.3412e+00,  5.6607e-02,
         7.2386e-01, -1.0868e+00,  3.5732e-01,  2.0704e+00, -2.2176e-01,
        -6.3954e-01, -1.1623e+00, -7.9249e-01, -1.5707e+00,  5.0808e-01,
         1.7823e-01,  4.4992e-01,  2.2511e-01,  1.0701e+00, -1.1095e+00,
         2.1271e-01, -5.1025e-01,  5.1649e-01,  9.7876e-01,  4.2928e-02,
        -3.4780e-01, -4.9096e-01,  9.8162e-01,  8.6

In [99]:
x = torch.randn((10, ))

In [100]:
x

tensor([-0.2459, -0.5377,  0.2185,  0.9448, -0.2103,  0.7507,  1.4196, -0.7844,
        -0.0427, -0.8096])

In [101]:
dropout = nn.Dropout(p=0.2)

In [102]:
y = dropout(x)

In [103]:
y

tensor([-0.0000, -0.6722,  0.0000,  1.1810, -0.2629,  0.9384,  1.7746, -0.9805,
        -0.0534, -1.0119])

In [104]:
x

tensor([-0.2459, -0.5377,  0.2185,  0.9448, -0.2103,  0.7507,  1.4196, -0.7844,
        -0.0427, -0.8096])

In [105]:
x / y

tensor([   inf, 0.8000,    inf, 0.8000, 0.8000, 0.8000, 0.8000, 0.8000, 0.8000,
        0.8000])

In [106]:
y * 0.8

tensor([-0.0000, -0.5377,  0.0000,  0.9448, -0.2103,  0.7507,  1.4196, -0.7844,
        -0.0427, -0.8096])

Pack padding

In [107]:
seqs = ['Long_str', 'tiny', 'medium']

In [108]:
vocab = ['<pad>'] + sorted(set(c for s in seqs for c in s))

In [109]:
vocab

['<pad>', 'L', '_', 'd', 'e', 'g', 'i', 'm', 'n', 'o', 'r', 's', 't', 'u', 'y']

In [110]:
tok_dict = {c: i for i, c in enumerate(vocab)}

In [111]:
tok_dict

{'<pad>': 0,
 'L': 1,
 '_': 2,
 'd': 3,
 'e': 4,
 'g': 5,
 'i': 6,
 'm': 7,
 'n': 8,
 'o': 9,
 'r': 10,
 's': 11,
 't': 12,
 'u': 13,
 'y': 14}

In [112]:
tensor_seqs = [[tok_dict[c] for c in seq] for seq in seqs ]

In [113]:
tensor_seqs

[[1, 9, 8, 5, 2, 11, 12, 10], [12, 6, 8, 14], [7, 4, 3, 6, 13, 7]]

In [114]:
lengths = [len(s) for s in seqs]

In [115]:
lengths

[8, 4, 6]

In [116]:
seq_tensor = torch.full((len(seqs), max(lengths)),  0)

In [117]:
for i, s in enumerate(tensor_seqs):
    seq_tensor[i, :lengths[i]].copy_(torch.tensor(s))

In [118]:
seq_tensor

tensor([[ 1,  9,  8,  5,  2, 11, 12, 10],
        [12,  6,  8, 14,  0,  0,  0,  0],
        [ 7,  4,  3,  6, 13,  7,  0,  0]])

In [119]:
seq_tensor.shape

torch.Size([3, 8])

In [120]:
seq_tensor = seq_tensor[[0, 2, 1]]

In [121]:
seq_tensor

tensor([[ 1,  9,  8,  5,  2, 11, 12, 10],
        [ 7,  4,  3,  6, 13,  7,  0,  0],
        [12,  6,  8, 14,  0,  0,  0,  0]])

In [122]:
emb_net = nn.Embedding(len(vocab), 4, padding_idx=0)

In [123]:
emb = emb_net(seq_tensor)

In [124]:
emb.shape

torch.Size([3, 8, 4])

In [125]:
lstm = nn.LSTM(4, 5, batch_first=True)

In [126]:
emb

tensor([[[ 0.3671,  1.3340,  0.8594, -0.3965],
         [ 1.0585, -1.7917,  1.2432, -0.4402],
         [-0.6276,  0.2203,  0.0834,  0.0284],
         [-1.3854,  0.5379, -0.2663, -0.4320],
         [-2.2702, -0.1355, -0.2149,  0.1521],
         [ 1.0618,  1.0721,  0.7986,  0.1014],
         [ 0.1155,  0.7137,  0.3804, -2.0123],
         [-1.1377, -1.4786,  0.9397, -0.7802]],

        [[-1.2943,  0.5872, -1.7636,  0.6925],
         [ 1.7885,  1.1710,  0.5277, -0.0941],
         [-1.3338, -1.9147, -0.6878,  0.2971],
         [-0.4266, -0.8293, -0.5631,  2.1739],
         [ 0.4974, -0.5883,  0.2990, -0.4474],
         [-1.2943,  0.5872, -1.7636,  0.6925],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.1155,  0.7137,  0.3804, -2.0123],
         [-0.4266, -0.8293, -0.5631,  2.1739],
         [-0.6276,  0.2203,  0.0834,  0.0284],
         [ 0.7318,  0.0792,  0.5259,  0.2827],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         

In [127]:
seq_lengths = torch.tensor([lengths[0], lengths[2], lengths[1]])

In [128]:
seq_lengths

tensor([8, 6, 4])

In [129]:
emb, emb.shape

(tensor([[[ 0.3671,  1.3340,  0.8594, -0.3965],
          [ 1.0585, -1.7917,  1.2432, -0.4402],
          [-0.6276,  0.2203,  0.0834,  0.0284],
          [-1.3854,  0.5379, -0.2663, -0.4320],
          [-2.2702, -0.1355, -0.2149,  0.1521],
          [ 1.0618,  1.0721,  0.7986,  0.1014],
          [ 0.1155,  0.7137,  0.3804, -2.0123],
          [-1.1377, -1.4786,  0.9397, -0.7802]],
 
         [[-1.2943,  0.5872, -1.7636,  0.6925],
          [ 1.7885,  1.1710,  0.5277, -0.0941],
          [-1.3338, -1.9147, -0.6878,  0.2971],
          [-0.4266, -0.8293, -0.5631,  2.1739],
          [ 0.4974, -0.5883,  0.2990, -0.4474],
          [-1.2943,  0.5872, -1.7636,  0.6925],
          [ 0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000]],
 
         [[ 0.1155,  0.7137,  0.3804, -2.0123],
          [-0.4266, -0.8293, -0.5631,  2.1739],
          [-0.6276,  0.2203,  0.0834,  0.0284],
          [ 0.7318,  0.0792,  0.5259,  0.2827],
          [ 0.0000,  0.0000,  0.00

In [130]:
pack = nn.utils.rnn.pack_padded_sequence(emb, seq_lengths, batch_first=True)

In [131]:
pack

PackedSequence(data=tensor([[ 0.3671,  1.3340,  0.8594, -0.3965],
        [-1.2943,  0.5872, -1.7636,  0.6925],
        [ 0.1155,  0.7137,  0.3804, -2.0123],
        [ 1.0585, -1.7917,  1.2432, -0.4402],
        [ 1.7885,  1.1710,  0.5277, -0.0941],
        [-0.4266, -0.8293, -0.5631,  2.1739],
        [-0.6276,  0.2203,  0.0834,  0.0284],
        [-1.3338, -1.9147, -0.6878,  0.2971],
        [-0.6276,  0.2203,  0.0834,  0.0284],
        [-1.3854,  0.5379, -0.2663, -0.4320],
        [-0.4266, -0.8293, -0.5631,  2.1739],
        [ 0.7318,  0.0792,  0.5259,  0.2827],
        [-2.2702, -0.1355, -0.2149,  0.1521],
        [ 0.4974, -0.5883,  0.2990, -0.4474],
        [ 1.0618,  1.0721,  0.7986,  0.1014],
        [-1.2943,  0.5872, -1.7636,  0.6925],
        [ 0.1155,  0.7137,  0.3804, -2.0123],
        [-1.1377, -1.4786,  0.9397, -0.7802]],
       grad_fn=<PackPaddedSequenceBackward0>), batch_sizes=tensor([3, 3, 3, 3, 2, 2, 1, 1]), sorted_indices=None, unsorted_indices=None)

In [132]:
pack_out, (hn, cn) = lstm(pack)

In [133]:
pack_out

PackedSequence(data=tensor([[-0.0479,  0.1212,  0.1360, -0.0552, -0.0867],
        [-0.2239, -0.0018, -0.0403,  0.0916,  0.0348],
        [-0.0582,  0.0309,  0.1993, -0.0363, -0.1940],
        [ 0.0527,  0.3471,  0.1746, -0.0436,  0.1176],
        [-0.1283,  0.1882,  0.1621, -0.1178,  0.0758],
        [ 0.1396,  0.1737,  0.0049,  0.2628,  0.0236],
        [ 0.0521,  0.1669,  0.1245,  0.0671,  0.0438],
        [ 0.0601,  0.0435,  0.0103,  0.0845,  0.1172],
        [ 0.0191,  0.0935,  0.0060,  0.1596, -0.0057],
        [-0.0837,  0.0347,  0.0886,  0.0900, -0.0941],
        [ 0.1646,  0.1336, -0.0343,  0.3357,  0.2339],
        [ 0.0511,  0.2284,  0.0769,  0.1150,  0.0718],
        [-0.1049, -0.0510,  0.0171,  0.1851, -0.0958],
        [ 0.0759,  0.1482, -0.0040,  0.2034,  0.2706],
        [-0.0709,  0.1320,  0.1601,  0.0020, -0.1178],
        [-0.1885,  0.0074, -0.0555,  0.1314,  0.2051],
        [-0.1011,  0.1170,  0.3258, -0.0443, -0.2554],
        [ 0.0254,  0.0929,  0.1277,  0.0225, 

In [134]:
hn, hn.shape

(tensor([[[ 0.0254,  0.0929,  0.1277,  0.0225, -0.1082],
          [-0.1885,  0.0074, -0.0555,  0.1314,  0.2051],
          [ 0.0511,  0.2284,  0.0769,  0.1150,  0.0718]]],
        grad_fn=<StackBackward0>),
 torch.Size([1, 3, 5]))

In [135]:
cn, cn.shape

(tensor([[[ 0.0780,  0.1852,  0.2993,  0.0389, -0.3620],
          [-0.2909,  0.0284, -0.1417,  0.5317,  0.3060],
          [ 0.1402,  0.4977,  0.1136,  0.2195,  0.1058]]],
        grad_fn=<StackBackward0>),
 torch.Size([1, 3, 5]))

In [136]:
out = nn.utils.rnn.pad_packed_sequence(pack_out, batch_first=True)

In [137]:
out

(tensor([[[-0.0479,  0.1212,  0.1360, -0.0552, -0.0867],
          [ 0.0527,  0.3471,  0.1746, -0.0436,  0.1176],
          [ 0.0521,  0.1669,  0.1245,  0.0671,  0.0438],
          [-0.0837,  0.0347,  0.0886,  0.0900, -0.0941],
          [-0.1049, -0.0510,  0.0171,  0.1851, -0.0958],
          [-0.0709,  0.1320,  0.1601,  0.0020, -0.1178],
          [-0.1011,  0.1170,  0.3258, -0.0443, -0.2554],
          [ 0.0254,  0.0929,  0.1277,  0.0225, -0.1082]],
 
         [[-0.2239, -0.0018, -0.0403,  0.0916,  0.0348],
          [-0.1283,  0.1882,  0.1621, -0.1178,  0.0758],
          [ 0.0601,  0.0435,  0.0103,  0.0845,  0.1172],
          [ 0.1646,  0.1336, -0.0343,  0.3357,  0.2339],
          [ 0.0759,  0.1482, -0.0040,  0.2034,  0.2706],
          [-0.1885,  0.0074, -0.0555,  0.1314,  0.2051],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],
 
         [[-0.0582,  0.0309,  0.1993, -0.0363, -0.1940],
          [ 0.1396,  0.17

In [138]:
out[0].shape

torch.Size([3, 8, 5])

In [139]:
emb.shape

torch.Size([3, 8, 4])

In [140]:
nn.Dropout(p=0.1)(torch.randn(2, 5, 10))

tensor([[[-1.5460, -2.5042,  0.4786,  0.8921,  1.4133,  0.7514,  2.1048,
          -0.0121,  2.6287, -3.4389],
         [-0.4235,  0.0000,  1.4360,  0.6238,  0.0000,  0.0000,  1.2670,
           2.7964, -0.6498,  0.4897],
         [-0.9694, -0.2152,  0.3140, -0.3766,  0.0000,  1.1677, -0.9263,
           0.0385, -1.9612,  0.2844],
         [-0.3100,  1.5022,  0.5568, -0.7406, -0.0820, -1.3247,  0.1136,
           1.3514,  0.7137,  0.5456],
         [ 0.3754, -0.7686,  0.0527,  0.3326, -0.5875,  0.0000, -1.5427,
           1.2762, -0.2588,  0.6040]],

        [[ 1.6713, -0.1814, -0.1206, -0.0000,  1.7031,  1.2326, -0.8841,
           0.3153, -0.5282, -2.3104],
         [-1.4563,  1.5149, -0.7979,  1.0994, -1.4102,  0.4619,  0.1596,
           0.8654,  1.3375,  0.0607],
         [ 1.4168,  0.3127,  0.3840, -0.3514,  0.3749,  0.4348,  1.9042,
           0.6755, -1.8836,  0.9926],
         [-0.8742,  1.3405,  0.6788,  0.5404,  1.0181,  2.5527, -0.4064,
          -0.0000,  2.8675,  0.5209],

In [141]:
lstm.weight_hh_l0

Parameter containing:
tensor([[-0.0333,  0.1173, -0.0640,  0.0197,  0.0359],
        [-0.3169, -0.4083,  0.3587,  0.3638,  0.0152],
        [ 0.3171, -0.0092, -0.0725, -0.3896,  0.0393],
        [-0.0629,  0.0823,  0.3987, -0.3283, -0.1105],
        [ 0.3074, -0.3461, -0.4293, -0.2412, -0.1811],
        [ 0.1837, -0.3388,  0.0512,  0.2533, -0.4404],
        [-0.1301,  0.2809,  0.2151,  0.3206,  0.2904],
        [-0.0255, -0.4137,  0.1480, -0.2196,  0.1552],
        [ 0.2892, -0.0090,  0.0429, -0.3924, -0.2510],
        [-0.3423,  0.2023,  0.0337,  0.2497,  0.1350],
        [ 0.4103,  0.3104,  0.2279, -0.3925,  0.1034],
        [-0.0767, -0.0106,  0.0750, -0.3789, -0.3944],
        [-0.4202,  0.3310,  0.0324, -0.2236, -0.3058],
        [ 0.3241, -0.2345,  0.0772,  0.0695,  0.4145],
        [-0.3109, -0.4248, -0.2422,  0.2540, -0.0280],
        [-0.3810,  0.4236, -0.1972, -0.1865, -0.0556],
        [-0.0341,  0.4008,  0.2638, -0.2003,  0.0666],
        [-0.4169,  0.1741, -0.4416,  0.0811

In [142]:
w = lstm.weight_hh_l0
w.shape

torch.Size([20, 5])

In [143]:
u, v = w.chunk(2, dim=1)

In [144]:
u

tensor([[-0.0333,  0.1173, -0.0640],
        [-0.3169, -0.4083,  0.3587],
        [ 0.3171, -0.0092, -0.0725],
        [-0.0629,  0.0823,  0.3987],
        [ 0.3074, -0.3461, -0.4293],
        [ 0.1837, -0.3388,  0.0512],
        [-0.1301,  0.2809,  0.2151],
        [-0.0255, -0.4137,  0.1480],
        [ 0.2892, -0.0090,  0.0429],
        [-0.3423,  0.2023,  0.0337],
        [ 0.4103,  0.3104,  0.2279],
        [-0.0767, -0.0106,  0.0750],
        [-0.4202,  0.3310,  0.0324],
        [ 0.3241, -0.2345,  0.0772],
        [-0.3109, -0.4248, -0.2422],
        [-0.3810,  0.4236, -0.1972],
        [-0.0341,  0.4008,  0.2638],
        [-0.4169,  0.1741, -0.4416],
        [-0.2715, -0.1549,  0.3251],
        [ 0.3530,  0.3771,  0.2422]], grad_fn=<SplitBackward0>)

In [145]:
v

tensor([[ 0.0197,  0.0359],
        [ 0.3638,  0.0152],
        [-0.3896,  0.0393],
        [-0.3283, -0.1105],
        [-0.2412, -0.1811],
        [ 0.2533, -0.4404],
        [ 0.3206,  0.2904],
        [-0.2196,  0.1552],
        [-0.3924, -0.2510],
        [ 0.2497,  0.1350],
        [-0.3925,  0.1034],
        [-0.3789, -0.3944],
        [-0.2236, -0.3058],
        [ 0.0695,  0.4145],
        [ 0.2540, -0.0280],
        [-0.1865, -0.0556],
        [-0.2003,  0.0666],
        [ 0.0811, -0.0734],
        [-0.1380,  0.3148],
        [ 0.4266,  0.3653]], grad_fn=<SplitBackward0>)

In [146]:
(torch.arange(0, 10,) >= torch.randint(4, 8, (30, )).view(3, 10).unsqueeze_(1)).size(0)

3

In [147]:
torch.arange(0, 10,) >= torch.randint(4, 8, (9, )).view(9).unsqueeze(1)

tensor([[False, False, False, False,  True,  True,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True,  True,  True],
        [False, False, False, False, False, False, False,  True,  True,  True],
        [False, False, False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False, False,  True,  True,  True,  True,  True],
        [False, False, False, False, False, False, False,  True,  True,  True],
        [False, False, False, False, False, False, False,  True,  True,  True]])

In [148]:
nn.Linear(128, 256)(torch.randn((16, 64, 92, 128))).shape

torch.Size([16, 64, 92, 256])

In [149]:
(torch.randn((3, 1, 4)) + torch.randn(( 4))).shape

torch.Size([3, 1, 4])

In [150]:
torch.exp(torch.tensor(-65504.))

tensor(0.)

Cross entropy loss

In [151]:
x = torch.randn((16, 48, 128))

In [152]:
mask = torch.randint(10, 128, size=(16, 48, 1))
mask[0][0]

tensor([104])

In [153]:
target = torch.empty((16, 48, 128), dtype=torch.int64).random_(1, 128)
target[0][0]

tensor([  1,  66,  94,  85,  29,  79,  97,  99, 100,  72,  15,  27,  79,  52,
         79,  85,  17, 104,  93,  85,  48, 122,  17,  10,  52,  98,  42,  38,
         14,  26,  14,  87,  85,  92,  80, 120,  95, 100,  50,  70,  26, 122,
         89,  64,   1,  82,   1, 109,  34, 124,  26,  82,  59,  73, 104,  73,
         63,  78, 107, 113,  40,  21,  64, 112,  13, 100,  56,  81,  66, 119,
          6,  13,  39,  85, 107,  82,  85,  65,  31,  31, 104,  98,  22,  69,
         75,  56,  45,  17,  46,  18,  59,  58,  25,  67,  11,  14,  33,  98,
         92,   8,  98,  79,  85, 116,  46,  62,  32, 106,  29,  23, 107,  98,
         96,  75,  22, 110, 122,  20,  94,  74,  25,   8, 101, 121,  44,  50,
          4,  28])

In [154]:
masked = torch.arange(0, 128, dtype=torch.long) >= mask
target.masked_fill_(masked, 0) 
pass

In [155]:
target[0][0][mask[0][0]-1:]

tensor([116,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0])

In [156]:
cross_loss = nn.CrossEntropyLoss(ignore_index=0)

In [157]:
# loss = cross_loss(input, target)

In [158]:
target[0][0]

tensor([  1,  66,  94,  85,  29,  79,  97,  99, 100,  72,  15,  27,  79,  52,
         79,  85,  17, 104,  93,  85,  48, 122,  17,  10,  52,  98,  42,  38,
         14,  26,  14,  87,  85,  92,  80, 120,  95, 100,  50,  70,  26, 122,
         89,  64,   1,  82,   1, 109,  34, 124,  26,  82,  59,  73, 104,  73,
         63,  78, 107, 113,  40,  21,  64, 112,  13, 100,  56,  81,  66, 119,
          6,  13,  39,  85, 107,  82,  85,  65,  31,  31, 104,  98,  22,  69,
         75,  56,  45,  17,  46,  18,  59,  58,  25,  67,  11,  14,  33,  98,
         92,   8,  98,  79,  85, 116,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0])

In [159]:
x = torch.randn((2, 4, 8))
x

tensor([[[ 0.2552, -0.1802,  0.2588, -0.7061, -0.8777, -1.2653,  0.0321,
           1.5530],
         [ 0.3243,  0.2790,  0.1466,  0.7425,  0.5751, -0.4438,  0.9766,
           0.1799],
         [-0.0652, -0.1049, -0.1837, -0.6695,  1.3287, -1.7559,  0.6593,
           0.4805],
         [ 0.5903,  0.8178, -0.9333, -0.6854,  0.9481,  0.7393,  0.3437,
           0.0594]],

        [[ 0.7289,  0.7445,  0.5808,  0.7623, -2.6973,  0.2699, -0.7284,
           1.2703],
         [-0.9471, -0.5631,  0.7597, -0.1863, -0.0955, -1.4100,  0.2837,
           2.0454],
         [ 0.2972, -0.9666, -1.2491, -0.0188, -0.7169,  1.4711,  1.8277,
          -0.6550],
         [-1.7866, -0.5917,  1.0615, -0.8268, -0.9765,  0.1190, -2.1398,
           1.4746]]])

In [160]:
target = torch.empty((2, 4), dtype=torch.int64).random_(1, 8)
target

tensor([[1, 7, 1, 3],
        [5, 4, 6, 2]])

In [161]:
y = x.gather(dim=-1, index=target.unsqueeze(2))

In [162]:
y.shape, y

(torch.Size([2, 4, 1]),
 tensor([[[-0.1802],
          [ 0.1799],
          [-0.1049],
          [-0.6854]],
 
         [[ 0.2699],
          [-0.0955],
          [ 1.8277],
          [ 1.0615]]]))

In [163]:
net = nn.Linear(10, 50)

In [164]:
net.half()

Linear(in_features=10, out_features=50, bias=True)

In [165]:
for p in net.parameters():
    print(p.dtype)

torch.float16
torch.float16


In [166]:
for p in net.parameters():
    p.to(torch.float)
    print(p.dtype)
    

torch.float16
torch.float16


In [167]:
for p in net.parameters():
    print(p.requires_grad)

True
True


In [168]:
for p in net.parameters():
    print(p.detach().requires_grad, p.dtype)

False torch.float16
False torch.float16


In [169]:
net.float()
loss = net(torch.randn((32, 10), dtype=torch.float32)).sum()

In [170]:
loss.backward()

In [171]:
for p in net.parameters():
    print(type(p.grad), p.grad.requires_grad)

<class 'torch.Tensor'> False
<class 'torch.Tensor'> False


In [172]:
nn.utils.clip_grad_norm_(net.parameters(), 5.0)

tensor(267.4038)

In [173]:
math.exp(math.log(0.01) / 100)

0.954992586021436

In [174]:
0.954992586021436 ** 100

0.010000000000000049

In [188]:
x = torch.empty((4, 5)).float().uniform_(-1, 1)

In [189]:
x

tensor([[ 0.1155,  0.2325,  0.9164, -0.2074, -0.8107],
        [-0.6912,  0.9049,  0.6055, -0.1095, -0.6014],
        [ 0.7091, -0.4299,  0.0394, -0.9688,  0.5415],
        [ 0.9204,  0.5323,  0.6835,  0.1981, -0.3870]])

In [190]:
y = torch.zeros_like(x)

In [191]:
y

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [192]:
z = x.to(y)

In [196]:
z += 3

In [198]:
z, y, x

(tensor([[4.1155, 4.2325, 4.9164, 3.7926, 3.1893],
         [3.3088, 4.9049, 4.6055, 3.8905, 3.3986],
         [4.7091, 3.5701, 4.0394, 3.0312, 4.5415],
         [4.9204, 4.5323, 4.6835, 4.1981, 3.6130]]),
 tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 tensor([[4.1155, 4.2325, 4.9164, 3.7926, 3.1893],
         [3.3088, 4.9049, 4.6055, 3.8905, 3.3986],
         [4.7091, 3.5701, 4.0394, 3.0312, 4.5415],
         [4.9204, 4.5323, 4.6835, 4.1981, 3.6130]]))