In [1]:
from torch.utils.data import Sampler as TorchSampler, DataLoader, Dataset
import torch


In [2]:
class TestDat(Dataset):
    
    def __init__(self) -> None:
        self.seq = list(range(100))
        
    def __getitem__(self, index):
        return self.seq[index]
    
    def __len__(self):
        return len(self.seq)

In [38]:

class Sampler(TorchSampler):
    
    def __init__(self, dataset, batch_size, seeds=[0]):
        print("ok")
        self.dataset = dataset
        data_len = len(dataset)
        
        num_samples = data_len // batch_size
        
        num_samples *= batch_size
        print("number samples is ", num_samples)
        
        self.num_samples = num_samples
        
        indices = list(range(len(dataset)))
        
        indices = torch.tensor(indices, dtype=torch.int64)
        
        self.indices = indices
        self.seeds = seeds
        self.epoch = 0  
        self.n = len(self.dataset)  
    
    def init_rng(self):
        rng = torch.Generator()
        
        rng.manual_seed(self.seeds[self.epoch])
        
        return rng
        
    def set_epoch(self, epoch):
        self.epoch = epoch
    
    def __iter__(self):
        rng = self.init_rng()
        print(torch.randperm(len(self.indices), generator=rng))
        for k, i in enumerate(torch.randperm(len(self.indices), generator=rng)):
            if k == self.num_samples:
                print("Done")
                break
            print(i, k, self.n)
            yield self.indices[i]
        

    def __len__(self):
        return self.num_samples

batch_size = 6
dst = TestDat() 
sampler = Sampler(dst, batch_size=6,)
loader = DataLoader(dst, batch_size=6, sampler=sampler)


ok
number samples is  96


In [39]:
for v in loader:
    print(v)

tensor([44, 19, 93, 90, 71, 69, 37, 95, 53, 91, 81, 42, 80, 85, 74, 56, 76, 63,
        82, 40, 26, 92, 57, 10, 16, 66, 89, 41, 97,  8, 31, 24, 35, 30, 65,  7,
        98, 23, 20, 29, 78, 61, 94, 15,  4, 52, 59,  5, 54, 46,  3, 28,  2, 70,
         6, 60, 49, 68, 55, 72, 79, 77, 45,  1, 32, 34, 11,  0, 22, 12, 87, 50,
        25, 47, 36, 96,  9, 83, 62, 84, 18, 17, 75, 67, 13, 48, 39, 21, 64, 88,
        38, 27, 14, 73, 33, 58, 86, 43, 99, 51])
tensor(12) 0 100
tensor(42) 1 100
tensor(28) 2 100
tensor(68) 3 100
tensor(79) 4 100
tensor(89) 5 100
tensor([12, 42, 28, 68, 79, 89])
tensor(72) 6 100
tensor(61) 7 100
tensor(15) 8 100
tensor(88) 9 100
tensor(18) 10 100
tensor(99) 11 100
tensor([72, 61, 15, 88, 18, 99])
tensor(16) 12 100
tensor(8) 13 100
tensor(86) 14 100
tensor(29) 15 100
tensor(34) 16 100
tensor(0) 17 100
tensor([16,  8, 86, 29, 34,  0])
tensor(80) 18 100
tensor(74) 19 100
tensor(94) 20 100
tensor(83) 21 100
tensor(53) 22 100
tensor(52) 23 100
tensor([80, 74, 94, 83, 53, 52])