In [2]:
import jax.numpy as jnp
from jax import grad, jit, vmap, random
import numpy as np

In [6]:
key = random.PRNGKey(0)
x = random.normal(key, (10, 10), dtype=jnp.float32)
x

Array([[-1.9810703 ,  1.0481724 ,  0.8898191 ,  0.035166  , -0.9473585 ,
         0.85125655,  0.0312455 , -0.38968593,  0.01320801, -0.42052191],
       [-1.2335656 , -1.2524313 ,  0.98738754,  0.80595386, -0.41083032,
         0.9738211 , -0.6879051 , -0.79305184, -1.973272  ,  0.15538813],
       [-0.5808592 ,  1.5863018 ,  0.28492707,  0.63823265,  0.06069284,
         0.39795223, -0.22721659, -0.7053813 ,  0.6570658 , -1.8061262 ],
       [ 1.0407923 , -1.9712908 , -0.06924485,  0.60396975, -0.38382423,
         0.32502025,  0.28134054, -1.5120755 ,  0.874926  , -0.79578525],
       [ 0.37597522, -0.4551476 ,  0.13549148,  1.2002596 ,  1.7405769 ,
         0.98859143, -0.02708917, -1.184509  , -0.9568104 ,  0.9804613 ],
       [ 0.2211316 ,  0.48654258,  1.6977485 ,  0.20131212, -0.58212173,
        -0.39210144,  0.05007881,  2.0786808 ,  0.1626376 , -0.6914365 ],
       [ 0.48800626,  1.7702677 , -0.05003558,  1.2240386 ,  0.54848504,
         1.6315418 ,  0.46113688, -0.14762828

In [7]:
y = np.array(x)

In [8]:
y

array([[-1.9810703 ,  1.0481724 ,  0.8898191 ,  0.035166  , -0.9473585 ,
         0.85125655,  0.0312455 , -0.38968593,  0.01320801, -0.42052191],
       [-1.2335656 , -1.2524313 ,  0.98738754,  0.80595386, -0.41083032,
         0.9738211 , -0.6879051 , -0.79305184, -1.973272  ,  0.15538813],
       [-0.5808592 ,  1.5863018 ,  0.28492707,  0.63823265,  0.06069284,
         0.39795223, -0.22721659, -0.7053813 ,  0.6570658 , -1.8061262 ],
       [ 1.0407923 , -1.9712908 , -0.06924485,  0.60396975, -0.38382423,
         0.32502025,  0.28134054, -1.5120755 ,  0.874926  , -0.79578525],
       [ 0.37597522, -0.4551476 ,  0.13549148,  1.2002596 ,  1.7405769 ,
         0.98859143, -0.02708917, -1.184509  , -0.9568104 ,  0.9804613 ],
       [ 0.2211316 ,  0.48654258,  1.6977485 ,  0.20131212, -0.58212173,
        -0.39210144,  0.05007881,  2.0786808 ,  0.1626376 , -0.6914365 ],
       [ 0.48800626,  1.7702677 , -0.05003558,  1.2240386 ,  0.54848504,
         1.6315418 ,  0.46113688, -0.14762828

In [9]:
x + y

Array([[-3.9621406 ,  2.0963447 ,  1.7796382 ,  0.07033201, -1.894717  ,
         1.7025131 ,  0.062491  , -0.77937186,  0.02641602, -0.84104383],
       [-2.4671311 , -2.5048625 ,  1.9747751 ,  1.6119077 , -0.82166064,
         1.9476422 , -1.3758101 , -1.5861037 , -3.946544  ,  0.31077626],
       [-1.1617184 ,  3.1726036 ,  0.56985414,  1.2764653 ,  0.12138568,
         0.79590446, -0.45443317, -1.4107625 ,  1.3141316 , -3.6122525 ],
       [ 2.0815847 , -3.9425817 , -0.13848971,  1.2079395 , -0.76764846,
         0.6500405 ,  0.5626811 , -3.024151  ,  1.749852  , -1.5915705 ],
       [ 0.75195044, -0.9102952 ,  0.27098295,  2.4005191 ,  3.4811537 ,
         1.9771829 , -0.05417835, -2.369018  , -1.9136208 ,  1.9609226 ],
       [ 0.4422632 ,  0.97308517,  3.395497  ,  0.40262425, -1.1642435 ,
        -0.7842029 ,  0.10015761,  4.1573615 ,  0.3252752 , -1.382873  ],
       [ 0.9760125 ,  3.5405354 , -0.10007115,  2.4480772 ,  1.0969701 ,
         3.2630837 ,  0.92227376, -0.29525656

In [11]:
x.device()

StreamExecutorGpuDevice(id=0, process_index=0, slice_index=0)

In [12]:
x += 1

In [13]:
x

Array([[-0.9810703 ,  2.0481725 ,  1.8898191 ,  1.035166  ,  0.05264151,
         1.8512566 ,  1.0312455 ,  0.6103141 ,  1.013208  ,  0.5794781 ],
       [-0.23356557, -0.25243127,  1.9873875 ,  1.8059539 ,  0.5891697 ,
         1.9738212 ,  0.31209493,  0.20694816, -0.97327197,  1.1553881 ],
       [ 0.41914082,  2.5863018 ,  1.2849271 ,  1.6382327 ,  1.0606928 ,
         1.3979522 ,  0.7727834 ,  0.29461873,  1.6570659 , -0.80612624],
       [ 2.0407925 , -0.9712908 ,  0.93075514,  1.6039698 ,  0.6161758 ,
         1.3250203 ,  1.2813406 , -0.51207554,  1.874926  ,  0.20421475],
       [ 1.3759753 ,  0.5448524 ,  1.1354915 ,  2.2002597 ,  2.7405767 ,
         1.9885914 ,  0.9729108 , -0.18450904,  0.04318959,  1.9804614 ],
       [ 1.2211316 ,  1.4865426 ,  2.6977487 ,  1.2013121 ,  0.41787827,
         0.6078986 ,  1.0500787 ,  3.0786808 ,  1.1626376 ,  0.30856347],
       [ 1.4880062 ,  2.7702677 ,  0.9499644 ,  2.2240386 ,  1.548485  ,
         2.6315417 ,  1.4611368 ,  0.8523717 

In [15]:
try:
    x[0] = 0
except Exception as e:
    print(e)

'<class 'jaxlib.xla_extension.ArrayImpl'>' object does not support item assignment. JAX arrays are immutable. Instead of ``x[idx] = y``, use ``x = x.at[idx].set(y)`` or another .at[] method: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html


In [16]:
x.at[0].set(0)

Array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [-0.23356557, -0.25243127,  1.9873875 ,  1.8059539 ,  0.5891697 ,
         1.9738212 ,  0.31209493,  0.20694816, -0.97327197,  1.1553881 ],
       [ 0.41914082,  2.5863018 ,  1.2849271 ,  1.6382327 ,  1.0606928 ,
         1.3979522 ,  0.7727834 ,  0.29461873,  1.6570659 , -0.80612624],
       [ 2.0407925 , -0.9712908 ,  0.93075514,  1.6039698 ,  0.6161758 ,
         1.3250203 ,  1.2813406 , -0.51207554,  1.874926  ,  0.20421475],
       [ 1.3759753 ,  0.5448524 ,  1.1354915 ,  2.2002597 ,  2.7405767 ,
         1.9885914 ,  0.9729108 , -0.18450904,  0.04318959,  1.9804614 ],
       [ 1.2211316 ,  1.4865426 ,  2.6977487 ,  1.2013121 ,  0.41787827,
         0.6078986 ,  1.0500787 ,  3.0786808 ,  1.1626376 ,  0.30856347],
       [ 1.4880062 ,  2.7702677 ,  0.9499644 ,  2.2240386 ,  1.548485  ,
         2.6315417 ,  1.4611368 ,  0.8523717 

In [18]:
x *= 2

In [19]:
x

Array([[-1.9621406 ,  4.096345  ,  3.7796383 ,  2.070332  ,  0.10528302,
         3.7025132 ,  2.062491  ,  1.2206281 ,  2.026416  ,  1.1589562 ],
       [-0.46713114, -0.50486255,  3.974775  ,  3.6119077 ,  1.1783394 ,
         3.9476423 ,  0.62418985,  0.41389632, -1.9465439 ,  2.3107762 ],
       [ 0.83828163,  5.1726036 ,  2.5698543 ,  3.2764654 ,  2.1213856 ,
         2.7959044 ,  1.5455668 ,  0.58923745,  3.3141317 , -1.6122525 ],
       [ 4.081585  , -1.9425817 ,  1.8615103 ,  3.2079396 ,  1.2323515 ,
         2.6500406 ,  2.5626812 , -1.0241511 ,  3.749852  ,  0.4084295 ],
       [ 2.7519505 ,  1.0897048 ,  2.270983  ,  4.4005194 ,  5.4811535 ,
         3.9771829 ,  1.9458216 , -0.36901808,  0.08637917,  3.9609227 ],
       [ 2.4422631 ,  2.9730852 ,  5.3954973 ,  2.4026241 ,  0.83575654,
         1.2157972 ,  2.1001575 ,  6.1573615 ,  2.3252752 ,  0.61712694],
       [ 2.9760125 ,  5.5405354 ,  1.8999288 ,  4.448077  ,  3.09697   ,
         5.2630835 ,  2.9222736 ,  1.7047434 

In [1]:
x.shape

NameError: name 'x' is not defined